import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { FwvProject } from '../src/core/project.mjs';
import { ReskinWorkflows } from '../src/workflows/reskin.mjs';
import { importSpine } from '../src/spine/application.mjs';
import { createReskinFixture } from '../examples/reskin-fixture/create.mjs';
import { run } from '../bin/fwv.mjs';

test('CLI bundle preserves exact reference and claim; analysis exports current prompt; completion uses actual provenance', async t => {
  const prefix = path.join(os.tmpdir(), 'fwv-local-cli-'), root = await fs.mkdtemp(prefix);
  const project = new FwvProject(root), workflows = new ReskinWorkflows({ project });
  t.after(async () => { workflows.close(); assert.equal(path.dirname(root), path.resolve(os.tmpdir())); assert.ok(root.startsWith(prefix)); await fs.rm(root, { recursive: true, force: true }); });
  await project.init({ name: 'local CLI fixture' });
  const template = await importSpine(project, await createReskinFixture());
  let workflow = await workflows.create({ templateAssetId: template.id, templateRevisionId: template.selectedRevisionId, name: 'test', brief: 'fixture only', mode: 'local' });
  workflow = await workflows.generate({ workflowId: workflow.assetId, requestId: 'local-cli-fixture' });
  const attempt = workflow.attempts[0];
  const args = ['--project', root];
  const identity = ['--workflow', workflow.assetId, '--attempt', attempt.id];
  const claimed = await run(['local-claim', ...args, ...identity, '--worker', 'cli-test', '--out', path.join(root, 'bundles')]);
  const task = JSON.parse(await fs.readFile(claimed.taskPath, 'utf8'));
  const reference = await project.readArtifact(task.reference);
  assert.deepEqual(await fs.readFile(task.referencePath), reference.buffer);
  assert.equal(task.referenceSha256, createHash('sha256').update(reference.buffer).digest('hex'));
  const retry = await run(['local-claim', ...args, ...identity, '--worker', 'cli-test', '--out', path.join(root, 'bundles')]);
  assert.notEqual(claimed.bundle, retry.bundle); assert.equal(retry.task.claimId, claimed.task.claimId);
  const readOnly = await run(['local-task', ...args, ...identity]); assert.equal(readOnly.task.claimId, undefined);
  const analysisPath = path.join(root, 'analysis.json');
  await fs.writeFile(analysisPath, JSON.stringify({ summary: 'CLI current analysis', partNotes: { head: 'Preserve face' }, risks: [] }));
  const analyzed = await run(['local-analyze', ...args, '--task', claimed.taskPath, '--analysis-file', analysisPath]);
  assert.match(await fs.readFile(analyzed.promptPath, 'utf8'), /CLI current analysis/);
  assert.doesNotMatch(await fs.readFile(task.promptPath, 'utf8'), /CLI current analysis/);
  const tampered = path.join(root, 'other-project-task.json');
  await fs.writeFile(tampered, JSON.stringify({ ...task, projectId: 'project_00000000000000000000000000000000' }));
  await assert.rejects(run(['local-dispatch', ...args, '--task', tampered]), /different FWV project/);
  await run(['local-dispatch', ...args, '--task', claimed.taskPath]);
  await assert.rejects(run(['local-dispatch', ...args, '--task', claimed.taskPath]), /已登记/);
  const uncertain = await run(['local-fail', ...args, '--task', claimed.taskPath, '--message', 'TEST: worker interrupted after dispatch; result can still arrive']);
  assert.equal(uncertain.attempts[0].status, 'unknown');
  const imported = await project.importImage({ name: 'TEST: source reused, no model', fileName: 'mock.png', buffer: reference.buffer });
  const completed = await run(['local-complete', ...args, '--task', claimed.taskPath, '--image-asset', imported.id, '--image-revision', imported.selectedRevisionId,
    '--provider', 'test-fixture', '--model', 'mock-raster', '--tool', 'local-test']);
  assert.equal(completed.attempts[0].status, 'succeeded');
  assert.equal(completed.attempts[0].local.receipt.execution.provider, 'test-fixture');
});
