use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use anyhow::{Context, Result};

use crate::support::proto::{parse_dir, FieldRule, ProtoField, ProtoMessage, ProtoSchema};
use crate::support::util::{join_blocks, pascal, snake, write_utf8};

pub fn generate(
    project_root: &Path,
    schema_dir: &Path,
    gd_out_dir: &Path,
    rust_out_dir: &Path,
    core_out_dir: &Path,
) -> Result<()> {
    let schema = parse_dir(schema_dir)?;
    let action_root = schema
        .messages
        .get("PlayerAction")
        .context("schema/bridge 必须包含 PlayerAction")?;
    let event_root = schema
        .messages
        .get("GameEvent")
        .context("schema/bridge 必须包含 GameEvent")?;
    let action_variants = resolve_oneof_variants(&schema, action_root)?;
    let event_variants = resolve_oneof_variants(&schema, event_root)?;
    let common_enums = collect_bridge_enums(&schema);
    let snapshot_records = collect_snapshot_records(&schema);

    write_utf8(
        &gd_out_dir.join("_action.gd"),
        &render_gd_action(&action_variants),
    )?;
    write_utf8(
        &gd_out_dir.join("_event.gd"),
        &render_gd_event(&event_variants),
    )?;
    write_utf8(
        &gd_out_dir.join("_snapshot.gd"),
        &render_gd_snapshot(&snapshot_records, &common_enums),
    )?;

    write_utf8(
        &rust_out_dir.join("_action.rs"),
        &render_rs_action(&action_variants, &common_enums),
    )?;
    write_utf8(
        &rust_out_dir.join("_event.rs"),
        &render_rs_event(&event_variants, &common_enums),
    )?;
    write_utf8(
        &rust_out_dir.join("_snapshot.rs"),
        &render_rs_snapshot(&snapshot_records, &common_enums),
    )?;
    write_utf8(
        &rust_out_dir.join("mod.rs"),
        "// This file is generated by fw_gen. Do not edit manually.\npub mod _action;\npub mod _event;\npub mod _snapshot;\n",
    )?;

    write_utf8(
        &core_out_dir.join("_bridge_action.rs"),
        &render_core_action_types(&action_variants),
    )?;
    write_utf8(
        &core_out_dir.join("_bridge_event.rs"),
        &render_core_event_types(&event_variants, &common_enums),
    )?;
    write_utf8(
        &core_out_dir.join("_bridge_snapshot.rs"),
        &render_core_snapshot_types(&snapshot_records, &common_enums),
    )?;

    println!(
        "Generated bridge interfaces:\n  schema : {}\n  gd out : {}\n  rust out: {}\n  core out: {}",
        schema_dir.strip_prefix(project_root).unwrap_or(schema_dir).display(),
        gd_out_dir.strip_prefix(project_root).unwrap_or(gd_out_dir).display(),
        rust_out_dir.strip_prefix(project_root).unwrap_or(rust_out_dir).display(),
        core_out_dir.strip_prefix(project_root).unwrap_or(core_out_dir).display(),
    );
    Ok(())
}

#[derive(Clone)]
struct VariantDef {
    rust_variant: String,
    gd_kind: String,
    fields: Vec<ProtoField>,
}

fn resolve_oneof_variants(schema: &ProtoSchema, root: &ProtoMessage) -> Result<Vec<VariantDef>> {
    let oneof = root
        .oneofs
        .first()
        .context("bridge root message must contain oneof")?;
    let mut out = Vec::new();
    for field in &oneof.fields {
        let payload = schema
            .messages
            .get(&field.ty)
            .with_context(|| format!("missing payload message {}", field.ty))?;
        let rust_variant = payload
            .name
            .trim_end_matches("Action")
            .trim_end_matches("Event");
        out.push(VariantDef {
            rust_variant: rust_variant.to_owned(),
            gd_kind: field.name.clone(),
            fields: payload.fields.clone(),
        });
    }
    Ok(out)
}

fn collect_bridge_enums(schema: &ProtoSchema) -> BTreeMap<String, Vec<String>> {
    let mut out = BTreeMap::new();
    for (name, enum_def) in &schema.enums {
        let variants = enum_def
            .variants
            .iter()
            .filter_map(|value| bridge_enum_variant(name, value))
            .collect::<Vec<_>>();
        if !variants.is_empty() {
            out.insert(name.clone(), variants);
        }
    }
    out
}

fn collect_snapshot_records(schema: &ProtoSchema) -> Vec<ProtoMessage> {
    let allowed = ["snapshot.proto"];
    schema
        .messages
        .values()
        .filter(|message| {
            allowed.iter().any(|suffix| message.file.ends_with(suffix))
                && !message.name.ends_with("Action")
                && !message.name.ends_with("Event")
        })
        .cloned()
        .collect()
}

fn bridge_enum_variant(enum_name: &str, value: &str) -> Option<String> {
    let prefix = snake(enum_name).to_uppercase();
    let trimmed = value.strip_prefix(&(prefix + "_")).unwrap_or(value);
    if trimmed == "UNSPECIFIED" {
        return None;
    }
    Some(pascal(trimmed))
}

fn gd_type_for_field(field_type: &str, enums: &BTreeMap<String, Vec<String>>) -> &'static str {
    match field_type {
        "int32" | "int64" | "uint32" | "uint64" | "PlayerId" | "EntityId" => "int",
        "bool" => "bool",
        "string" => "String",
        "Vec2i" => "Vector2i",
        other if enums.contains_key(other) => "String",
        _ => "Variant",
    }
}

fn gd_default_for_field(field_type: &str, enums: &BTreeMap<String, Vec<String>>) -> String {
    match field_type {
        "int32" | "int64" | "uint32" | "uint64" | "PlayerId" | "EntityId" => "0".to_owned(),
        "bool" => "false".to_owned(),
        "string" => "\"\"".to_owned(),
        "Vec2i" => "Vector2i.ZERO".to_owned(),
        other if enums.contains_key(other) => {
            let default = enums
                .get(other)
                .and_then(|items| items.first())
                .cloned()
                .unwrap_or_default();
            format!("\"{default}\"")
        }
        _ => "null".to_owned(),
    }
}

fn gd_cast_expr(field_type: &str, expr: &str, enums: &BTreeMap<String, Vec<String>>) -> String {
    match field_type {
        "int32" | "int64" | "uint32" | "uint64" | "PlayerId" | "EntityId" => format!("int({expr})"),
        "bool" => format!("bool({expr})"),
        "string" => format!("str({expr})"),
        "Vec2i" => expr.to_owned(),
        other if enums.contains_key(other) => format!("str({expr})"),
        _ => expr.to_owned(),
    }
}

fn render_gd_action(variants: &[VariantDef]) -> String {
    let mut blocks = Vec::new();
    for variant in variants {
        let params = variant
            .fields
            .iter()
            .map(|field| {
                format!(
                    "{}: {}",
                    field.name,
                    gd_type_for_field(&field.ty, &BTreeMap::new())
                )
            })
            .collect::<Vec<_>>()
            .join(", ");
        let mut body = vec![
            format!("static func {}({}) -> Dictionary:", variant.gd_kind, params),
            "\treturn {".to_owned(),
            format!("\t\t\"kind\": \"{}\",", variant.gd_kind),
        ];
        for field in &variant.fields {
            body.push(format!("\t\t\"{}\": {},", field.name, field.name));
        }
        body.push("\t}".to_owned());
        blocks.push(body.join("\n"));
    }
    format!(
        "# This file is generated by fw_gen. Do not edit manually.\nextends RefCounted\nclass_name _action\n\n{}\n",
        join_blocks(&blocks)
    )
}

fn render_gd_event(variants: &[VariantDef]) -> String {
    let mut wrappers = Vec::new();
    for variant in variants {
        let mut lines = vec![
            format!("class {}:", variant.rust_variant),
            "\textends RefCounted".to_owned(),
            "".to_owned(),
            "\tvar _raw: Dictionary = {}".to_owned(),
            "".to_owned(),
            "\tstatic func wrap(raw: Dictionary):".to_owned(),
            format!("\t\tvar obj := {}.new()", variant.rust_variant),
            "\t\tobj._raw = raw".to_owned(),
            "\t\treturn obj".to_owned(),
            "".to_owned(),
            "\tfunc raw() -> Dictionary:".to_owned(),
            "\t\treturn _raw".to_owned(),
            "".to_owned(),
        ];
        for field in &variant.fields {
            let ty = gd_type_for_field(&field.ty, &BTreeMap::new());
            let default = gd_default_for_field(&field.ty, &BTreeMap::new());
            lines.push(format!("\tfunc {}() -> {}:", field.name, ty));
            lines.push(format!(
                "\t\treturn {}",
                gd_cast_expr(
                    &field.ty,
                    &format!("_raw.get(\"{}\", {})", field.name, default),
                    &BTreeMap::new()
                )
            ));
            lines.push(String::new());
        }
        wrappers.push(lines.join("\n"));
    }
    let callback_methods = variants
        .iter()
        .map(|variant| {
            format!(
                "\tfunc on_{}(cb: Callable) -> void:\n\t\t_callbacks[\"{}\"] = cb",
                snake(&variant.rust_variant),
                variant.rust_variant
            )
        })
        .collect::<Vec<_>>()
        .join("\n\n");
    let dispatch_arms = variants
        .iter()
        .map(|variant| {
            format!(
                "\t\t\t\"{}\":\n\t\t\t\tcb.call({}.wrap(raw))",
                variant.rust_variant, variant.rust_variant
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "# This file is generated by fw_gen. Do not edit manually.\nextends RefCounted\nclass_name _event\n\n{}\n\nclass Bus:\n\textends RefCounted\n\n\tvar _callbacks: Dictionary = {{}}\n\n\tfunc clear() -> void:\n\t\t_callbacks.clear()\n\n{}\n\n\tfunc dispatch(events: Array) -> void:\n\t\tfor ev in events:\n\t\t\tdispatch_one(ev)\n\n\tfunc dispatch_one(raw: Dictionary) -> void:\n\t\tvar ev_type: String = str(raw.get(\"type\", \"\"))\n\t\tvar cb: Callable = _callbacks.get(ev_type, Callable())\n\t\tif not cb.is_valid():\n\t\t\treturn\n\t\tmatch ev_type:\n{}\n\t\t\t_:\n\t\t\t\tpass\n",
        join_blocks(&wrappers),
        callback_methods,
        dispatch_arms
    )
}

fn render_gd_snapshot(records: &[ProtoMessage], enums: &BTreeMap<String, Vec<String>>) -> String {
    let record_names = records
        .iter()
        .map(|record| record.name.clone())
        .collect::<BTreeSet<_>>();
    let mut wrappers = Vec::new();
    for record in records {
        let wrapper_name = format!("Wrapped{}", record.name);
        let mut lines = vec![
            format!("class {}:", wrapper_name),
            "\textends RefCounted".to_owned(),
            "".to_owned(),
            "\tvar _raw: Dictionary = {}".to_owned(),
            "".to_owned(),
            "\tstatic func wrap(raw: Dictionary):".to_owned(),
            format!("\t\tvar obj := {}.new()", wrapper_name),
            "\t\tobj._raw = raw".to_owned(),
            "\t\treturn obj".to_owned(),
            "".to_owned(),
            "\tfunc raw() -> Dictionary:".to_owned(),
            "\t\treturn _raw".to_owned(),
            "".to_owned(),
        ];
        for field in &record.fields {
            let ty = if field.rule == FieldRule::Repeated {
                "Array".to_owned()
            } else {
                gd_type_for_field(&field.ty, enums).to_owned()
            };
            let default = if field.rule == FieldRule::Repeated {
                "[]".to_owned()
            } else {
                gd_default_for_field(&field.ty, enums)
            };
            lines.push(format!("\tfunc {}() -> {}:", field.name, ty));
            lines.push(format!(
                "\t\treturn {}",
                gd_cast_expr(
                    &field.ty,
                    &format!("_raw.get(\"{}\", {})", field.name, default),
                    enums
                )
            ));
            lines.push(String::new());
            if field.rule == FieldRule::Repeated && record_names.contains(&field.ty) {
                let inner_wrapper = format!("Wrapped{}", field.ty);
                lines.push(format!("\tfunc {}_wrapped() -> Array:", field.name));
                lines.push("\t\tvar out: Array = []".to_owned());
                lines.push(format!("\t\tfor item in {}():", field.name));
                lines.push(format!("\t\t\tout.append({inner_wrapper}.wrap(item))"));
                lines.push("\t\treturn out".to_owned());
                lines.push(String::new());
            }
        }
        wrappers.push(lines.join("\n"));
    }
    format!(
        "# This file is generated by fw_gen. Do not edit manually.\nextends RefCounted\nclass_name _snapshot\n\n{}\n",
        join_blocks(&wrappers)
    )
}

fn render_rs_action(variants: &[VariantDef], enums: &BTreeMap<String, Vec<String>>) -> String {
    let used_enums = used_bridge_enums(variants, enums);
    let enum_decoders = used_enums
        .iter()
        .map(|(name, values)| {
            let arms = values
                .iter()
                .map(|variant| format!("        \"{variant}\" => Some({name}::{variant}),"))
                .collect::<Vec<_>>()
                .join("\n");
            format!(
                "fn decode_{}(value: &str) -> Option<{}> {{\n    match value {{\n{}\n        _ => None,\n    }}\n}}",
                snake(&name),
                name,
                arms
            )
        })
        .collect::<Vec<_>>();
    let match_arms = variants
        .iter()
        .map(|variant| {
            let mut lines = vec![format!(
                "        \"{}\" => Some(PlayerAction::{} {{",
                variant.gd_kind, variant.rust_variant
            )];
            for field in &variant.fields {
                lines.push(format!(
                    "            {}: {},",
                    field.name,
                    rs_decode_expr(field, enums)
                ));
            }
            lines.push("        }),".to_owned());
            lines.join("\n")
        })
        .collect::<Vec<_>>()
        .join("\n");
    let mut out = String::new();
    out.push_str("// This file is generated by fw_gen. Do not edit manually.\nuse core::bridge::action::PlayerAction;\n");
    if !used_enums.is_empty() {
        out.push_str(&format!(
            "use core::bridge::snapshot::{{{}}};\n",
            used_enums.keys().cloned().collect::<Vec<_>>().join(", ")
        ));
    }
    out.push_str("use godot::builtin::VarDictionary;\nuse godot::prelude::*;\n\n");
    out.push_str(&join_blocks(&enum_decoders));
    if !enum_decoders.is_empty() {
        out.push_str("\n\n");
    }
    out.push_str(&format!(
        "pub fn decode(v: &Variant) -> Option<PlayerAction> {{\n    if v.is_nil() {{\n        return None;\n    }}\n\n    let dict: VarDictionary = v.to();\n    let kind = dict.get_or_nil(\"kind\").to::<GString>().to_string();\n\n    match kind.as_str() {{\n{}\n        _ => None,\n    }}\n}}\n",
        match_arms
    ));
    out
}

fn render_rs_event(variants: &[VariantDef], enums: &BTreeMap<String, Vec<String>>) -> String {
    let used_enums = used_bridge_enums(variants, enums);
    let enum_encoders = used_enums
        .iter()
        .map(|(name, values)| {
            let arms = values
                .iter()
                .map(|variant| format!("        {name}::{variant} => \"{variant}\","))
                .collect::<Vec<_>>()
                .join("\n");
            format!(
                "fn encode_{}(value: {}) -> &'static str {{\n    match value {{\n{}\n    }}\n}}",
                snake(name),
                name,
                arms
            )
        })
        .collect::<Vec<_>>();
    let match_arms = variants
        .iter()
        .map(|variant| {
            let pattern = variant
                .fields
                .iter()
                .map(|field| field.name.clone())
                .collect::<Vec<_>>()
                .join(", ");
            let mut lines = vec![format!(
                "        GameEvent::{} {{ {} }} => {{",
                variant.rust_variant, pattern
            )];
            lines.push(format!(
                "            let _ = d.insert(\"type\", \"{}\");",
                variant.rust_variant
            ));
            for field in &variant.fields {
                lines.push(format!(
                    "            let _ = d.insert(\"{}\", {});",
                    field.name,
                    rs_encode_borrowed_expr(field, &field.name, enums)
                ));
            }
            lines.push("        }".to_owned());
            lines.join("\n")
        })
        .collect::<Vec<_>>()
        .join("\n");
    let enum_imports = if used_enums.is_empty() {
        String::new()
    } else {
        format!(
            "use core::bridge::snapshot::{{{}}};\n",
            used_enums.keys().cloned().collect::<Vec<_>>().join(", ")
        )
    };
    format!(
        "// This file is generated by fw_gen. Do not edit manually.\nuse core::bridge::event::GameEvent;\n{}use godot::builtin::{{VarArray, VarDictionary, Vector2i}};\nuse godot::prelude::*;\n\n{}\n\npub fn encode_one(event: &GameEvent) -> VarDictionary {{\n    let mut d = VarDictionary::new();\n    match event {{\n{}\n    }}\n    d\n}}\n\npub fn encode_all(events: &[GameEvent]) -> VarArray {{\n    let mut out = VarArray::new();\n    for event in events {{\n        out.push(&encode_one(event).to_variant());\n    }}\n    out\n}}\n",
        enum_imports,
        join_blocks(&enum_encoders),
        match_arms
    )
}

fn render_rs_snapshot(records: &[ProtoMessage], enums: &BTreeMap<String, Vec<String>>) -> String {
    let used_enums = records
        .iter()
        .flat_map(|record| record.fields.iter())
        .filter(|field| enums.contains_key(&field.ty))
        .map(|field| field.ty.clone())
        .collect::<BTreeSet<_>>();
    let enum_encoders = used_enums
        .iter()
        .map(|name| {
            let arms = enums[name]
                .iter()
                .map(|variant| format!("        {name}::{variant} => \"{variant}\","))
                .collect::<Vec<_>>()
                .join("\n");
            format!(
                "fn encode_{}(value: {}) -> &'static str {{\n    match value {{\n{}\n    }}\n}}",
                snake(name),
                name,
                arms
            )
        })
        .collect::<Vec<_>>();
    let record_names = records
        .iter()
        .map(|record| record.name.clone())
        .collect::<BTreeSet<_>>();
    let record_fns = records
        .iter()
        .map(|record| {
            let fn_name = format!("encode_{}", snake(&record.name));
            let mut lines = vec![
                format!(
                    "pub fn {}(value: &{}) -> VarDictionary {{",
                    fn_name, record.name
                ),
                "    let mut d = VarDictionary::new();".to_owned(),
            ];
            for field in &record.fields {
                if field.rule == FieldRule::Repeated && record_names.contains(&field.ty) {
                    let nested_fn = format!("encode_{}", snake(&field.ty));
                    lines.push("    {".to_owned());
                    lines.push("        let mut arr = VarArray::new();".to_owned());
                    lines.push(format!("        for item in &value.{} {{", field.name));
                    lines.push(format!(
                        "            arr.push(&{}(item).to_variant());",
                        nested_fn
                    ));
                    lines.push("        }".to_owned());
                    lines.push(format!(
                        "        let _ = d.insert(\"{}\", arr);",
                        field.name
                    ));
                    lines.push("    }".to_owned());
                } else {
                    lines.push(format!(
                        "    let _ = d.insert(\"{}\", {});",
                        field.name,
                        rs_encode_expr(field, &format!("value.{}", field.name), enums)
                    ));
                }
            }
            lines.push("    d".to_owned());
            lines.push("}".to_owned());
            lines.join("\n")
        })
        .collect::<Vec<_>>();
    format!(
        "// This file is generated by fw_gen. Do not edit manually.\nuse core::bridge::snapshot::{{{}}};\nuse godot::builtin::{{VarArray, VarDictionary, Vector2i}};\nuse godot::prelude::*;\n\n{}\n\n{}\n",
        records
            .iter()
            .map(|record| record.name.clone())
            .chain(used_enums.iter().cloned())
            .collect::<Vec<_>>()
            .join(", "),
        join_blocks(&enum_encoders),
        join_blocks(&record_fns)
    )
}

fn used_bridge_enums(
    variants: &[VariantDef],
    enums: &BTreeMap<String, Vec<String>>,
) -> BTreeMap<String, Vec<String>> {
    variants
        .iter()
        .flat_map(|variant| variant.fields.iter())
        .filter(|field| enums.contains_key(&field.ty))
        .map(|field| field.ty.clone())
        .collect::<BTreeSet<_>>()
        .into_iter()
        .map(|name| (name.clone(), enums.get(&name).cloned().unwrap_or_default()))
        .collect()
}

fn rs_decode_expr(field: &ProtoField, enums: &BTreeMap<String, Vec<String>>) -> String {
    match field.ty.as_str() {
        "int32" => format!("dict.get_or_nil(\"{}\").to::<i64>() as i32", field.name),
        "int64" => format!("dict.get_or_nil(\"{}\").to::<i64>() as i64", field.name),
        "uint32" => format!("dict.get_or_nil(\"{}\").to::<i64>() as u32", field.name),
        "uint64" => format!("dict.get_or_nil(\"{}\").to::<i64>() as u64", field.name),
        "bool" => format!("dict.get_or_nil(\"{}\").to::<bool>()", field.name),
        "string" => format!("dict.get_or_nil(\"{}\").to::<GString>().to_string()", field.name),
        "PlayerId" | "EntityId" => format!("dict.get_or_nil(\"{}\").to::<i64>() as u8", field.name),
        "Vec2i" => format!(
            "{{ let v = dict.get_or_nil(\"{}\").to::<Vector2i>(); crate::bridge_codec::godot_to_vec2i(v) }}",
            field.name
        ),
        other if enums.contains_key(other) => {
            format!(
                "decode_{}(&dict.get_or_nil(\"{}\").to::<GString>().to_string())?",
                snake(other),
                field.name
            )
        }
        other => format!("/* unsupported {} */ Default::default()", other),
    }
}

fn rs_encode_expr(field: &ProtoField, expr: &str, enums: &BTreeMap<String, Vec<String>>) -> String {
    match field.ty.as_str() {
        "int32" | "int64" | "uint32" | "uint64" => format!("Variant::from({expr} as i64)"),
        "bool" => format!("Variant::from({expr})"),
        "string" => format!("Variant::from({expr}.clone())"),
        "PlayerId" | "EntityId" => format!("Variant::from({expr}.0 as i64)"),
        "Vec2i" => format!("Vector2i::new({expr}.x, {expr}.y).to_variant()"),
        other if enums.contains_key(other) => {
            format!("Variant::from(encode_{}({expr}))", snake(other))
        }
        _ => format!("Variant::nil() /* unsupported {} */", field.ty),
    }
}

fn rs_encode_borrowed_expr(
    field: &ProtoField,
    expr: &str,
    enums: &BTreeMap<String, Vec<String>>,
) -> String {
    match field.ty.as_str() {
        "int32" | "int64" | "uint32" | "uint64" => format!("Variant::from(*{expr} as i64)"),
        "bool" => format!("Variant::from(*{expr})"),
        "string" => format!("Variant::from({expr}.clone())"),
        "PlayerId" | "EntityId" => format!("Variant::from({expr}.0 as i64)"),
        "Vec2i" => format!("Vector2i::new({expr}.x, {expr}.y).to_variant()"),
        other if enums.contains_key(other) => {
            format!("Variant::from(encode_{}(*{expr}))", snake(other))
        }
        _ => format!("Variant::nil() /* unsupported {} */", field.ty),
    }
}

fn render_core_action_types(variants: &[VariantDef]) -> String {
    let variant_blocks = variants
        .iter()
        .map(|variant| {
            let fields = variant
                .fields
                .iter()
                .map(|field| format!("{}: {}", field.name, core_rust_type(&field.ty)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("    {} {{ {} }},", variant.rust_variant, fields)
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "// This file is generated by fw_gen. Do not edit manually.\n#[derive(Clone, PartialEq, Debug, serde::Serialize, serde::Deserialize)]\n#[serde(tag = \"kind\", rename_all = \"snake_case\")]\npub enum PlayerAction {{\n{}\n}}\n",
        variant_blocks
    )
}

fn render_core_event_types(
    variants: &[VariantDef],
    enums: &BTreeMap<String, Vec<String>>,
) -> String {
    let imports = core_bridge_imports(variants, enums);
    let can_copy = variants.iter().all(|variant| {
        variant
            .fields
            .iter()
            .all(|field| core_type_is_copy(&field.ty, field.rule == FieldRule::Repeated))
    });
    let derives = if can_copy {
        "#[derive(Clone, Copy, PartialEq, Debug, serde::Serialize, serde::Deserialize)]"
    } else {
        "#[derive(Clone, PartialEq, Debug, serde::Serialize, serde::Deserialize)]"
    };
    let variant_blocks = variants
        .iter()
        .map(|variant| {
            let fields = variant
                .fields
                .iter()
                .map(|field| format!("{}: {}", field.name, core_rust_type(&field.ty)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("    {} {{ {} }},", variant.rust_variant, fields)
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "// This file is generated by fw_gen. Do not edit manually.\n{}\n{}\npub enum GameEvent {{\n{}\n}}\n",
        imports,
        derives,
        variant_blocks
    )
}

fn render_core_snapshot_types(
    records: &[ProtoMessage],
    enums: &BTreeMap<String, Vec<String>>,
) -> String {
    let mut blocks = Vec::new();
    blocks.push("// This file is generated by fw_gen. Do not edit manually.".to_owned());
    let needs_ids = records.iter().flat_map(|record| record.fields.iter()).any(|field| {
        matches!(field.ty.as_str(), "PlayerId" | "EntityId")
    });
    if needs_ids {
        blocks.push("use crate::ids::{EntityId, PlayerId};".to_owned());
    }
    blocks.push("use fw::Vec2i;".to_owned());
    blocks.push(String::new());

    for (name, variants) in enums {
        let enum_variants = variants
            .iter()
            .map(|variant| format!("    {variant},"))
            .collect::<Vec<_>>()
            .join("\n");
        let default_variant = variants
            .first()
            .cloned()
            .unwrap_or_else(|| "Default".to_owned());
        blocks.push(format!(
            "#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, serde::Serialize, serde::Deserialize)]\npub enum {name} {{\n{enum_variants}\n}}\n\nimpl Default for {name} {{\n    fn default() -> Self {{\n        Self::{default_variant}\n    }}\n}}"
        ));
        blocks.push(String::new());
    }

    for record in records {
        let fields = record
            .fields
            .iter()
            .map(|field| format!("    pub {}: {},", field.name, core_field_rust_type(field)))
            .collect::<Vec<_>>()
            .join("\n");
        let derives = if record
            .fields
            .iter()
            .all(|field| core_type_is_copy(&field.ty, field.rule == FieldRule::Repeated))
        {
            "#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default, serde::Serialize, serde::Deserialize)]"
        } else {
            "#[derive(Clone, PartialEq, Debug, Default, serde::Serialize, serde::Deserialize)]"
        };
        blocks.push(format!(
            "{derives}\npub struct {} {{\n{}\n}}",
            record.name, fields
        ));
        blocks.push(String::new());
    }

    format!("{}\n", blocks.join("\n"))
}

fn core_bridge_imports(variants: &[VariantDef], enums: &BTreeMap<String, Vec<String>>) -> String {
    let mut lines = Vec::new();
    let mut needs_ids = false;
    let mut needs_vec2i = false;
    let mut enum_imports = BTreeSet::new();

    for field in variants.iter().flat_map(|variant| variant.fields.iter()) {
        match field.ty.as_str() {
            "PlayerId" | "EntityId" => needs_ids = true,
            "Vec2i" => needs_vec2i = true,
            other if enums.contains_key(other) => {
                enum_imports.insert(other.to_owned());
            }
            _ => {}
        }
    }

    if needs_ids {
        lines.push("use crate::ids::{EntityId, PlayerId};".to_owned());
    }
    if needs_vec2i {
        lines.push("use fw::Vec2i;".to_owned());
    }
    if !enum_imports.is_empty() {
        lines.push(format!(
            "use crate::bridge::snapshot::{{{}}};",
            enum_imports.into_iter().collect::<Vec<_>>().join(", ")
        ));
    }

    if lines.is_empty() {
        String::new()
    } else {
        format!("{}\n", lines.join("\n"))
    }
}

fn core_field_rust_type(field: &ProtoField) -> String {
    if field.rule == FieldRule::Repeated {
        return format!("Vec<{}>", core_rust_type(&field.ty));
    }
    core_rust_type(&field.ty)
}

fn core_rust_type(proto_type: &str) -> String {
    match proto_type {
        "int32" => "i32".to_owned(),
        "int64" => "i64".to_owned(),
        "uint32" => "u32".to_owned(),
        "uint64" => "u64".to_owned(),
        "bool" => "bool".to_owned(),
        "string" => "String".to_owned(),
        "PlayerId" => "PlayerId".to_owned(),
        "EntityId" => "EntityId".to_owned(),
        "Vec2i" => "Vec2i".to_owned(),
        other => other.to_owned(),
    }
}

fn core_type_is_copy(proto_type: &str, repeated: bool) -> bool {
    if repeated {
        return false;
    }
    matches!(
        proto_type,
        "int32"
            | "int64"
            | "uint32"
            | "uint64"
            | "bool"
            | "PlayerId"
            | "EntityId"
            | "Vec2i"
            | "EntityKind"
            | "WeaponSlot"
            | "WeaponPhase"
    )
}
