using System.Text;

static class BridgeGen
{
    public static void Generate(string root, FwConfig config)
    {
        var schemaDir = config.BridgeSchemaDir(root);
        var gdDir = config.GodotGenDir(root);
        Directory.CreateDirectory(gdDir);

        GenerateBridgeGd(schemaDir, gdDir);
        GenerateTypesCs(root, config, schemaDir);
        GenerateCodecCs(root, config);
        GenerateIntentCodecCs(root, config, schemaDir);
        GenerateEventCodecCs(root, config, schemaDir);
        GeneratePacketCodecCs(root, config, schemaDir);
        Console.WriteLine($"generated bridge gd scripts: {gdDir}");
    }

    private static void GenerateBridgeGd(string schemaDir, string gdDir)
    {
        var schema = ProtoSchema.ParseFiles(SchemaFiles(schemaDir));
        var text = new StringBuilder();
        text.AppendLine("# This file is generated by fwgen. Do not edit manually.");
        text.AppendLine("extends RefCounted");
        text.AppendLine("class_name Bridge");
        text.AppendLine();
        text.Append(RenderGdValue(schema));
        text.AppendLine();
        text.Append(RenderGdIntent(schema));
        text.AppendLine();
        text.Append(RenderGdEvent(schema));
        text.AppendLine();
        text.Append(RenderGdView(schema));
        text.AppendLine();
        text.Append(RenderGdPacket(schema));

        TextUtil.WriteText(Path.Combine(gdDir, "_bridge.gd"), text.ToString());
        DeleteLegacyGd(gdDir);
    }

    private static string[] SchemaFiles(string schemaDir)
    {
        var names = new[] { "value.proto", "intent.proto", "view.proto", "event.proto", "packet.proto" };
        return names.Select(name => Path.Combine(schemaDir, name)).Where(File.Exists).ToArray();
    }

    private static void DeleteLegacyGd(string gdDir)
    {
        foreach (var name in new[]
        {
            "_action.gd",
            "_action.gd.uid",
            "_input.gd",
            "_input.gd.uid",
            "_event.gd",
            "_event.gd.uid",
            "_snapshot.gd",
            "_snapshot.gd.uid",
            "_view.gd",
            "_view.gd.uid",
        })
        {
            var path = Path.Combine(gdDir, name);
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }
    }

    private static string RenderGdValue(ProtoSchema schema)
    {
        var text = new StringBuilder();
        text.AppendLine("class Value:");
        text.AppendLine("\textends RefCounted");
        RenderGdStringEnum(text, schema, "EntityKind");
        RenderGdStringEnum(text, schema, "ItemKind");
        RenderGdStringEnum(text, schema, "WeaponSlot");
        RenderGdStringEnum(text, schema, "WeaponPhase");
        return text.ToString();
    }

    private static void RenderGdStringEnum(StringBuilder text, ProtoSchema schema, string enumName)
    {
        if (!schema.Enums.TryGetValue(enumName, out var protoEnum))
        {
            return;
        }

        text.AppendLine();
        text.AppendLine($"\tclass {enumName}:");
        text.AppendLine("\t\textends RefCounted");
        foreach (var value in protoEnum.Values.Where(item => item.Number != 0))
        {
            var name = EnumTail(value.Name);
            text.AppendLine($"\t\tconst {GdConstName(name)} := \"{Pascal(name)}\"");
        }
    }

    private static string RenderGdIntent(ProtoSchema schema)
    {
        var text = new StringBuilder();
        text.AppendLine("class Intent:");
        text.AppendLine("\textends RefCounted");
        if (schema.Enums.TryGetValue("PlayerButton", out var buttons))
        {
            foreach (var value in buttons.Values.Where(item => item.Number != 0))
            {
                text.AppendLine($"\tconst BTN_{EnumTail(value.Name).ToUpperInvariant()} := {value.Number}");
            }
        }
        if (!schema.Messages.TryGetValue("PlayerAction", out var actionRoot))
        {
            return text.ToString();
        }

        foreach (var variant in actionRoot.Fields.Where(item => item.IsOneof))
        {
            if (!schema.Messages.TryGetValue(variant.Type, out var action))
            {
                continue;
            }

            text.AppendLine();
            var args = action.Fields.Select(item => $"{item.Name}: {GdArgType(item)}");
            text.AppendLine($"\tstatic func {variant.Name}({string.Join(", ", args)}) -> Dictionary:");
            text.AppendLine("\t\treturn {");
            text.AppendLine($"\t\t\t\"kind\": \"{variant.Name}\",");
            foreach (var field in action.Fields)
            {
                text.AppendLine($"\t\t\t\"{field.Name}\": {field.Name},");
            }
            text.AppendLine("\t\t}");
        }
        return text.ToString();
    }

    private static string RenderGdPacket(ProtoSchema schema)
    {
        var text = new StringBuilder();
        text.AppendLine("class Packet:");
        text.AppendLine("\textends RefCounted");
        if (schema.Enums.TryGetValue("PacketType", out var protoEnum))
        {
            foreach (var value in protoEnum.Values.Where(item => item.Number != 0))
            {
                var name = value.Name.StartsWith("PACKET_TYPE_", StringComparison.Ordinal)
                    ? value.Name["PACKET_TYPE_".Length..].ToLowerInvariant()
                    : EnumTail(value.Name);
                text.AppendLine($"\tconst {GdConstName(name)} := \"{name}\"");
            }
        }
        return text.ToString();
    }

    private static string RenderGdEvent(ProtoSchema schema)
    {
        var text = new StringBuilder();
        text.AppendLine("class Event:");
        text.AppendLine("\textends RefCounted");
        if (!schema.Messages.TryGetValue("GameEvent", out var eventRoot))
        {
            return text.ToString();
        }

        foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
        {
            if (!schema.Messages.TryGetValue(variant.Type, out var message))
            {
                continue;
            }
            text.AppendLine();
            text.Append(Indent(RenderGdWrapper(
                ClassNameForEvent(variant.Type),
                message.Fields,
                eventMode: true,
                schema: null,
                groupName: "Event",
                classNameForType: ClassNameForEvent), "\t"));
            text.AppendLine();
        }

        text.AppendLine();
        text.AppendLine("\tclass Bus:");
        text.AppendLine("\t\textends RefCounted");
        text.AppendLine();
        text.AppendLine("\t\tvar _callbacks: Dictionary = {}");
        text.AppendLine();
        text.AppendLine("\t\tfunc clear() -> void:");
        text.AppendLine("\t\t\t_callbacks.clear()");
        foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
        {
            var eventKey = ClassNameForEvent(variant.Type);
            text.AppendLine();
            text.AppendLine($"\t\tfunc on_{variant.Name}(cb: Callable) -> void:");
            text.AppendLine($"\t\t\tvar callbacks: Array = _callbacks.get(\"{eventKey}\", [])");
            text.AppendLine("\t\t\tcallbacks.append(cb)");
            text.AppendLine($"\t\t\t_callbacks[\"{eventKey}\"] = callbacks");
        }
        text.AppendLine();
        text.AppendLine("\t\tfunc dispatch(events: Array) -> void:");
        text.AppendLine("\t\t\tfor ev in events:");
        text.AppendLine("\t\t\t\tdispatch_one(ev)");
        text.AppendLine();
        text.AppendLine("\t\tfunc dispatch_one(raw: Dictionary) -> void:");
        text.AppendLine("\t\t\tvar ev_type: String = str(raw.get(\"type\", \"\"))");
        text.AppendLine("\t\t\tvar callbacks: Array = _callbacks.get(ev_type, [])");
        text.AppendLine("\t\t\tif callbacks.is_empty():");
        text.AppendLine("\t\t\t\treturn");
        text.AppendLine("\t\t\tmatch ev_type:");
        foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
        {
            var eventKey = ClassNameForEvent(variant.Type);
            text.AppendLine($"\t\t\t\t\"{eventKey}\":");
            text.AppendLine($"\t\t\t\t\tvar ev = {eventKey}.wrap(raw)");
            text.AppendLine("\t\t\t\t\tfor cb in callbacks:");
            text.AppendLine("\t\t\t\t\t\tif cb.is_valid():");
            text.AppendLine("\t\t\t\t\t\t\tcb.call(ev)");
        }
        text.AppendLine("\t\t\t\t_:");
        text.AppendLine("\t\t\t\t\tpass");
        return text.ToString();
    }

    private static string RenderGdView(ProtoSchema schema)
    {
        var text = new StringBuilder();
        text.AppendLine("class View:");
        text.AppendLine("\textends RefCounted");
        var messages = schema.Messages.Values
            .Where(item => Path.GetFileName(item.SourcePath) == "view.proto")
            .Where(item => item.Fields.All(field => !field.IsOneof))
            .OrderBy(item => item.Name, StringComparer.Ordinal)
            .ToArray();
        foreach (var message in messages)
        {
            text.AppendLine();
            text.Append(Indent(RenderGdWrapper(
                ClassNameForView(message.Name),
                message.Fields,
                eventMode: false,
                schema,
                groupName: "View",
                classNameForType: ClassNameForView), "\t"));
            text.AppendLine();
        }
        return text.ToString();
    }

    private static string RenderGdWrapper(
        string className,
        IReadOnlyList<ProtoField> fields,
        bool eventMode,
        ProtoSchema? schema,
        string groupName,
        Func<string, string> classNameForType
    )
    {
        var block = new StringBuilder();
        block.AppendLine($"class {className}:");
        block.AppendLine("\textends RefCounted");
        block.AppendLine();
        block.AppendLine("\tvar _raw: Dictionary = {}");
        block.AppendLine();
        block.AppendLine($"\tstatic func wrap(raw: Dictionary) -> {className}:");
        block.AppendLine($"\t\tvar obj: {className} = {className}.new()");
        block.AppendLine("\t\tobj._raw = raw");
        block.AppendLine("\t\treturn obj");
        block.AppendLine();
        block.AppendLine("\tfunc raw() -> Dictionary:");
        block.AppendLine("\t\treturn _raw");

        foreach (var field in fields)
        {
            block.AppendLine();
            block.AppendLine($"\tfunc {field.Name}() -> {GdReturnType(field, eventMode)}:");
            block.AppendLine($"\t\treturn {GdGetter(field, eventMode)}");

            if (field.IsRepeated && schema != null && !IsIntLike(field.Type) && schema.Messages.ContainsKey(field.Type))
            {
                var nestedClass = classNameForType(field.Type);
                block.AppendLine();
                block.AppendLine($"\tfunc {field.Name}_wrapped() -> Array:");
                block.AppendLine("\t\tvar out: Array = []");
                block.AppendLine($"\t\tfor item in {field.Name}():");
                block.AppendLine($"\t\t\tout.append({nestedClass}.wrap(item))");
                block.AppendLine("\t\treturn out");
            }
        }

        return block.ToString().TrimEnd();
    }

    private static string Indent(string text, string prefix)
    {
        return string.Join("\n", text.Split('\n').Select(line => line.Length == 0 ? line : prefix + line));
    }

    private static void GenerateTypesCs(string root, FwConfig config, string schemaDir)
    {
        var output = config.BridgeTypesCsPath(root);
        IEnumerable<string> files = Directory.Exists(schemaDir)
            ? Directory.GetFiles(schemaDir, "*.proto").OrderBy(item => item, StringComparer.Ordinal)
            : Array.Empty<string>();
        var schema = ProtoSchema.ParseFiles(files);
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen bridge. Do not edit.");
        text.AppendLine("using System.Collections.Generic;");
        text.AppendLine("using Godot;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Core;");
        text.AppendLine();
        RenderBridgeFields(text, schema);
        text.AppendLine();
        RenderBridgeEnums(text, schema);
        text.AppendLine();
        RenderPacketTypes(text, schema);
        text.AppendLine();
        RenderPlayerActionCs(text, schema);
        text.AppendLine();
        RenderPlayerIntentCs(text);
        text.AppendLine();
        RenderCoreEventCs(text, schema);
        TextUtil.WriteText(output, text.ToString());
        Console.WriteLine($"generated bridge csharp types: {output}");
    }

    private static void GenerateCodecCs(string root, FwConfig config)
    {
        var output = config.BridgeCodecCsPath(root);
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen bridge. Do not edit.");
        text.AppendLine("using Godot;");
        text.AppendLine($"using {rootNamespace}.Core;");
        text.AppendLine("using GdArray = Godot.Collections.Array;");
        text.AppendLine("using GdDictionary = Godot.Collections.Dictionary;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Bridge;");
        text.AppendLine();
        text.AppendLine("public static class BridgeCodec");
        text.AppendLine("{");
        text.AppendLine("    public const int ProtocolVersion = 1;");
        text.AppendLine();
        text.AppendLine("    public static GdDictionary Packet(string type)");
        text.AppendLine("    {");
        text.AppendLine("        var packet = new GdDictionary();");
        text.AppendLine("        packet[BridgeField.Type] = type;");
        text.AppendLine("        packet[BridgeField.ProtocolVersion] = ProtocolVersion;");
        text.AppendLine("        packet[BridgeField.SessionToken] = \"\";");
        text.AppendLine("        return packet;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static string ReadType(GdDictionary packet)");
        text.AppendLine("    {");
        text.AppendLine("        return ReadString(packet, BridgeField.Type);");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static int ReadProtocolVersion(GdDictionary packet)");
        text.AppendLine("    {");
        text.AppendLine("        return (int)ReadLong(packet, BridgeField.ProtocolVersion, 0);");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static bool IsProtocolSupported(GdDictionary packet)");
        text.AppendLine("    {");
        text.AppendLine("        return ReadProtocolVersion(packet) == ProtocolVersion;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static string ReadSessionToken(GdDictionary packet)");
        text.AppendLine("    {");
        text.AppendLine("        return ReadString(packet, BridgeField.SessionToken);");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static void SetSessionToken(GdDictionary packet, string sessionToken)");
        text.AppendLine("    {");
        text.AppendLine("        packet[BridgeField.SessionToken] = sessionToken;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static string ReadString(GdDictionary packet, string field)");
        text.AppendLine("    {");
        text.AppendLine("        return packet.TryGetValue(field, out Variant value) ? value.AsString() : \"\";");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static string ReadString(GdDictionary packet, string field, string fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return packet.TryGetValue(field, out Variant value) ? value.AsString() : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static long ReadLong(GdDictionary packet, string field, long fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return packet.TryGetValue(field, out Variant value) ? value.AsInt64() : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static bool ReadBool(GdDictionary packet, string field, bool fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return packet.TryGetValue(field, out Variant value) ? value.AsBool() : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static float ReadFloat(GdDictionary packet, string field, float fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return packet.TryGetValue(field, out Variant value) ? (float)value.AsDouble() : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static Vector2I ReadVector2I(GdDictionary packet, string field, Vector2I fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return packet.TryGetValue(field, out Variant value) ? value.AsVector2I() : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static bool TryGetDictionary(GdDictionary packet, string field, out GdDictionary value)");
        text.AppendLine("    {");
        text.AppendLine("        value = new GdDictionary();");
        text.AppendLine("        if (!packet.TryGetValue(field, out Variant variant) || variant.VariantType != Variant.Type.Dictionary)");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        value = variant.AsGodotDictionary();");
        text.AppendLine("        return true;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static bool TryGetArray(GdDictionary packet, string field, out GdArray value)");
        text.AppendLine("    {");
        text.AppendLine("        value = new GdArray();");
        text.AppendLine("        if (!packet.TryGetValue(field, out Variant variant) || variant.VariantType != Variant.Type.Array)");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        value = variant.AsGodotArray();");
        text.AppendLine("        return true;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static byte[] ToBytes(GdDictionary packet)");
        text.AppendLine("    {");
        text.AppendLine("        return GD.VarToBytes(packet);");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static GdDictionary? FromBytes(byte[] bytes)");
        text.AppendLine("    {");
        text.AppendLine("        Variant value = GD.BytesToVar(bytes);");
        text.AppendLine("        return value.VariantType == Variant.Type.Dictionary ? value.AsGodotDictionary() : null;");
        text.AppendLine("    }");
        text.AppendLine("}");
        TextUtil.WriteText(output, text.ToString());
        Console.WriteLine($"generated bridge csharp codec: {output}");
    }

    private static void GenerateIntentCodecCs(string root, FwConfig config, string schemaDir)
    {
        var output = config.BridgeIntentCodecCsPath(root);
        var files = new[]
        {
            Path.Combine(schemaDir, "value.proto"),
            Path.Combine(schemaDir, "intent.proto"),
        };
        var schema = ProtoSchema.ParseFiles(files);
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen bridge. Do not edit.");
        text.AppendLine("using System.Collections.Generic;");
        text.AppendLine("using Godot;");
        text.AppendLine($"using {rootNamespace}.Core;");
        text.AppendLine("using GdArray = Godot.Collections.Array;");
        text.AppendLine("using GdDictionary = Godot.Collections.Dictionary;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Bridge;");
        text.AppendLine();
        text.AppendLine("public static class IntentCodec");
        text.AppendLine("{");
        text.AppendLine("    public static List<PlayerIntent> Decode(GdArray intents)");
        text.AppendLine("    {");
        text.AppendLine("        var intentsOut = new List<PlayerIntent>();");
        text.AppendLine("        foreach (Variant intent in intents)");
        text.AppendLine("        {");
        text.AppendLine("            if (intent.VariantType != Variant.Type.Dictionary)");
        text.AppendLine("            {");
        text.AppendLine("                continue;");
        text.AppendLine("            }");
        text.AppendLine();
        text.AppendLine("            GdDictionary dict = intent.AsGodotDictionary();");
        text.AppendLine("            intentsOut.Add(DecodeOne(BridgeCodec.ReadLong(dict, BridgeField.PlayerId, -1), dict));");
        text.AppendLine("        }");
        text.AppendLine("        return intentsOut;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static PlayerIntent DecodeOne(long playerId, GdDictionary dict)");
        text.AppendLine("    {");
        text.AppendLine("        return new PlayerIntent(");
        text.AppendLine("            playerId,");
        text.AppendLine("            (uint)BridgeCodec.ReadLong(dict, BridgeField.ClientTick, 0),");
        text.AppendLine("            BridgeCodec.ReadVector2I(dict, BridgeField.MoveDir, Vector2I.Zero),");
        text.AppendLine("            BridgeCodec.ReadVector2I(dict, BridgeField.AimDir, Vector2I.Zero),");
        text.AppendLine("            (int)BridgeCodec.ReadLong(dict, BridgeField.ButtonsHold, 0),");
        text.AppendLine("            (int)BridgeCodec.ReadLong(dict, BridgeField.ButtonsDown, 0),");
        text.AppendLine("            (int)BridgeCodec.ReadLong(dict, BridgeField.ButtonsUp, 0),");
        text.AppendLine("            DecodeAction(dict)");
        text.AppendLine("        );");
        text.AppendLine("    }");
        text.AppendLine();
        RenderInputActionDecoder(text, schema);
        text.AppendLine("}");
        TextUtil.WriteText(output, text.ToString());
        DeleteLegacyFile(Path.Combine(Path.GetDirectoryName(output) ?? root, "_input_codec.cs"));
        Console.WriteLine($"generated bridge intent codec: {output}");
    }

    private static void RenderInputActionDecoder(StringBuilder text, ProtoSchema schema)
    {
        text.AppendLine("    private static PlayerAction? DecodeAction(GdDictionary dictionary)");
        text.AppendLine("    {");
        text.AppendLine("        if (!BridgeCodec.TryGetDictionary(dictionary, BridgeField.Action, out GdDictionary action))");
        text.AppendLine("        {");
        text.AppendLine("            return null;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        string kind = BridgeCodec.ReadString(action, BridgeField.Kind);");
        text.AppendLine("        if (string.IsNullOrEmpty(kind))");
        text.AppendLine("        {");
        text.AppendLine("            return null;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        return new PlayerAction");
        text.AppendLine("        {");
        text.AppendLine("            Kind = kind,");
        foreach (var field in ActionFields(schema))
        {
            text.AppendLine($"            {Pascal(field.Name)} = {ReadExpression("action", field)},");
        }
        text.AppendLine("        };");
        text.AppendLine("    }");
    }

    private static ProtoField[] ActionFields(ProtoSchema schema)
    {
        if (!schema.Messages.TryGetValue("PlayerAction", out var actionRoot))
        {
            return [];
        }
        return actionRoot.Fields
            .Where(item => item.IsOneof)
            .SelectMany(variant => schema.Messages.TryGetValue(variant.Type, out var message) ? message.Fields : [])
            .GroupBy(field => field.Name, StringComparer.Ordinal)
            .Select(group => group.First())
            .OrderBy(field => field.Name, StringComparer.Ordinal)
            .ToArray();
    }

    private static string ReadExpression(string source, ProtoField field)
    {
        var bridgeField = $"BridgeField.{Pascal(field.Name)}";
        if (field.IsRepeated)
        {
            return $"BridgeCodec.TryGetArray({source}, {bridgeField}, out GdArray {field.Name}Array) ? {field.Name}Array : new GdArray()";
        }
        return field.Type switch
        {
            "string" => $"BridgeCodec.ReadString({source}, {bridgeField})",
            "bool" => $"BridgeCodec.ReadBool({source}, {bridgeField}, false)",
            "float" or "double" => $"BridgeCodec.ReadFloat({source}, {bridgeField}, 0.0f)",
            "Vec2i" => $"BridgeCodec.ReadVector2I({source}, {bridgeField}, Vector2I.Zero)",
            "EntityKind" or "ItemKind" or "WeaponSlot" or "WeaponPhase" => $"BridgeCodec.ReadString({source}, {bridgeField}, {BridgeEnumDefault(field.Type)})",
            _ when IsIntLike(field.Type) => $"(int)BridgeCodec.ReadLong({source}, {bridgeField}, {ReadFallback(field)})",
            _ => $"BridgeCodec.ReadString({source}, {bridgeField})",
        };
    }

    private static string ReadFallback(ProtoField field)
    {
        return field.Name == "count" ? "1" : "0";
    }

    private static void GenerateEventCodecCs(string root, FwConfig config, string schemaDir)
    {
        var output = config.BridgeEventCodecCsPath(root);
        var files = new[]
        {
            Path.Combine(schemaDir, "value.proto"),
            Path.Combine(schemaDir, "event.proto"),
        };
        var schema = ProtoSchema.ParseFiles(files);
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen bridge. Do not edit.");
        text.AppendLine("using System.Collections.Generic;");
        text.AppendLine("using Godot;");
        text.AppendLine($"using {rootNamespace}.Core;");
        text.AppendLine("using GdArray = Godot.Collections.Array;");
        text.AppendLine("using GdDictionary = Godot.Collections.Dictionary;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Bridge;");
        text.AppendLine();
        text.AppendLine("public static class EventCodec");
        text.AppendLine("{");
        text.AppendLine("    public static GdArray Encode(IReadOnlyList<CoreEvent> events)");
        text.AppendLine("    {");
        text.AppendLine("        var output = new GdArray();");
        text.AppendLine("        foreach (CoreEvent ev in events)");
        text.AppendLine("        {");
        text.AppendLine("            output.Add(EncodeOne(ev));");
        text.AppendLine("        }");
        text.AppendLine("        return output;");
        text.AppendLine("    }");
        text.AppendLine();
        RenderEventEncoder(text, schema);
        text.AppendLine("}");
        TextUtil.WriteText(output, text.ToString());
        Console.WriteLine($"generated bridge event codec: {output}");
    }

    private static void GeneratePacketCodecCs(string root, FwConfig config, string schemaDir)
    {
        var output = config.BridgePacketCodecCsPath(root);
        var schema = ProtoSchema.ParseFiles(SchemaFiles(schemaDir));
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen bridge. Do not edit.");
        text.AppendLine("using Godot;");
        text.AppendLine($"using {rootNamespace}.Core;");
        text.AppendLine("using GdArray = Godot.Collections.Array;");
        text.AppendLine("using GdDictionary = Godot.Collections.Dictionary;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Bridge;");
        text.AppendLine();
        text.AppendLine("public static class PacketCodec");
        text.AppendLine("{");

        foreach (var payload in PacketPayloadFields(schema))
        {
            RenderPacketCreator(text, schema, payload);
            text.AppendLine();
        }

        foreach (var payload in PacketPayloadFields(schema))
        {
            RenderPacketReader(text, schema, payload);
            text.AppendLine();
        }

        text.AppendLine("    private static GdDictionary Payload(string field, Variant value)");
        text.AppendLine("    {");
        text.AppendLine("        var payload = new GdDictionary();");
        text.AppendLine("        payload[field] = value;");
        text.AppendLine("        return payload;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool TryPayload(GdDictionary packet, string type, string field, out GdDictionary payload)");
        text.AppendLine("    {");
        text.AppendLine("        payload = new GdDictionary();");
        text.AppendLine("        if (!BridgeCodec.IsProtocolSupported(packet) || BridgeCodec.ReadType(packet) != type)");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine("        return BridgeCodec.TryGetDictionary(packet, field, out payload);");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool TryReadString(GdDictionary packet, string field, out string value)");
        text.AppendLine("    {");
        text.AppendLine("        value = \"\";");
        text.AppendLine("        if (!packet.TryGetValue(field, out Variant variant))");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine("        value = variant.AsString();");
        text.AppendLine("        return true;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool TryReadBool(GdDictionary packet, string field, out bool value)");
        text.AppendLine("    {");
        text.AppendLine("        value = false;");
        text.AppendLine("        if (!packet.TryGetValue(field, out Variant variant))");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine("        value = variant.AsBool();");
        text.AppendLine("        return true;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool TryReadFloat(GdDictionary packet, string field, out float value)");
        text.AppendLine("    {");
        text.AppendLine("        value = 0.0f;");
        text.AppendLine("        if (!packet.TryGetValue(field, out Variant variant))");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine("        value = (float)variant.AsDouble();");
        text.AppendLine("        return true;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool TryReadVector2I(GdDictionary packet, string field, out Vector2I value)");
        text.AppendLine("    {");
        text.AppendLine("        value = Vector2I.Zero;");
        text.AppendLine("        if (!packet.TryGetValue(field, out Variant variant) || variant.VariantType != Variant.Type.Vector2I)");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine("        value = variant.AsVector2I();");
        text.AppendLine("        return true;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool TryReadLong(GdDictionary packet, string field, out long value)");
        text.AppendLine("    {");
        text.AppendLine("        value = 0;");
        text.AppendLine("        if (!packet.TryGetValue(field, out Variant variant))");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine("        value = variant.AsInt64();");
        text.AppendLine("        return true;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool TryReadInt(GdDictionary packet, string field, out int value)");
        text.AppendLine("    {");
        text.AppendLine("        value = 0;");
        text.AppendLine("        if (!packet.TryGetValue(field, out Variant variant))");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine("        value = (int)variant.AsInt64();");
        text.AppendLine("        return true;");
        text.AppendLine("    }");
        text.AppendLine("}");
        TextUtil.WriteText(output, text.ToString());
        Console.WriteLine($"generated bridge packet codec: {output}");
    }

    private static ProtoField[] PacketPayloadFields(ProtoSchema schema)
    {
        if (!schema.Messages.TryGetValue("Packet", out var packet))
        {
            return [];
        }
        return packet.Fields
            .Where(field => field.IsOneof)
            .ToArray();
    }

    private static void RenderPacketCreator(StringBuilder text, ProtoSchema schema, ProtoField payload)
    {
        var methodName = Pascal(payload.Name);
        var packetType = $"BridgePacketType.{methodName}";
        var payloadField = $"BridgeField.{methodName}";
        var payloadMessage = schema.Messages.TryGetValue(payload.Type, out var message)
            ? message
            : new ProtoMessage(payload.Type, "");
        var args = payloadMessage.Fields
            .Select(field => $"{PacketRuntimeType(field)} {Camel(field.Name)}")
            .ToArray();

        text.AppendLine($"    public static GdDictionary {methodName}({string.Join(", ", args)})");
        text.AppendLine("    {");
        text.AppendLine($"        var packet = BridgeCodec.Packet({packetType});");
        if (payloadMessage.Fields.Count == 0)
        {
            text.AppendLine($"        packet[{payloadField}] = new GdDictionary();");
        }
        else if (payloadMessage.Fields.Count == 1)
        {
            var field = payloadMessage.Fields[0];
            text.AppendLine($"        packet[{payloadField}] = Payload(BridgeField.{Pascal(field.Name)}, {Camel(field.Name)});");
        }
        else
        {
            text.AppendLine("        var payload = new GdDictionary();");
            foreach (var field in payloadMessage.Fields)
            {
                text.AppendLine($"        payload[BridgeField.{Pascal(field.Name)}] = {Camel(field.Name)};");
            }
            text.AppendLine($"        packet[{payloadField}] = payload;");
        }
        text.AppendLine("        return packet;");
        text.AppendLine("    }");
    }

    private static void RenderPacketReader(StringBuilder text, ProtoSchema schema, ProtoField payload)
    {
        var methodName = Pascal(payload.Name);
        var packetType = $"BridgePacketType.{methodName}";
        var payloadField = $"BridgeField.{methodName}";
        var payloadMessage = schema.Messages.TryGetValue(payload.Type, out var message)
            ? message
            : new ProtoMessage(payload.Type, "");

        if (payloadMessage.Fields.Count == 0)
        {
            text.AppendLine($"    public static bool TryRead{methodName}(GdDictionary packet)");
            text.AppendLine("    {");
            text.AppendLine($"        return TryPayload(packet, {packetType}, {payloadField}, out _);");
            text.AppendLine("    }");
            return;
        }

        var args = payloadMessage.Fields
            .Select(field => $"out {PacketRuntimeType(field)} {Camel(field.Name)}")
            .ToArray();
        text.AppendLine($"    public static bool TryRead{methodName}(GdDictionary packet, {string.Join(", ", args)})");
        text.AppendLine("    {");
        foreach (var field in payloadMessage.Fields)
        {
            text.AppendLine($"        {Camel(field.Name)} = {PacketDefaultValue(field)};");
        }
        text.AppendLine($"        if (!TryPayload(packet, {packetType}, {payloadField}, out GdDictionary payload))");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");

        if (payloadMessage.Fields.Count == 1)
        {
            var field = payloadMessage.Fields[0];
            text.AppendLine($"        return {PacketReadExpression(field)};");
        }
        else
        {
            text.AppendLine("        var ok = true;");
            foreach (var field in payloadMessage.Fields)
            {
                text.AppendLine($"        ok &= {PacketReadExpression(field)};");
            }
            text.AppendLine("        return ok;");
        }
        text.AppendLine("    }");
    }

    private static string PacketRuntimeType(ProtoField field)
    {
        if (field.IsRepeated)
        {
            return "GdArray";
        }
        return field.Type switch
        {
            "string" => "string",
            "bool" => "bool",
            "float" or "double" => "float",
            "Vec2i" => "Vector2I",
            "PlayerId" => "long",
            "EntityId" => "int",
            "EntityKind" or "ItemKind" or "WeaponSlot" or "WeaponPhase" => "string",
            _ when IsIntLike(field.Type) => "int",
            _ => "GdDictionary",
        };
    }

    private static string PacketDefaultValue(ProtoField field)
    {
        if (field.IsRepeated)
        {
            return "new GdArray()";
        }
        return field.Type switch
        {
            "string" => "\"\"",
            "bool" => "false",
            "float" or "double" => "0.0f",
            "Vec2i" => "Vector2I.Zero",
            "PlayerId" => "0",
            "EntityId" => "0",
            "EntityKind" or "ItemKind" or "WeaponSlot" or "WeaponPhase" => BridgeEnumDefault(field.Type),
            _ when IsIntLike(field.Type) => "0",
            _ => "new GdDictionary()",
        };
    }

    private static string PacketReadExpression(ProtoField field)
    {
        var variable = Camel(field.Name);
        var bridgeField = $"BridgeField.{Pascal(field.Name)}";
        if (field.IsRepeated)
        {
            return $"BridgeCodec.TryGetArray(payload, {bridgeField}, out {variable})";
        }
        return field.Type switch
        {
            "string" => $"TryReadString(payload, {bridgeField}, out {variable})",
            "bool" => $"TryReadBool(payload, {bridgeField}, out {variable})",
            "float" or "double" => $"TryReadFloat(payload, {bridgeField}, out {variable})",
            "Vec2i" => $"TryReadVector2I(payload, {bridgeField}, out {variable})",
            "PlayerId" => $"TryReadLong(payload, {bridgeField}, out {variable})",
            "EntityId" => $"TryReadInt(payload, {bridgeField}, out {variable})",
            "EntityKind" or "ItemKind" or "WeaponSlot" or "WeaponPhase" => $"TryReadString(payload, {bridgeField}, out {variable})",
            _ when IsIntLike(field.Type) => $"TryReadInt(payload, {bridgeField}, out {variable})",
            _ => $"BridgeCodec.TryGetDictionary(payload, {bridgeField}, out {variable})",
        };
    }

    private static void RenderEventEncoder(StringBuilder text, ProtoSchema schema)
    {
        text.AppendLine("    private static GdDictionary EncodeOne(CoreEvent ev)");
        text.AppendLine("    {");
        text.AppendLine("        var data = new GdDictionary();");
        text.AppendLine("        data[BridgeField.Type] = ev.Type;");
        text.AppendLine("        switch (ev.Type)");
        text.AppendLine("        {");
        if (schema.Messages.TryGetValue("GameEvent", out var eventRoot))
        {
            foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
            {
                if (!schema.Messages.TryGetValue(variant.Type, out var message))
                {
                    continue;
                }
                text.AppendLine($"            case CoreEvent.{ClassNameForEvent(variant.Type)}:");
                foreach (var field in message.Fields)
                {
                    text.AppendLine($"                data[BridgeField.{Pascal(field.Name)}] = ev.{Pascal(field.Name)};");
                }
                text.AppendLine("                break;");
            }
        }
        text.AppendLine("        }");
        text.AppendLine("        return data;");
        text.AppendLine("    }");
    }

    private static void RenderBridgeFields(StringBuilder text, ProtoSchema schema)
    {
        var fields = schema.Messages.Values
            .SelectMany(message => message.Fields)
            .Select(field => field.Name)
            .Append("kind")
            .Append("type")
            .Distinct(StringComparer.Ordinal)
            .OrderBy(item => item, StringComparer.Ordinal)
            .ToArray();

        text.AppendLine("public static class BridgeField");
        text.AppendLine("{");
        foreach (var field in fields)
        {
            text.AppendLine($"    public const string {Pascal(field)} = \"{field}\";");
        }
        text.AppendLine("}");
    }

    private static void RenderBridgeEnums(StringBuilder text, ProtoSchema schema)
    {
        RenderStringEnum(text, schema, "EntityKind", "BridgeEntityKind");
        text.AppendLine();
        RenderStringEnum(text, schema, "ItemKind", "BridgeItemKind");
        text.AppendLine();
        RenderStringEnum(text, schema, "WeaponSlot", "BridgeWeaponSlot");
        text.AppendLine();
        RenderStringEnum(text, schema, "WeaponPhase", "BridgeWeaponPhase");
        text.AppendLine();
        RenderButtonEnum(text, schema);
    }

    private static void RenderPacketTypes(StringBuilder text, ProtoSchema schema)
    {
        text.AppendLine("public static class BridgePacketType");
        text.AppendLine("{");
        if (schema.Enums.TryGetValue("PacketType", out var protoEnum))
        {
            foreach (var value in protoEnum.Values.Where(item => item.Number != 0))
            {
                var name = value.Name.StartsWith("PACKET_TYPE_", StringComparison.Ordinal)
                    ? value.Name["PACKET_TYPE_".Length..].ToLowerInvariant()
                    : EnumTail(value.Name);
                text.AppendLine($"    public const string {Pascal(name)} = \"{name}\";");
            }
        }
        text.AppendLine("}");
    }

    private static void RenderStringEnum(StringBuilder text, ProtoSchema schema, string enumName, string className)
    {
        text.AppendLine($"public static class {className}");
        text.AppendLine("{");
        if (schema.Enums.TryGetValue(enumName, out var protoEnum))
        {
            foreach (var value in protoEnum.Values.Where(item => item.Number != 0))
            {
                var name = EnumTail(value.Name);
                text.AppendLine($"    public const string {Pascal(name)} = \"{Pascal(name)}\";");
            }
        }
        text.AppendLine("}");
    }

    private static void RenderButtonEnum(StringBuilder text, ProtoSchema schema)
    {
        text.AppendLine("public static class BridgeButton");
        text.AppendLine("{");
        if (schema.Enums.TryGetValue("PlayerButton", out var protoEnum))
        {
            foreach (var value in protoEnum.Values.Where(item => item.Number != 0))
            {
                text.AppendLine($"    public const int {Pascal(EnumTail(value.Name))} = {value.Number};");
            }
        }
        text.AppendLine("}");
    }

    private static void RenderPlayerActionCs(StringBuilder text, ProtoSchema schema)
    {
        text.AppendLine("public sealed class PlayerAction");
        text.AppendLine("{");
        if (schema.Messages.TryGetValue("PlayerAction", out var actionRoot))
        {
            foreach (var variant in actionRoot.Fields.Where(item => item.IsOneof))
            {
                text.AppendLine($"    public const string {Pascal(variant.Name)} = \"{variant.Name}\";");
            }

            var fields = actionRoot.Fields
                .Where(item => item.IsOneof)
                .SelectMany(variant => schema.Messages.TryGetValue(variant.Type, out var message) ? message.Fields : [])
                .GroupBy(field => field.Name, StringComparer.Ordinal)
                .Select(group => group.First())
                .OrderBy(field => field.Name, StringComparer.Ordinal)
                .ToArray();

            text.AppendLine();
            text.AppendLine("    public string Kind { get; init; } = \"\";");
            foreach (var field in fields)
            {
                var init = CsDefaultInit(field);
                text.AppendLine($"    public {CsCoreType(field.Type, field.IsRepeated)} {Pascal(field.Name)} {{ get; init; }}{init}");
            }
        }
        else
        {
            text.AppendLine("    public string Kind { get; init; } = \"\";");
        }
        text.AppendLine("}");
    }

    private static void RenderPlayerIntentCs(StringBuilder text)
    {
        text.AppendLine("public readonly struct PlayerIntent");
        text.AppendLine("{");
        text.AppendLine("    public const int BtnPrimary = BridgeButton.Primary;");
        text.AppendLine("    public const int BtnSecondary = BridgeButton.Secondary;");
        text.AppendLine("    public const int BtnSprint = BridgeButton.Sprint;");
        text.AppendLine("    public const int BtnInteract = BridgeButton.Interact;");
        text.AppendLine();
        text.AppendLine("    public PlayerIntent(");
        text.AppendLine("        long playerId,");
        text.AppendLine("        uint clientTick,");
        text.AppendLine("        Vector2I moveDir,");
        text.AppendLine("        Vector2I aimDir,");
        text.AppendLine("        int hold,");
        text.AppendLine("        int down,");
        text.AppendLine("        int up,");
        text.AppendLine("        PlayerAction? action");
        text.AppendLine("    )");
        text.AppendLine("    {");
        text.AppendLine("        PlayerId = playerId;");
        text.AppendLine("        ClientTick = clientTick;");
        text.AppendLine("        MoveDir = moveDir;");
        text.AppendLine("        AimDir = aimDir;");
        text.AppendLine("        Hold = hold;");
        text.AppendLine("        Down = down;");
        text.AppendLine("        Up = up;");
        text.AppendLine("        Action = action;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public long PlayerId { get; }");
        text.AppendLine("    public uint ClientTick { get; }");
        text.AppendLine("    public Vector2I MoveDir { get; }");
        text.AppendLine("    public Vector2I AimDir { get; }");
        text.AppendLine("    public int Hold { get; }");
        text.AppendLine("    public int Down { get; }");
        text.AppendLine("    public int Up { get; }");
        text.AppendLine("    public PlayerAction? Action { get; }");
        text.AppendLine();
        text.AppendLine("    public bool IsHold(int mask) => (Hold & mask) != 0;");
        text.AppendLine("    public bool IsDown(int mask) => (Down & mask) != 0;");
        text.AppendLine("    public bool IsUp(int mask) => (Up & mask) != 0;");
        text.AppendLine("}");
    }

    private static void RenderCoreEventCs(StringBuilder text, ProtoSchema schema)
    {
        text.AppendLine("public sealed class CoreEvent");
        text.AppendLine("{");
        if (schema.Messages.TryGetValue("GameEvent", out var eventRoot))
        {
            foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
            {
                text.AppendLine($"    public const string {ClassNameForEvent(variant.Type)} = \"{ClassNameForEvent(variant.Type)}\";");
            }

            var fields = eventRoot.Fields
                .Where(item => item.IsOneof)
                .SelectMany(variant => schema.Messages.TryGetValue(variant.Type, out var message) ? message.Fields : [])
                .GroupBy(field => field.Name, StringComparer.Ordinal)
                .Select(group => group.First())
                .OrderBy(field => field.Name, StringComparer.Ordinal)
                .ToArray();

            text.AppendLine();
            text.AppendLine("    public string Type { get; init; } = \"\";");
            foreach (var field in fields)
            {
                var init = CsDefaultInit(field);
                text.AppendLine($"    public {CsCoreType(field.Type, field.IsRepeated)} {Pascal(field.Name)} {{ get; init; }}{init}");
            }
        }
        else
        {
            text.AppendLine("    public string Type { get; init; } = \"\";");
        }
        text.AppendLine("}");
    }

    private static string ClassNameForEvent(string messageType)
    {
        return messageType.EndsWith("Event", StringComparison.Ordinal)
            ? messageType[..^"Event".Length]
            : messageType;
    }

    private static string ClassNameForView(string messageType)
    {
        return messageType.EndsWith("View", StringComparison.Ordinal)
            ? messageType[..^"View".Length]
            : messageType;
    }

    private static string EnumTail(string value)
    {
        var parts = value.Split('_', StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length <= 2)
        {
            return value.ToLowerInvariant();
        }
        return string.Join("_", parts.Skip(2)).ToLowerInvariant();
    }

    private static string Pascal(string value)
    {
        var text = new StringBuilder();
        foreach (var part in value.Split('_', StringSplitOptions.RemoveEmptyEntries))
        {
            text.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
            {
                text.Append(part[1..].ToLowerInvariant());
            }
        }
        return text.Length == 0 ? "Value" : text.ToString();
    }

    private static string Camel(string value)
    {
        var pascal = Pascal(value);
        return pascal.Length == 0
            ? "value"
            : char.ToLowerInvariant(pascal[0]) + pascal[1..];
    }

    private static string GdConstName(string value)
    {
        return string.Join("_", value.Split('_', StringSplitOptions.RemoveEmptyEntries))
            .ToUpperInvariant();
    }

    private static string CsCoreType(string type, bool repeated)
    {
        var itemType = type switch
        {
            "string" => "string",
            "bool" => "bool",
            "float" or "double" => "float",
            "Vec2i" => "Vector2I",
            "PlayerId" => "long",
            "EntityId" => "int",
            "PlayerAction" => "PlayerAction?",
            "EntityKind" or "ItemKind" or "WeaponSlot" or "WeaponPhase" => "string",
            _ when IsIntLike(type) => "int",
            _ => Pascal(type),
        };
        return repeated ? $"List<{itemType}>" : itemType;
    }

    private static string CsDefaultInit(ProtoField field)
    {
        if (field.IsRepeated)
        {
            return " = new();";
        }
        if (field.Type == "string")
        {
            return " = \"\";";
        }
        if (field.Type == "PlayerAction")
        {
            return "";
        }
        return field.Type switch
        {
            "EntityKind" => field.Name == "victim_kind"
                ? " = BridgeEntityKind.Dummy;"
                : $" = BridgeEntityKind.{Pascal(EnumDefault("EntityKind"))};",
            "ItemKind" => $" = BridgeItemKind.{Pascal(EnumDefault("ItemKind"))};",
            "WeaponSlot" => $" = BridgeWeaponSlot.{Pascal(EnumDefault("WeaponSlot"))};",
            "WeaponPhase" => $" = BridgeWeaponPhase.{Pascal(EnumDefault("WeaponPhase"))};",
            _ when field.Name == "count" => " = 1;",
            _ => "",
        };
    }

    private static string GdArgType(ProtoField field)
    {
        if (field.IsRepeated) return "Array";
        return field.Type switch
        {
            "string" => "String",
            "bool" => "bool",
            "float" or "double" => "float",
            "Vec2i" => "Vector2i",
            "EntityKind" or "ItemKind" or "WeaponSlot" or "WeaponPhase" => "String",
            _ when IsIntLike(field.Type) => "int",
            _ => "Variant"
        };
    }

    private static string GdReturnType(ProtoField field, bool eventMode)
    {
        if (field.IsRepeated) return "Array";
        return field.Type switch
        {
            "string" => "String",
            "bool" => "bool",
            "float" or "double" => "float",
            "Vec2i" => "Vector2i",
            _ when IsIntLike(field.Type) => "int",
            "EntityKind" or "ItemKind" or "WeaponSlot" or "WeaponPhase" => "String",
            _ => eventMode ? "Variant" : "String"
        };
    }

    private static string GdGetter(ProtoField field, bool eventMode)
    {
        if (field.IsRepeated)
        {
            return $"_raw.get(\"{field.Name}\", [])";
        }

        return field.Type switch
        {
            "string" => $"str(_raw.get(\"{field.Name}\", \"\"))",
            "bool" => $"bool(_raw.get(\"{field.Name}\", false))",
            "float" or "double" => $"float(_raw.get(\"{field.Name}\", 0.0))",
            "Vec2i" => $"_raw.get(\"{field.Name}\", Vector2i.ZERO)",
            _ when IsIntLike(field.Type) => $"int(_raw.get(\"{field.Name}\", 0))",
            "EntityKind" or "ItemKind" or "WeaponSlot" or "WeaponPhase" => $"str(_raw.get(\"{field.Name}\", \"{EnumDefault(field.Type)}\"))",
            _ => eventMode ? $"_raw.get(\"{field.Name}\", null)" : $"str(_raw.get(\"{field.Name}\", \"{EnumDefault(field.Type)}\"))"
        };
    }

    private static string EnumDefault(string type)
    {
        return type switch
        {
            "EntityKind" => "Player",
            "ItemKind" => "Torch",
            "WeaponSlot" => "Sword",
            "WeaponPhase" => "Idle",
            _ => ""
        };
    }

    private static string BridgeEnumDefault(string type)
    {
        var className = type switch
        {
            "EntityKind" => "BridgeEntityKind",
            "ItemKind" => "BridgeItemKind",
            "WeaponSlot" => "BridgeWeaponSlot",
            "WeaponPhase" => "BridgeWeaponPhase",
            _ => ""
        };
        return string.IsNullOrEmpty(className)
            ? "\"\""
            : $"{className}.{Pascal(EnumDefault(type))}";
    }

    private static bool IsIntLike(string type)
    {
        return type is "int32" or "int64" or "uint32" or "uint64" or "sint32" or "sint64"
            || type.EndsWith("Id", StringComparison.Ordinal);
    }

    private static void DeleteLegacyFile(string path)
    {
        if (File.Exists(path))
        {
            File.Delete(path);
        }
    }
}
