using System.Text;
using static BridgeSchema;

static class BridgeGd
{
    internal static void Write(string gdDir, ProtoSchema schema)
    {
        var text = new StringBuilder();
        text.AppendLine("# This file is generated by fwgen. Do not edit manually.");
        text.AppendLine("extends RefCounted");
        text.AppendLine("class_name Bridge");
        text.AppendLine();
        text.Append(RenderGdValue(schema));
        text.AppendLine();
        text.Append(RenderGdIntent(schema));
        text.AppendLine();
        text.Append(RenderGdEvent(schema));
        text.AppendLine();
        text.Append(RenderGdView(schema));
        text.AppendLine();
        text.Append(RenderGdPacket(schema));

        TextUtil.WriteText(Path.Combine(gdDir, "_bridge.gd"), text.ToString());
        DeleteLegacyGd(gdDir);
    }

    private static void DeleteLegacyGd(string gdDir)
    {
        foreach (var name in new[]
        {
            "_action.gd",
            "_action.gd.uid",
            "_input.gd",
            "_input.gd.uid",
            "_event.gd",
            "_event.gd.uid",
            "_snapshot.gd",
            "_snapshot.gd.uid",
            "_view.gd",
            "_view.gd.uid",
        })
        {
            var path = Path.Combine(gdDir, name);
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }
    }

    private static string RenderGdValue(ProtoSchema schema)
    {
        var text = new StringBuilder();
        text.AppendLine("class Value:");
        text.AppendLine("\textends RefCounted");
        foreach (var protoEnum in EnumsInFile(schema, "value.proto"))
        {
            RenderGdStringEnum(text, protoEnum);
        }
        return text.ToString();
    }

    private static void RenderGdStringEnum(StringBuilder text, ProtoEnum protoEnum)
    {
        text.AppendLine();
        text.AppendLine($"\tclass {protoEnum.Name}:");
        text.AppendLine("\t\textends RefCounted");
        foreach (var value in protoEnum.Values.Where(item => item.Number != 0))
        {
            var name = EnumTail(value.Name);
            text.AppendLine($"\t\tconst {GdConstName(name)} := \"{Pascal(name)}\"");
        }
    }

    private static string RenderGdIntent(ProtoSchema schema)
    {
        var text = new StringBuilder();
        text.AppendLine("class Intent:");
        text.AppendLine("\textends RefCounted");
        var buttons = FindButtonEnum(schema);
        if (buttons != null)
        {
            foreach (var value in buttons.Values.Where(item => item.Number != 0))
            {
                text.AppendLine($"\tconst BTN_{EnumTail(value.Name).ToUpperInvariant()} := {value.Number}");
            }
        }
        var actionRoot = FindActionRoot(schema);
        if (actionRoot == null)
        {
            return text.ToString();
        }

        foreach (var variant in actionRoot.Fields.Where(item => item.IsOneof))
        {
            if (!schema.Messages.TryGetValue(variant.Type, out var action))
            {
                continue;
            }

            text.AppendLine();
            var args = action.Fields.Select(item => $"{item.Name}: {GdArgType(schema, item)}");
            text.AppendLine($"\tstatic func {variant.Name}({string.Join(", ", args)}) -> Dictionary:");
            text.AppendLine("\t\treturn {");
            text.AppendLine($"\t\t\t\"kind\": \"{variant.Name}\",");
            foreach (var field in action.Fields)
            {
                text.AppendLine($"\t\t\t\"{field.Name}\": {field.Name},");
            }
            text.AppendLine("\t\t}");
        }
        return text.ToString();
    }

    private static string RenderGdPacket(ProtoSchema schema)
    {
        var text = new StringBuilder();
        text.AppendLine("class Packet:");
        text.AppendLine("\textends RefCounted");
        var protoEnum = FindPacketEnum(schema);
        if (protoEnum != null)
        {
            foreach (var value in protoEnum.Values.Where(item => item.Number != 0))
            {
                var name = PacketValueName(value.Name);
                text.AppendLine($"\tconst {GdConstName(name)} := \"{name}\"");
            }
        }
        return text.ToString();
    }

    private static string RenderGdEvent(ProtoSchema schema)
    {
        var text = new StringBuilder();
        text.AppendLine("class Event:");
        text.AppendLine("\textends RefCounted");
        var eventRoot = FindOneofRoot(schema, "event.proto");
        if (eventRoot == null)
        {
            return text.ToString();
        }

        foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
        {
            if (!schema.Messages.TryGetValue(variant.Type, out var message))
            {
                continue;
            }
            text.AppendLine();
            text.Append(Indent(RenderGdWrapper(
                ClassNameForEvent(variant.Type),
                message.Fields,
                eventMode: true,
                schema,
                groupName: "Event",
                classNameForType: ClassNameForEvent), "\t"));
            text.AppendLine();
        }

        text.AppendLine();
        text.AppendLine("\tclass Bus:");
        text.AppendLine("\t\textends RefCounted");
        text.AppendLine();
        text.AppendLine("\t\tvar _callbacks: Dictionary = {}");
        text.AppendLine();
        text.AppendLine("\t\tfunc clear() -> void:");
        text.AppendLine("\t\t\t_callbacks.clear()");
        foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
        {
            var eventKey = ClassNameForEvent(variant.Type);
            text.AppendLine();
            text.AppendLine($"\t\tfunc on_{variant.Name}(cb: Callable) -> void:");
            text.AppendLine($"\t\t\tvar callbacks: Array = _callbacks.get(\"{eventKey}\", [])");
            text.AppendLine("\t\t\tcallbacks.append(cb)");
            text.AppendLine($"\t\t\t_callbacks[\"{eventKey}\"] = callbacks");
        }
        text.AppendLine();
        text.AppendLine("\t\tfunc dispatch(events: Array) -> void:");
        text.AppendLine("\t\t\tfor ev in events:");
        text.AppendLine("\t\t\t\tdispatch_one(ev)");
        text.AppendLine();
        text.AppendLine("\t\tfunc dispatch_one(raw: Dictionary) -> void:");
        text.AppendLine("\t\t\tvar ev_type: String = str(raw.get(\"type\", \"\"))");
        text.AppendLine("\t\t\tvar callbacks: Array = _callbacks.get(ev_type, [])");
        text.AppendLine("\t\t\tif callbacks.is_empty():");
        text.AppendLine("\t\t\t\treturn");
        text.AppendLine("\t\t\tmatch ev_type:");
        foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
        {
            var eventKey = ClassNameForEvent(variant.Type);
            text.AppendLine($"\t\t\t\t\"{eventKey}\":");
            text.AppendLine($"\t\t\t\t\tvar ev = {eventKey}.wrap(raw)");
            text.AppendLine("\t\t\t\t\tfor cb in callbacks:");
            text.AppendLine("\t\t\t\t\t\tif cb.is_valid():");
            text.AppendLine("\t\t\t\t\t\t\tcb.call(ev)");
        }
        text.AppendLine("\t\t\t\t_:");
        text.AppendLine("\t\t\t\t\tpass");
        return text.ToString();
    }

    private static string RenderGdView(ProtoSchema schema)
    {
        var text = new StringBuilder();
        text.AppendLine("class View:");
        text.AppendLine("\textends RefCounted");
        var messages = schema.Messages.Values
            .Where(item => Path.GetFileName(item.SourcePath) == "view.proto")
            .Where(item => item.Fields.All(field => !field.IsOneof))
            .OrderBy(item => item.Name, StringComparer.Ordinal)
            .ToArray();
        foreach (var message in messages)
        {
            text.AppendLine();
            text.Append(Indent(RenderGdWrapper(
                ClassNameForView(message.Name),
                message.Fields,
                eventMode: false,
                schema,
                groupName: "View",
                classNameForType: ClassNameForView), "\t"));
            text.AppendLine();
        }
        return text.ToString();
    }

    private static string RenderGdWrapper(
        string className,
        IReadOnlyList<ProtoField> fields,
        bool eventMode,
        ProtoSchema? schema,
        string groupName,
        Func<string, string> classNameForType
    )
    {
        var block = new StringBuilder();
        block.AppendLine($"class {className}:");
        block.AppendLine("\textends RefCounted");
        block.AppendLine();
        block.AppendLine("\tvar _raw: Dictionary = {}");
        block.AppendLine();
        block.AppendLine($"\tstatic func wrap(raw: Dictionary) -> {className}:");
        block.AppendLine($"\t\tvar obj: {className} = {className}.new()");
        block.AppendLine("\t\tobj._raw = raw");
        block.AppendLine("\t\treturn obj");
        block.AppendLine();
        block.AppendLine("\tfunc raw() -> Dictionary:");
        block.AppendLine("\t\treturn _raw");

        foreach (var field in fields)
        {
            block.AppendLine();
            block.AppendLine($"\tfunc {field.Name}() -> {GdReturnType(schema, field, eventMode)}:");
            block.AppendLine($"\t\treturn {GdGetter(schema, field, eventMode)}");

            if (field.IsRepeated && schema != null && !IsIntLike(field.Type) && schema.Messages.ContainsKey(field.Type))
            {
                var nestedClass = classNameForType(field.Type);
                block.AppendLine();
                block.AppendLine($"\tfunc {field.Name}_wrapped() -> Array:");
                block.AppendLine("\t\tvar out: Array = []");
                block.AppendLine($"\t\tfor item in {field.Name}():");
                block.AppendLine($"\t\t\tout.append({nestedClass}.wrap(item))");
                block.AppendLine("\t\treturn out");
            }
        }

        return block.ToString().TrimEnd();
    }

    private static string Indent(string text, string prefix)
    {
        return string.Join("\n", text.Split('\n').Select(line => line.Length == 0 ? line : prefix + line));
    }
}
