using System.Text;

static class BridgeGen
{
    public static void Generate(string root, FwConfig config)
    {
        var schemaDir = config.BridgeSchemaDir(root);
        var gdDir = config.GodotGenDir(root);
        Directory.CreateDirectory(gdDir);

        var commonPath = Path.Combine(schemaDir, "common.proto");
        GenerateInput(schemaDir, gdDir);
        GenerateAction(schemaDir, gdDir);
        GenerateEvent(schemaDir, gdDir, commonPath);
        GenerateSnapshot(schemaDir, gdDir, commonPath);
        GenerateContractCs(root, config, schemaDir);
        GenerateCodecCs(root, config);
        GenerateInputCodecCs(root, config, schemaDir);
        GenerateEventCodecCs(root, config, schemaDir);
        Console.WriteLine($"generated bridge gd scripts: {gdDir}");
    }

    private static void GenerateInput(string schemaDir, string gdDir)
    {
        var inputPath = Path.Combine(schemaDir, "input.proto");
        if (!File.Exists(inputPath))
        {
            return;
        }

        var schema = ProtoSchema.ParseFiles([inputPath]);
        if (!schema.Enums.TryGetValue("PlayerButton", out var buttons))
        {
            return;
        }

        var text = new StringBuilder();
        text.AppendLine("# This file is generated by fw_gen. Do not edit manually.");
        text.AppendLine("extends RefCounted");
        text.AppendLine("class_name _input");
        text.AppendLine();
        foreach (var value in buttons.Values.Where(item => item.Number != 0))
        {
            text.AppendLine($"const BTN_{EnumTail(value.Name).ToUpperInvariant()} := {value.Number}");
        }

        TextUtil.WriteText(Path.Combine(gdDir, "_input.gd"), text.ToString());
    }

    private static void GenerateAction(string schemaDir, string gdDir)
    {
        var schema = ProtoSchema.ParseFiles([Path.Combine(schemaDir, "action.proto")]);
        if (!schema.Messages.TryGetValue("PlayerAction", out var actionRoot))
        {
            return;
        }

        var blocks = new List<string>();
        foreach (var variant in actionRoot.Fields.Where(item => item.IsOneof))
        {
            if (!schema.Messages.TryGetValue(variant.Type, out var action))
            {
                continue;
            }

            var args = action.Fields.Select(item => $"{item.Name}: {GdArgType(item)}");
            var lines = new List<string>
            {
                $"static func {variant.Name}({string.Join(", ", args)}) -> Dictionary:",
                "\treturn {",
                $"\t\t\"kind\": \"{variant.Name}\","
            };
            lines.AddRange(action.Fields.Select(item => $"\t\t\"{item.Name}\": {item.Name},"));
            lines.Add("\t}");
            blocks.Add(string.Join("\n", lines));
        }

        TextUtil.WriteText(Path.Combine(gdDir, "_action.gd"),
            "# This file is generated by fw_gen. Do not edit manually.\n" +
            "extends RefCounted\n" +
            "class_name _action\n\n" +
            string.Join("\n\n", blocks) +
            "\n");
    }

    private static void GenerateEvent(string schemaDir, string gdDir, string commonPath)
    {
        var files = File.Exists(commonPath)
            ? new[] { commonPath, Path.Combine(schemaDir, "event.proto") }
            : new[] { Path.Combine(schemaDir, "event.proto") };
        var schema = ProtoSchema.ParseFiles(files);
        if (!schema.Messages.TryGetValue("GameEvent", out var eventRoot))
        {
            return;
        }

        var classes = new List<string>();
        foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
        {
            if (!schema.Messages.TryGetValue(variant.Type, out var message))
            {
                continue;
            }
            classes.Add(RenderWrapper(ClassNameForEvent(variant.Type), message.Fields, eventMode: true));
        }

        var bus = new StringBuilder();
        bus.AppendLine("class Bus:");
        bus.AppendLine("\textends RefCounted");
        bus.AppendLine();
        bus.AppendLine("\tvar _callbacks: Dictionary = {}");
        bus.AppendLine();
        bus.AppendLine("\tfunc clear() -> void:");
        bus.AppendLine("\t\t_callbacks.clear()");
        bus.AppendLine();
        foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
        {
            var eventKey = ClassNameForEvent(variant.Type);
            bus.AppendLine($"\tfunc on_{variant.Name}(cb: Callable) -> void:");
            bus.AppendLine($"\t\t_callbacks[\"{eventKey}\"] = cb");
            bus.AppendLine();
        }
        bus.AppendLine("\tfunc dispatch(events: Array) -> void:");
        bus.AppendLine("\t\tfor ev in events:");
        bus.AppendLine("\t\t\tdispatch_one(ev)");
        bus.AppendLine();
        bus.AppendLine("\tfunc dispatch_one(raw: Dictionary) -> void:");
        bus.AppendLine("\t\tvar ev_type: String = str(raw.get(\"type\", \"\"))");
        bus.AppendLine("\t\tvar cb: Callable = _callbacks.get(ev_type, Callable())");
        bus.AppendLine("\t\tif not cb.is_valid():");
        bus.AppendLine("\t\t\treturn");
        bus.AppendLine("\t\tmatch ev_type:");
        foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
        {
            var eventKey = ClassNameForEvent(variant.Type);
            bus.AppendLine($"\t\t\t\"{eventKey}\":");
            bus.AppendLine($"\t\t\t\tcb.call({ClassNameForEvent(variant.Type)}.wrap(raw))");
        }
        bus.AppendLine("\t\t\t_:");
        bus.AppendLine("\t\t\t\tpass");

        TextUtil.WriteText(Path.Combine(gdDir, "_event.gd"),
            "# This file is generated by fw_gen. Do not edit manually.\n" +
            "extends RefCounted\n" +
            "class_name _event\n\n" +
            string.Join("\n\n", classes) +
            "\n\n" +
            bus);
    }

    private static void GenerateSnapshot(string schemaDir, string gdDir, string commonPath)
    {
        var snapshotPath = Path.Combine(schemaDir, "snapshot.proto");
        var files = File.Exists(commonPath)
            ? new[] { commonPath, snapshotPath }
            : new[] { snapshotPath };
        var schema = ProtoSchema.ParseFiles(files);
        var snapshotMessages = schema.Messages.Values
            .Where(item => Path.GetFullPath(item.SourcePath) == Path.GetFullPath(snapshotPath))
            .Where(item => item.Fields.All(field => !field.IsOneof))
            .OrderBy(item => item.Name, StringComparer.Ordinal)
            .ToArray();

        var blocks = snapshotMessages
            .Select(message => RenderWrapper($"Wrapped{message.Name}", message.Fields, eventMode: false, schema))
            .ToArray();

        TextUtil.WriteText(Path.Combine(gdDir, "_snapshot.gd"),
            "# This file is generated by fw_gen. Do not edit manually.\n" +
            "extends RefCounted\n" +
            "class_name _snapshot\n\n" +
            string.Join("\n\n", blocks) +
            "\n");
    }

    private static void GenerateContractCs(string root, FwConfig config, string schemaDir)
    {
        var output = config.BridgeContractCsPath(root);
        IEnumerable<string> files = Directory.Exists(schemaDir)
            ? Directory.GetFiles(schemaDir, "*.proto").OrderBy(item => item, StringComparer.Ordinal)
            : Array.Empty<string>();
        var schema = ProtoSchema.ParseFiles(files);
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        var text = new StringBuilder();
        text.AppendLine("// @generated by fw_gen bridge. Do not edit.");
        text.AppendLine("using System.Collections.Generic;");
        text.AppendLine("using Godot;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Core;");
        text.AppendLine();
        RenderBridgeFields(text, schema);
        text.AppendLine();
        RenderBridgeEnums(text, schema);
        text.AppendLine();
        RenderPacketTypes(text, schema);
        text.AppendLine();
        RenderPlayerActionCs(text, schema);
        text.AppendLine();
        RenderPlayerCommandCs(text);
        text.AppendLine();
        RenderCoreEventCs(text, schema);
        TextUtil.WriteText(output, text.ToString());
        Console.WriteLine($"generated bridge csharp contract: {output}");
    }

    private static void GenerateCodecCs(string root, FwConfig config)
    {
        var output = config.BridgeCodecCsPath(root);
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        var text = new StringBuilder();
        text.AppendLine("// @generated by fw_gen bridge. Do not edit.");
        text.AppendLine("using Godot;");
        text.AppendLine($"using {rootNamespace}.Core;");
        text.AppendLine("using GdArray = Godot.Collections.Array;");
        text.AppendLine("using GdDictionary = Godot.Collections.Dictionary;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Bridge;");
        text.AppendLine();
        text.AppendLine("public static class BridgeCodec");
        text.AppendLine("{");
        text.AppendLine("    public static GdDictionary Packet(string type)");
        text.AppendLine("    {");
        text.AppendLine("        var packet = new GdDictionary();");
        text.AppendLine("        packet[BridgeField.Type] = type;");
        text.AppendLine("        return packet;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static string ReadType(GdDictionary packet)");
        text.AppendLine("    {");
        text.AppendLine("        return ReadString(packet, BridgeField.Type);");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static string ReadString(GdDictionary packet, string field)");
        text.AppendLine("    {");
        text.AppendLine("        return packet.TryGetValue(field, out Variant value) ? value.AsString() : \"\";");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static long ReadLong(GdDictionary packet, string field, long fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return packet.TryGetValue(field, out Variant value) ? value.AsInt64() : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static bool ReadBool(GdDictionary packet, string field, bool fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return packet.TryGetValue(field, out Variant value) ? value.AsBool() : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static float ReadFloat(GdDictionary packet, string field, float fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return packet.TryGetValue(field, out Variant value) ? (float)value.AsDouble() : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static Vector2I ReadVector2I(GdDictionary packet, string field, Vector2I fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return packet.TryGetValue(field, out Variant value) ? value.AsVector2I() : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static bool TryGetDictionary(GdDictionary packet, string field, out GdDictionary value)");
        text.AppendLine("    {");
        text.AppendLine("        value = new GdDictionary();");
        text.AppendLine("        if (!packet.TryGetValue(field, out Variant variant) || variant.VariantType != Variant.Type.Dictionary)");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        value = variant.AsGodotDictionary();");
        text.AppendLine("        return true;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static bool TryGetArray(GdDictionary packet, string field, out GdArray value)");
        text.AppendLine("    {");
        text.AppendLine("        value = new GdArray();");
        text.AppendLine("        if (!packet.TryGetValue(field, out Variant variant) || variant.VariantType != Variant.Type.Array)");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        value = variant.AsGodotArray();");
        text.AppendLine("        return true;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static byte[] ToBytes(GdDictionary packet)");
        text.AppendLine("    {");
        text.AppendLine("        return GD.VarToBytes(packet);");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static GdDictionary? FromBytes(byte[] bytes)");
        text.AppendLine("    {");
        text.AppendLine("        Variant value = GD.BytesToVar(bytes);");
        text.AppendLine("        return value.VariantType == Variant.Type.Dictionary ? value.AsGodotDictionary() : null;");
        text.AppendLine("    }");
        text.AppendLine("}");
        TextUtil.WriteText(output, text.ToString());
        Console.WriteLine($"generated bridge csharp codec: {output}");
    }

    private static void GenerateInputCodecCs(string root, FwConfig config, string schemaDir)
    {
        var output = config.BridgeInputCodecCsPath(root);
        var files = new[]
        {
            Path.Combine(schemaDir, "common.proto"),
            Path.Combine(schemaDir, "action.proto"),
            Path.Combine(schemaDir, "input.proto"),
        };
        var schema = ProtoSchema.ParseFiles(files);
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        var text = new StringBuilder();
        text.AppendLine("// @generated by fw_gen bridge. Do not edit.");
        text.AppendLine("using System.Collections.Generic;");
        text.AppendLine("using Godot;");
        text.AppendLine($"using {rootNamespace}.Core;");
        text.AppendLine("using GdArray = Godot.Collections.Array;");
        text.AppendLine("using GdDictionary = Godot.Collections.Dictionary;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Bridge;");
        text.AppendLine();
        text.AppendLine("public static class InputCodec");
        text.AppendLine("{");
        text.AppendLine("    public static List<PlayerCommand> Decode(GdArray inputs)");
        text.AppendLine("    {");
        text.AppendLine("        var cmds = new List<PlayerCommand>();");
        text.AppendLine("        foreach (Variant input in inputs)");
        text.AppendLine("        {");
        text.AppendLine("            if (input.VariantType != Variant.Type.Dictionary)");
        text.AppendLine("            {");
        text.AppendLine("                continue;");
        text.AppendLine("            }");
        text.AppendLine();
        text.AppendLine("            GdDictionary dict = input.AsGodotDictionary();");
        text.AppendLine("            cmds.Add(DecodeOne(BridgeCodec.ReadLong(dict, BridgeField.PlayerId, -1), dict));");
        text.AppendLine("        }");
        text.AppendLine("        return cmds;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static PlayerCommand DecodeOne(long playerId, GdDictionary dict)");
        text.AppendLine("    {");
        text.AppendLine("        return new PlayerCommand(");
        text.AppendLine("            playerId,");
        text.AppendLine("            (uint)BridgeCodec.ReadLong(dict, BridgeField.ClientTick, 0),");
        text.AppendLine("            BridgeCodec.ReadVector2I(dict, BridgeField.MoveDir, Vector2I.Zero),");
        text.AppendLine("            BridgeCodec.ReadVector2I(dict, BridgeField.AimDir, Vector2I.Zero),");
        text.AppendLine("            (int)BridgeCodec.ReadLong(dict, BridgeField.ButtonsHold, 0),");
        text.AppendLine("            (int)BridgeCodec.ReadLong(dict, BridgeField.ButtonsDown, 0),");
        text.AppendLine("            (int)BridgeCodec.ReadLong(dict, BridgeField.ButtonsUp, 0),");
        text.AppendLine("            DecodeAction(dict)");
        text.AppendLine("        );");
        text.AppendLine("    }");
        text.AppendLine();
        RenderInputActionDecoder(text, schema);
        text.AppendLine("}");
        TextUtil.WriteText(output, text.ToString());
        Console.WriteLine($"generated bridge input codec: {output}");
    }

    private static void RenderInputActionDecoder(StringBuilder text, ProtoSchema schema)
    {
        text.AppendLine("    private static PlayerAction? DecodeAction(GdDictionary dictionary)");
        text.AppendLine("    {");
        text.AppendLine("        if (!BridgeCodec.TryGetDictionary(dictionary, BridgeField.Action, out GdDictionary action))");
        text.AppendLine("        {");
        text.AppendLine("            return null;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        string kind = BridgeCodec.ReadString(action, BridgeField.Kind);");
        text.AppendLine("        if (string.IsNullOrEmpty(kind))");
        text.AppendLine("        {");
        text.AppendLine("            return null;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        return new PlayerAction");
        text.AppendLine("        {");
        text.AppendLine("            Kind = kind,");
        foreach (var field in ActionFields(schema))
        {
            text.AppendLine($"            {Pascal(field.Name)} = {ReadExpression("action", field)},");
        }
        text.AppendLine("        };");
        text.AppendLine("    }");
    }

    private static ProtoField[] ActionFields(ProtoSchema schema)
    {
        if (!schema.Messages.TryGetValue("PlayerAction", out var actionRoot))
        {
            return [];
        }
        return actionRoot.Fields
            .Where(item => item.IsOneof)
            .SelectMany(variant => schema.Messages.TryGetValue(variant.Type, out var message) ? message.Fields : [])
            .GroupBy(field => field.Name, StringComparer.Ordinal)
            .Select(group => group.First())
            .OrderBy(field => field.Name, StringComparer.Ordinal)
            .ToArray();
    }

    private static string ReadExpression(string source, ProtoField field)
    {
        var bridgeField = $"BridgeField.{Pascal(field.Name)}";
        if (field.IsRepeated)
        {
            return $"BridgeCodec.TryGetArray({source}, {bridgeField}, out GdArray {field.Name}Array) ? {field.Name}Array : new GdArray()";
        }
        return field.Type switch
        {
            "string" => $"BridgeCodec.ReadString({source}, {bridgeField})",
            "bool" => $"BridgeCodec.ReadBool({source}, {bridgeField}, false)",
            "float" or "double" => $"BridgeCodec.ReadFloat({source}, {bridgeField}, 0.0f)",
            "Vec2i" => $"BridgeCodec.ReadVector2I({source}, {bridgeField}, Vector2I.Zero)",
            "EntityKind" or "ItemKind" or "WeaponSlot" or "WeaponPhase" => $"BridgeCodec.ReadString({source}, {bridgeField})",
            _ when IsIntLike(field.Type) => $"(int)BridgeCodec.ReadLong({source}, {bridgeField}, {ReadFallback(field)})",
            _ => $"BridgeCodec.ReadString({source}, {bridgeField})",
        };
    }

    private static string ReadFallback(ProtoField field)
    {
        return field.Name == "count" ? "1" : "0";
    }

    private static void GenerateEventCodecCs(string root, FwConfig config, string schemaDir)
    {
        var output = config.BridgeEventCodecCsPath(root);
        var files = new[]
        {
            Path.Combine(schemaDir, "common.proto"),
            Path.Combine(schemaDir, "event.proto"),
        };
        var schema = ProtoSchema.ParseFiles(files);
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        var text = new StringBuilder();
        text.AppendLine("// @generated by fw_gen bridge. Do not edit.");
        text.AppendLine("using System.Collections.Generic;");
        text.AppendLine("using Godot;");
        text.AppendLine($"using {rootNamespace}.Core;");
        text.AppendLine("using GdArray = Godot.Collections.Array;");
        text.AppendLine("using GdDictionary = Godot.Collections.Dictionary;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Bridge;");
        text.AppendLine();
        text.AppendLine("public static class EventCodec");
        text.AppendLine("{");
        text.AppendLine("    public static GdArray Encode(IReadOnlyList<CoreEvent> events)");
        text.AppendLine("    {");
        text.AppendLine("        var output = new GdArray();");
        text.AppendLine("        foreach (CoreEvent ev in events)");
        text.AppendLine("        {");
        text.AppendLine("            output.Add(EncodeOne(ev));");
        text.AppendLine("        }");
        text.AppendLine("        return output;");
        text.AppendLine("    }");
        text.AppendLine();
        RenderEventEncoder(text, schema);
        text.AppendLine("}");
        TextUtil.WriteText(output, text.ToString());
        Console.WriteLine($"generated bridge event codec: {output}");
    }

    private static void RenderEventEncoder(StringBuilder text, ProtoSchema schema)
    {
        text.AppendLine("    private static GdDictionary EncodeOne(CoreEvent ev)");
        text.AppendLine("    {");
        text.AppendLine("        var data = new GdDictionary();");
        text.AppendLine("        data[BridgeField.Type] = ev.Type;");
        text.AppendLine("        switch (ev.Type)");
        text.AppendLine("        {");
        if (schema.Messages.TryGetValue("GameEvent", out var eventRoot))
        {
            foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
            {
                if (!schema.Messages.TryGetValue(variant.Type, out var message))
                {
                    continue;
                }
                text.AppendLine($"            case CoreEvent.{ClassNameForEvent(variant.Type)}:");
                foreach (var field in message.Fields)
                {
                    text.AppendLine($"                data[BridgeField.{Pascal(field.Name)}] = ev.{Pascal(field.Name)};");
                }
                text.AppendLine("                break;");
            }
        }
        text.AppendLine("        }");
        text.AppendLine("        return data;");
        text.AppendLine("    }");
    }

    private static void RenderBridgeFields(StringBuilder text, ProtoSchema schema)
    {
        var fields = schema.Messages.Values
            .SelectMany(message => message.Fields)
            .Select(field => field.Name)
            .Append("kind")
            .Append("type")
            .Distinct(StringComparer.Ordinal)
            .OrderBy(item => item, StringComparer.Ordinal)
            .ToArray();

        text.AppendLine("public static class BridgeField");
        text.AppendLine("{");
        foreach (var field in fields)
        {
            text.AppendLine($"    public const string {Pascal(field)} = \"{field}\";");
        }
        text.AppendLine("}");
    }

    private static void RenderBridgeEnums(StringBuilder text, ProtoSchema schema)
    {
        RenderStringEnum(text, schema, "EntityKind", "BridgeEntityKind");
        text.AppendLine();
        RenderStringEnum(text, schema, "ItemKind", "BridgeItemKind");
        text.AppendLine();
        RenderStringEnum(text, schema, "WeaponSlot", "BridgeWeaponSlot");
        text.AppendLine();
        RenderStringEnum(text, schema, "WeaponPhase", "BridgeWeaponPhase");
        text.AppendLine();
        RenderButtonEnum(text, schema);
    }

    private static void RenderPacketTypes(StringBuilder text, ProtoSchema schema)
    {
        text.AppendLine("public static class BridgePacketType");
        text.AppendLine("{");
        if (schema.Enums.TryGetValue("NetPacketType", out var protoEnum))
        {
            foreach (var value in protoEnum.Values.Where(item => item.Number != 0))
            {
                var name = value.Name.StartsWith("NET_PACKET_TYPE_", StringComparison.Ordinal)
                    ? value.Name["NET_PACKET_TYPE_".Length..].ToLowerInvariant()
                    : EnumTail(value.Name);
                text.AppendLine($"    public const string {Pascal(name)} = \"{name}\";");
            }
        }
        text.AppendLine("}");
    }

    private static void RenderStringEnum(StringBuilder text, ProtoSchema schema, string enumName, string className)
    {
        text.AppendLine($"public static class {className}");
        text.AppendLine("{");
        if (schema.Enums.TryGetValue(enumName, out var protoEnum))
        {
            foreach (var value in protoEnum.Values.Where(item => item.Number != 0))
            {
                var name = EnumTail(value.Name);
                text.AppendLine($"    public const string {Pascal(name)} = \"{Pascal(name)}\";");
            }
        }
        text.AppendLine("}");
    }

    private static void RenderButtonEnum(StringBuilder text, ProtoSchema schema)
    {
        text.AppendLine("public static class BridgeButton");
        text.AppendLine("{");
        if (schema.Enums.TryGetValue("PlayerButton", out var protoEnum))
        {
            foreach (var value in protoEnum.Values.Where(item => item.Number != 0))
            {
                text.AppendLine($"    public const int {Pascal(EnumTail(value.Name))} = {value.Number};");
            }
        }
        text.AppendLine("}");
    }

    private static void RenderPlayerActionCs(StringBuilder text, ProtoSchema schema)
    {
        text.AppendLine("public sealed class PlayerAction");
        text.AppendLine("{");
        if (schema.Messages.TryGetValue("PlayerAction", out var actionRoot))
        {
            foreach (var variant in actionRoot.Fields.Where(item => item.IsOneof))
            {
                text.AppendLine($"    public const string {Pascal(variant.Name)} = \"{variant.Name}\";");
            }

            var fields = actionRoot.Fields
                .Where(item => item.IsOneof)
                .SelectMany(variant => schema.Messages.TryGetValue(variant.Type, out var message) ? message.Fields : [])
                .GroupBy(field => field.Name, StringComparer.Ordinal)
                .Select(group => group.First())
                .OrderBy(field => field.Name, StringComparer.Ordinal)
                .ToArray();

            text.AppendLine();
            text.AppendLine("    public string Kind { get; init; } = \"\";");
            foreach (var field in fields)
            {
                var init = CsDefaultInit(field);
                text.AppendLine($"    public {CsCoreType(field.Type, field.IsRepeated)} {Pascal(field.Name)} {{ get; init; }}{init}");
            }
        }
        else
        {
            text.AppendLine("    public string Kind { get; init; } = \"\";");
        }
        text.AppendLine("}");
    }

    private static void RenderPlayerCommandCs(StringBuilder text)
    {
        text.AppendLine("public readonly struct PlayerCommand");
        text.AppendLine("{");
        text.AppendLine("    public const int BtnPrimary = BridgeButton.Primary;");
        text.AppendLine("    public const int BtnSecondary = BridgeButton.Secondary;");
        text.AppendLine("    public const int BtnSprint = BridgeButton.Sprint;");
        text.AppendLine("    public const int BtnInteract = BridgeButton.Interact;");
        text.AppendLine();
        text.AppendLine("    public PlayerCommand(");
        text.AppendLine("        long playerId,");
        text.AppendLine("        uint clientTick,");
        text.AppendLine("        Vector2I moveDir,");
        text.AppendLine("        Vector2I aimDir,");
        text.AppendLine("        int hold,");
        text.AppendLine("        int down,");
        text.AppendLine("        int up,");
        text.AppendLine("        PlayerAction? action");
        text.AppendLine("    )");
        text.AppendLine("    {");
        text.AppendLine("        PlayerId = playerId;");
        text.AppendLine("        ClientTick = clientTick;");
        text.AppendLine("        MoveDir = moveDir;");
        text.AppendLine("        AimDir = aimDir;");
        text.AppendLine("        Hold = hold;");
        text.AppendLine("        Down = down;");
        text.AppendLine("        Up = up;");
        text.AppendLine("        Action = action;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public long PlayerId { get; }");
        text.AppendLine("    public uint ClientTick { get; }");
        text.AppendLine("    public Vector2I MoveDir { get; }");
        text.AppendLine("    public Vector2I AimDir { get; }");
        text.AppendLine("    public int Hold { get; }");
        text.AppendLine("    public int Down { get; }");
        text.AppendLine("    public int Up { get; }");
        text.AppendLine("    public PlayerAction? Action { get; }");
        text.AppendLine();
        text.AppendLine("    public bool IsHold(int mask) => (Hold & mask) != 0;");
        text.AppendLine("    public bool IsDown(int mask) => (Down & mask) != 0;");
        text.AppendLine("    public bool IsUp(int mask) => (Up & mask) != 0;");
        text.AppendLine("}");
    }

    private static void RenderCoreEventCs(StringBuilder text, ProtoSchema schema)
    {
        text.AppendLine("public sealed class CoreEvent");
        text.AppendLine("{");
        if (schema.Messages.TryGetValue("GameEvent", out var eventRoot))
        {
            foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
            {
                text.AppendLine($"    public const string {ClassNameForEvent(variant.Type)} = \"{ClassNameForEvent(variant.Type)}\";");
            }

            var fields = eventRoot.Fields
                .Where(item => item.IsOneof)
                .SelectMany(variant => schema.Messages.TryGetValue(variant.Type, out var message) ? message.Fields : [])
                .GroupBy(field => field.Name, StringComparer.Ordinal)
                .Select(group => group.First())
                .OrderBy(field => field.Name, StringComparer.Ordinal)
                .ToArray();

            text.AppendLine();
            text.AppendLine("    public string Type { get; init; } = \"\";");
            foreach (var field in fields)
            {
                var init = CsDefaultInit(field);
                text.AppendLine($"    public {CsCoreType(field.Type, field.IsRepeated)} {Pascal(field.Name)} {{ get; init; }}{init}");
            }
        }
        else
        {
            text.AppendLine("    public string Type { get; init; } = \"\";");
        }
        text.AppendLine("}");
    }

    private static string RenderWrapper(string className, IReadOnlyList<ProtoField> fields, bool eventMode, ProtoSchema? schema = null)
    {
        var block = new StringBuilder();
        block.AppendLine($"class {className}:");
        block.AppendLine("\textends RefCounted");
        block.AppendLine();
        block.AppendLine("\tvar _raw: Dictionary = {}");
        block.AppendLine();
        block.AppendLine($"\tstatic func wrap(raw: Dictionary):");
        block.AppendLine($"\t\tvar obj := {className}.new()");
        block.AppendLine("\t\tobj._raw = raw");
        block.AppendLine("\t\treturn obj");
        block.AppendLine();
        block.AppendLine("\tfunc raw() -> Dictionary:");
        block.AppendLine("\t\treturn _raw");

        foreach (var field in fields)
        {
            block.AppendLine();
            block.AppendLine($"\tfunc {field.Name}() -> {GdReturnType(field, eventMode)}:");
            block.AppendLine($"\t\treturn {GdGetter(field, eventMode)}");

            if (field.IsRepeated && schema != null && !IsIntLike(field.Type) && schema.Messages.ContainsKey(field.Type))
            {
                block.AppendLine();
                block.AppendLine($"\tfunc {field.Name}_wrapped() -> Array:");
                block.AppendLine("\t\tvar out: Array = []");
                block.AppendLine($"\t\tfor item in {field.Name}():");
                block.AppendLine($"\t\t\tout.append(Wrapped{field.Type}.wrap(item))");
                block.AppendLine("\t\treturn out");
            }
        }

        return block.ToString().TrimEnd();
    }

    private static string ClassNameForEvent(string messageType)
    {
        return messageType.EndsWith("Event", StringComparison.Ordinal)
            ? messageType[..^"Event".Length]
            : messageType;
    }

    private static string EnumTail(string value)
    {
        var parts = value.Split('_', StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length <= 2)
        {
            return value.ToLowerInvariant();
        }
        return string.Join("_", parts.Skip(2)).ToLowerInvariant();
    }

    private static string Pascal(string value)
    {
        var text = new StringBuilder();
        foreach (var part in value.Split('_', StringSplitOptions.RemoveEmptyEntries))
        {
            text.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
            {
                text.Append(part[1..].ToLowerInvariant());
            }
        }
        return text.Length == 0 ? "Value" : text.ToString();
    }

    private static string CsCoreType(string type, bool repeated)
    {
        var itemType = type switch
        {
            "string" => "string",
            "bool" => "bool",
            "float" or "double" => "float",
            "Vec2i" => "Vector2I",
            "PlayerId" => "long",
            "EntityId" => "int",
            "PlayerAction" => "PlayerAction?",
            "EntityKind" or "ItemKind" or "WeaponSlot" or "WeaponPhase" => "string",
            _ when IsIntLike(type) => "int",
            _ => Pascal(type),
        };
        return repeated ? $"List<{itemType}>" : itemType;
    }

    private static string CsDefaultInit(ProtoField field)
    {
        if (field.IsRepeated)
        {
            return " = new();";
        }
        if (field.Type == "string")
        {
            return " = \"\";";
        }
        if (field.Type == "PlayerAction")
        {
            return "";
        }
        return field.Type switch
        {
            "EntityKind" => field.Name == "victim_kind"
                ? " = BridgeEntityKind.Dummy;"
                : $" = BridgeEntityKind.{Pascal(EnumDefault("EntityKind"))};",
            "ItemKind" => $" = BridgeItemKind.{Pascal(EnumDefault("ItemKind"))};",
            "WeaponSlot" => $" = BridgeWeaponSlot.{Pascal(EnumDefault("WeaponSlot"))};",
            "WeaponPhase" => $" = BridgeWeaponPhase.{Pascal(EnumDefault("WeaponPhase"))};",
            _ when field.Name == "count" => " = 1;",
            _ => "",
        };
    }

    private static string GdArgType(ProtoField field)
    {
        if (field.IsRepeated) return "Array";
        return field.Type switch
        {
            "string" => "String",
            "bool" => "bool",
            "float" or "double" => "float",
            "Vec2i" => "Vector2i",
            _ when IsIntLike(field.Type) => "int",
            _ => "Variant"
        };
    }

    private static string GdReturnType(ProtoField field, bool eventMode)
    {
        if (field.IsRepeated) return "Array";
        return field.Type switch
        {
            "string" => "String",
            "bool" => "bool",
            "float" or "double" => "float",
            "Vec2i" => "Vector2i",
            _ when IsIntLike(field.Type) => "int",
            _ => eventMode ? "Variant" : "String"
        };
    }

    private static string GdGetter(ProtoField field, bool eventMode)
    {
        if (field.IsRepeated)
        {
            return $"_raw.get(\"{field.Name}\", [])";
        }

        return field.Type switch
        {
            "string" => $"str(_raw.get(\"{field.Name}\", \"\"))",
            "bool" => $"bool(_raw.get(\"{field.Name}\", false))",
            "float" or "double" => $"float(_raw.get(\"{field.Name}\", 0.0))",
            "Vec2i" => $"_raw.get(\"{field.Name}\", Vector2i.ZERO)",
            _ when IsIntLike(field.Type) => $"int(_raw.get(\"{field.Name}\", 0))",
            _ => eventMode ? $"_raw.get(\"{field.Name}\", null)" : $"str(_raw.get(\"{field.Name}\", \"{EnumDefault(field.Type)}\"))"
        };
    }

    private static string EnumDefault(string type)
    {
        return type switch
        {
            "EntityKind" => "Player",
            "ItemKind" => "Torch",
            "WeaponSlot" => "Sword",
            "WeaponPhase" => "Idle",
            _ => ""
        };
    }

    private static bool IsIntLike(string type)
    {
        return type is "int32" or "int64" or "uint32" or "uint64" or "sint32" or "sint64"
            || type.EndsWith("Id", StringComparison.Ordinal);
    }
}
