using System.Globalization;
using System.Text;
using System.Text.Json;

static class ConfigGen
{
    public static void Generate(string root, FwConfig config)
    {
        var schemaDir = config.ConfigSchemaDir(root);
        var schema = ProtoSchema.ParseFiles(Directory.Exists(schemaDir)
            ? Directory.GetFiles(schemaDir, "*.proto").OrderBy(item => item, StringComparer.Ordinal)
            : []);

        GenerateCSharp(root, config, schema);
        GenerateGd(root, config, schema);
    }

    private static void GenerateCSharp(string root, FwConfig config, ProtoSchema schema)
    {
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        var roots = ConfigRoots(root, config, schema);

        GenerateCSharpContract(config.ConfigContractCsPath(root), schema, rootNamespace, roots);
        GenerateCSharpCodec(
            config.ConfigCodecCsPath(root),
            schema,
            rootNamespace);
    }

    private static void GenerateGd(string root, FwConfig config, ProtoSchema schema)
    {
        var messages = schema.Messages.Values
            .Where(item => item.Name != "Fixed32")
            .OrderBy(item => item.Name.EndsWith("Config", StringComparison.Ordinal) ? 1 : 0)
            .ThenBy(item => item.Name, StringComparer.Ordinal)
            .ToArray();
        var roots = ConfigRoots(root, config, schema);

        var text = new StringBuilder();
        text.Append(GdRuntimePrelude());
        RenderGdDefaults(text, messages, schema);
        RenderGdParsers(text, messages, schema, false);
        RenderGdParsers(text, messages, schema, true);
        RenderGdLoaders(text, roots, schema);

        var output = config.ConfigGdPath(root);
        TextUtil.WriteText(output, text.ToString());
        Console.WriteLine($"generated config gd script: {output}");
    }

    private static ConfigRoot[] ConfigRoots(string root, FwConfig config, ProtoSchema schema)
    {
        var dataDir = config.ConfigDataDir(root);
        var packDir = config.ConfigPackDir(root);
        return schema.Messages.Values
            .Where(item => item.Name.EndsWith("Config", StringComparison.Ordinal))
            .Select(item =>
            {
                var rootName = TextUtil.Snake(item.Name[..^"Config".Length]);
                var isJson = File.Exists(Path.Combine(dataDir, $"{rootName}.json"));
                var sourcePath = ResourcePath(root, Path.Combine(dataDir, isJson ? $"{rootName}.json" : $"{rootName}.csv.txt"));
                var packPath = ResourcePath(root, Path.Combine(packDir, $"{rootName}.bin"));
                return new ConfigRoot(rootName, item, isJson, sourcePath, packPath);
            })
            .OrderBy(item => item.Name, StringComparer.Ordinal)
            .ToArray();
    }

    private static string GdRuntimePrelude()
    {
        return """
# This file is generated by fwgen. Do not edit manually.
extends RefCounted
class_name _config

const PACK_MAGIC: Array[int] = [87, 67, 70, 71]
const FIXED_SCALE: float = 256.0

static func _normalize_csv_header(header: String, index: int) -> String:
	if index == 0 and not header.is_empty() and header.unicode_at(0) == 0xfeff:
		return header.substr(1)
	return header

static func _read_csv_rows(path: String) -> Array:
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	assert(file != null, "failed to open %s" % path)
	var headers: PackedStringArray = file.get_csv_line()
	var rows: Array = []
	while not file.eof_reached():
		var values: PackedStringArray = file.get_csv_line()
		if values.is_empty():
			continue
		var row: Dictionary = {}
		for index in range(min(headers.size(), values.size())):
			row[_normalize_csv_header(str(headers[index]), index)] = str(values[index])
		rows.append(row)
	return rows

static func _read_json_array(path: String, ctx: String) -> Array:
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	assert(file != null, "failed to open %s" % path)
	var parsed: Variant = JSON.parse_string(file.get_as_text())
	assert(parsed is Array, "%s must be a json array" % ctx)
	return parsed

static func _read_bin_entries(path: String, ctx: String) -> Array:
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	assert(file != null, "failed to open %s" % path)
	var bytes: PackedByteArray = file.get_buffer(file.get_length())
	assert(bytes.size() >= PACK_MAGIC.size(), "%s binary is too short" % ctx)
	for index in range(PACK_MAGIC.size()):
		assert(bytes[index] == PACK_MAGIC[index], "%s binary magic mismatch" % ctx)
	var payload: PackedByteArray = PackedByteArray()
	payload.resize(bytes.size() - PACK_MAGIC.size())
	for index in range(payload.size()):
		payload[index] = bytes[PACK_MAGIC.size() + index]
	var parsed: Variant = JSON.parse_string(payload.get_string_from_utf8())
	assert(parsed is Array, "%s binary payload must be an array" % ctx)
	return parsed

static func _cell(row: Dictionary, field: String, ctx: String) -> String:
	assert(row.has(field), "%s missing column %s" % [ctx, field])
	return str(row[field])

static func _as_dictionary(value: Variant, ctx: String) -> Dictionary:
	assert(value is Dictionary, "%s must be a dictionary" % ctx)
	return value

static func _object_field(obj: Dictionary, field: String, ctx: String) -> Variant:
	assert(obj.has(field), "%s missing field %s" % [ctx, field])
	return obj[field]

static func _parse_text_int(value: Variant, ctx: String) -> int:
	match typeof(value):
		TYPE_STRING:
			var text: String = str(value)
			assert(text.is_valid_int(), "%s must be int-compatible text" % ctx)
			return int(text)
		TYPE_INT, TYPE_FLOAT:
			return int(value)
		_:
			assert(false, "%s must be int-compatible value" % ctx)
			return 0

static func _parse_text_bool(value: Variant, ctx: String) -> bool:
	match typeof(value):
		TYPE_BOOL:
			return bool(value)
		TYPE_STRING:
			var text: String = str(value).to_lower()
			if text in ["1", "true", "yes"]:
				return true
			if text in ["0", "false", "no"]:
				return false
		_:
			pass
	assert(false, "%s must be bool-compatible value" % ctx)
	return false

static func _parse_text_fixed(value: Variant, ctx: String) -> float:
	return _parse_text_float(value, ctx)

static func _parse_text_float(value: Variant, ctx: String) -> float:
	match typeof(value):
		TYPE_STRING:
			var text: String = str(value)
			assert(text.is_valid_float() or text.is_valid_int(), "%s must be float-compatible text" % ctx)
			return float(text)
		TYPE_INT, TYPE_FLOAT:
			return float(value)
		_:
			assert(false, "%s must be float-compatible value" % ctx)
			return 0.0

static func _parse_text_string(value: Variant, _ctx: String) -> String:
	return str(value)

static func _parse_text_array(value: Variant, ctx: String, item_parser: Callable) -> Array:
	assert(value is Array, "%s must be an array" % ctx)
	var items: Array = value
	var out: Array = []
	for index in range(items.size()):
		out.append(item_parser.call(items[index], "%s[%d]" % [ctx, index]))
	return out

static func _parse_bin_int(value: Variant, ctx: String) -> int:
	match typeof(value):
		TYPE_INT, TYPE_FLOAT:
			return int(value)
		TYPE_STRING:
			var text: String = str(value)
			assert(text.is_valid_int(), "%s must be int-compatible text" % ctx)
			return int(text)
		_:
			assert(false, "%s must be int-compatible value" % ctx)
			return 0

static func _parse_bin_bool(value: Variant, ctx: String) -> bool:
	if typeof(value) == TYPE_BOOL:
		return bool(value)
	assert(false, "%s must be bool" % ctx)
	return false

static func _parse_bin_fixed(value: Variant, ctx: String) -> float:
	return _parse_bin_float(value, ctx) / FIXED_SCALE

static func _parse_bin_float(value: Variant, ctx: String) -> float:
	match typeof(value):
		TYPE_INT, TYPE_FLOAT:
			return float(value)
		TYPE_STRING:
			var text: String = str(value)
			assert(text.is_valid_float() or text.is_valid_int(), "%s must be float-compatible text" % ctx)
			return float(text)
		_:
			assert(false, "%s must be float-compatible value" % ctx)
			return 0.0

static func _parse_bin_string(value: Variant, ctx: String) -> String:
	if typeof(value) == TYPE_STRING:
		return str(value)
	assert(false, "%s must be string" % ctx)
	return ""

static func _parse_bin_array(value: Variant, ctx: String, item_parser: Callable) -> Array:
	assert(value is Array, "%s must be an array" % ctx)
	var items: Array = value
	var out: Array = []
	for index in range(items.size()):
		out.append(item_parser.call(items[index], "%s[%d]" % [ctx, index]))
	return out

static func _clone_value(value: Variant) -> Variant:
	if value is Dictionary:
		var out: Dictionary = {}
		for key in value.keys():
			out[key] = _clone_value(value[key])
		return out
	if value is Array:
		var out: Array = []
		for item in value:
			out.append(_clone_value(item))
		return out
	return value

static func _clone_by_key(entries: Array, key: String) -> Dictionary:
	for item in entries:
		var entry: Dictionary = _as_dictionary(item, "entry")
		if str(entry.get("key", "")) == key:
			return _clone_value(entry.get("value", {}))
	return {}

static func _clone_required_by_key(entries: Array, key: String, ctx: String) -> Dictionary:
	var value: Dictionary = _clone_by_key(entries, key)
	assert(not value.is_empty(), "%s references missing key %s" % [ctx, key])
	return value

static func _clone_by_index(entries: Array, index: int) -> Dictionary:
	if index < 0 or index >= entries.size():
		return {}
	var entry: Dictionary = _as_dictionary(entries[index], "entry")
	return _clone_value(entry.get("value", {}))

static func _clone_all(entries: Array) -> Array:
	var out: Array = []
	for item in entries:
		var entry: Dictionary = _as_dictionary(item, "entry")
		out.append({
			"key": str(entry.get("key", "")),
			"value": _clone_value(entry.get("value", {})),
		})
	return out

""";
    }

    private static void RenderGdDefaults(StringBuilder text, IEnumerable<ProtoMessage> messages, ProtoSchema schema)
    {
        foreach (var message in messages)
        {
            var name = TextUtil.Snake(message.Name);
            text.AppendLine($"static func _default_{name}() -> Dictionary:");
            text.AppendLine("\treturn {");
            foreach (var field in message.Fields)
            {
                text.AppendLine($"\t\t\"{field.Name}\": {GdDefaultExpr(field, schema)},");
            }
            text.AppendLine("\t}");
            text.AppendLine();
        }
    }

    private static void RenderGdParsers(
        StringBuilder text,
        IEnumerable<ProtoMessage> messages,
        ProtoSchema schema,
        bool binary
    )
    {
        var mode = binary ? "bin" : "text";
        foreach (var message in messages)
        {
            var name = TextUtil.Snake(message.Name);
            text.AppendLine($"static func _parse_{mode}_{name}(value: Variant, ctx: String) -> Dictionary:");
            text.AppendLine("\tvar obj: Dictionary = _as_dictionary(value, ctx)");
            text.AppendLine("\treturn {");
            foreach (var field in message.Fields)
            {
                var ctx = $"\"%s.{field.Name}\" % ctx";
                var expr = GdFieldParseExpr(field, schema, binary, $"_object_field(obj, \"{field.Name}\", ctx)", ctx);
                var fallback = GdMissingFieldExpr(field, schema);
                text.AppendLine($"\t\t\"{field.Name}\": {expr} if obj.has(\"{field.Name}\") else {fallback},");
            }
            text.AppendLine("\t}");
            text.AppendLine();
        }
    }

    private static void RenderGdLoaders(StringBuilder text, IEnumerable<ConfigRoot> roots, ProtoSchema schema)
    {
        foreach (var root in roots)
        {
            text.AppendLine($"static var _{root.Name}_loaded: bool = false");
            text.AppendLine($"static var _{root.Name}_entries: Array = []");
            text.AppendLine();

            if (root.IsJson)
            {
                RenderGdJsonLoader(text, root);
            }
            else
            {
                RenderGdCsvLoader(text, root, schema);
            }
            RenderGdBinLoader(text, root);
            RenderGdEntryAccess(text, root);
        }
    }

    private static void RenderGdCsvLoader(StringBuilder text, ConfigRoot root, ProtoSchema schema)
    {
        text.AppendLine($"static func _load_{root.Name}_text() -> Array:");
        text.AppendLine($"\tvar rows: Array = _read_csv_rows(\"{root.SourcePath}\")");
        text.AppendLine("\tvar entries: Array = []");
        text.AppendLine("\tfor index in range(rows.size()):");
        text.AppendLine("\t\tvar row: Dictionary = rows[index]");
        text.AppendLine($"\t\tvar ctx: String = \"{root.Name}[%d]\" % index");
        text.AppendLine("\t\tvar value: Dictionary = {");
        foreach (var field in root.Message.Fields)
        {
            var ctx = $"\"%s.{field.Name}\" % ctx";
            var expr = GdCsvFieldExpr(field, schema, $"_cell(row, \"{field.Name}\", ctx)", ctx);
            var fallback = GdMissingFieldExpr(field, schema);
            text.AppendLine($"\t\t\t\"{field.Name}\": {expr} if row.has(\"{field.Name}\") else {fallback},");
        }
        text.AppendLine("\t\t}");
        text.AppendLine("\t\tentries.append({\"key\": _cell(row, \"key\", ctx), \"value\": value})");
        text.AppendLine("\treturn entries");
        text.AppendLine();
    }

    private static void RenderGdJsonLoader(StringBuilder text, ConfigRoot root)
    {
        var parseName = TextUtil.Snake(root.Message.Name);
        text.AppendLine($"static func _load_{root.Name}_text() -> Array:");
        text.AppendLine($"\tvar items: Array = _read_json_array(\"{root.SourcePath}\", \"{root.Name}\")");
        text.AppendLine("\tvar entries: Array = []");
        text.AppendLine("\tfor index in range(items.size()):");
        text.AppendLine($"\t\tvar item: Dictionary = _as_dictionary(items[index], \"%s[%d]\" % [\"{root.Name}\", index])");
        text.AppendLine($"\t\tvar ctx: String = \"{root.Name}[%d]\" % index");
        text.AppendLine($"\t\tentries.append({{\"key\": _parse_text_string(_object_field(item, \"key\", ctx), \"%s.key\" % ctx), \"value\": _parse_text_{parseName}(item, ctx)}})");
        text.AppendLine("\treturn entries");
        text.AppendLine();
    }

    private static void RenderGdBinLoader(StringBuilder text, ConfigRoot root)
    {
        var parseName = TextUtil.Snake(root.Message.Name);
        text.AppendLine($"static func _load_{root.Name}_bin() -> Array:");
        text.AppendLine($"\tvar raw_entries: Array = _read_bin_entries(\"{root.PackPath}\", \"{root.Name}\")");
        text.AppendLine("\tvar entries: Array = []");
        text.AppendLine("\tfor index in range(raw_entries.size()):");
        text.AppendLine($"\t\tvar item: Dictionary = _as_dictionary(raw_entries[index], \"%s[%d]\" % [\"{root.Name}\", index])");
        text.AppendLine($"\t\tvar ctx: String = \"{root.Name}[%d]\" % index");
        text.AppendLine($"\t\tentries.append({{\"key\": _parse_bin_string(_object_field(item, \"key\", ctx), \"%s.key\" % ctx), \"value\": _parse_bin_{parseName}(_object_field(item, \"value\", ctx), \"%s.value\" % ctx)}})");
        text.AppendLine("\treturn entries");
        text.AppendLine();
    }

    private static void RenderGdEntryAccess(StringBuilder text, ConfigRoot root)
    {
        text.AppendLine($"static func _load_{root.Name}_entries() -> Array:");
        text.AppendLine($"\tif _{root.Name}_loaded:");
        text.AppendLine($"\t\treturn _{root.Name}_entries");
        text.AppendLine("\tif OS.has_feature(\"editor\"):");
        text.AppendLine($"\t\t_{root.Name}_entries = _load_{root.Name}_text()");
        text.AppendLine("\telse:");
        text.AppendLine($"\t\t_{root.Name}_entries = _load_{root.Name}_bin()");
        text.AppendLine($"\t_{root.Name}_loaded = true");
        text.AppendLine($"\treturn _{root.Name}_entries");
        text.AppendLine();
        text.AppendLine($"static func {root.Name}_by_key(key: String) -> Dictionary:");
        text.AppendLine($"\treturn _clone_by_key(_load_{root.Name}_entries(), key)");
        text.AppendLine();
        text.AppendLine($"static func {root.Name}_by_index(index: int) -> Dictionary:");
        text.AppendLine($"\treturn _clone_by_index(_load_{root.Name}_entries(), index)");
        text.AppendLine();
        text.AppendLine($"static func {root.Name}_all() -> Array:");
        text.AppendLine($"\treturn _clone_all(_load_{root.Name}_entries())");
        text.AppendLine();
        text.AppendLine($"static func {root.Name}_default_config() -> Dictionary:");
        text.AppendLine($"\tvar value: Dictionary = {root.Name}_by_key(\"default\")");
        text.AppendLine("\tassert(not value.is_empty(), \"generated config source must contain default\")");
        text.AppendLine("\treturn value");
        text.AppendLine();
    }

    private static string GdCsvFieldExpr(ProtoField field, ProtoSchema schema, string valueExpr, string ctxExpr)
    {
        if (field.IsRepeated)
        {
            return $"_parse_text_array(JSON.parse_string({valueExpr}), {ctxExpr}, {GdParserName(field.Type, false)})";
        }
        if (IsMessageType(field.Type, schema) && field.Type != "Fixed32")
        {
            if (IsConfigMessage(field.Type))
            {
                return $"_clone_required_by_key(_load_{ConfigRootName(field.Type)}_entries(), {valueExpr}, {ctxExpr})";
            }
            return $"_parse_text_{TextUtil.Snake(field.Type)}(JSON.parse_string({valueExpr}), {ctxExpr})";
        }
        return $"{GdScalarParser(field.Type, false)}({valueExpr}, {ctxExpr})";
    }

    private static string GdFieldParseExpr(
        ProtoField field,
        ProtoSchema schema,
        bool binary,
        string valueExpr,
        string ctxExpr
    )
    {
        var mode = binary ? "bin" : "text";
        if (field.IsRepeated)
        {
            return $"_parse_{mode}_array({valueExpr}, {ctxExpr}, {GdParserName(field.Type, binary)})";
        }
        if (IsMessageType(field.Type, schema) && field.Type != "Fixed32")
        {
            var parser = $"_parse_{mode}_{TextUtil.Snake(field.Type)}({valueExpr}, {ctxExpr})";
            if (!IsConfigMessage(field.Type))
            {
                return parser;
            }
            var rootName = ConfigRootName(field.Type);
            return $"(_clone_required_by_key(_load_{rootName}_entries(), str({valueExpr}), {ctxExpr}) if typeof({valueExpr}) == TYPE_STRING else {parser})";
        }
        return $"{GdScalarParser(field.Type, binary)}({valueExpr}, {ctxExpr})";
    }

    private static string GdParserName(string type, bool binary)
    {
        if (type == "Fixed32")
        {
            return binary ? "_parse_bin_fixed" : "_parse_text_fixed";
        }
        return type switch
        {
            "string" => binary ? "_parse_bin_string" : "_parse_text_string",
            "bool" => binary ? "_parse_bin_bool" : "_parse_text_bool",
            "float" or "double" => binary ? "_parse_bin_float" : "_parse_text_float",
            "uint32" or "uint64" or "int32" or "sint32" or "int64" or "sint64" => binary ? "_parse_bin_int" : "_parse_text_int",
            _ => binary ? $"_parse_bin_{TextUtil.Snake(type)}" : $"_parse_text_{TextUtil.Snake(type)}",
        };
    }

    private static string GdScalarParser(string type, bool binary)
    {
        return GdParserName(type, binary);
    }

    private static string GdMissingFieldExpr(ProtoField field, ProtoSchema schema)
    {
        if (field.IsRepeated)
        {
            return "[]";
        }
        if (IsMessageType(field.Type, schema) && field.Type != "Fixed32")
        {
            return IsConfigMessage(field.Type)
                ? $"_clone_required_by_key(_load_{ConfigRootName(field.Type)}_entries(), \"default\", \"%s.{field.Name}\" % ctx)"
                : $"_default_{TextUtil.Snake(field.Type)}()";
        }
        return GdDefaultExpr(field, schema);
    }

    private static string GdDefaultExpr(ProtoField field, ProtoSchema schema)
    {
        if (field.IsRepeated)
        {
            return "[]";
        }
        if (field.Type == "Fixed32" || field.Type is "float" or "double")
        {
            return "0.0";
        }
        if (field.Type == "bool")
        {
            return "false";
        }
        if (field.Type == "string")
        {
            return "\"\"";
        }
        if (IsMessageType(field.Type, schema))
        {
            return "{}";
        }
        return "0";
    }

    private static bool IsMessageType(string type, ProtoSchema schema)
    {
        return schema.Messages.ContainsKey(type);
    }

    private static bool IsConfigMessage(string type)
    {
        return type.EndsWith("Config", StringComparison.Ordinal);
    }

    private static string ConfigRootName(string type)
    {
        return TextUtil.Snake(type[..^"Config".Length]);
    }

    private static string ConfigClassName(string type)
    {
        return type == "GameConfig" ? "CoreConfig" : type;
    }

    private static void GenerateCSharpContract(
        string output,
        ProtoSchema schema,
        string rootNamespace,
        IEnumerable<ConfigRoot> roots
    )
    {
        var messages = schema.Messages.Values
            .Where(item => item.Name != "Fixed32")
            .OrderBy(item => item.Name == "GameConfig" ? "CoreConfig" : item.Name, StringComparer.Ordinal)
            .ToArray();

        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen config. Do not edit.");
        text.AppendLine("using System.Collections.Generic;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Core;");
        text.AppendLine();
        RenderConfigFields(text, schema);
        text.AppendLine();
        RenderConfigPaths(text, roots);
        text.AppendLine();
        foreach (var message in messages)
        {
            var className = message.Name == "GameConfig" ? "CoreConfig" : message.Name;
            text.AppendLine($"public sealed class {className}");
            text.AppendLine("{");
            foreach (var field in message.Fields)
            {
                text.AppendLine($"    public {CsConfigType(field.Type, field.IsRepeated)} {Pascal(field.Name)} {{ get; init; }}{CsConfigInit(field, schema)}");
            }
            text.AppendLine("}");
            text.AppendLine();
        }

        TextUtil.WriteText(output, text.ToString());
        Console.WriteLine($"generated config csharp contract: {output}");
    }

    private static void RenderConfigPaths(StringBuilder text, IEnumerable<ConfigRoot> roots)
    {
        var orderedRoots = roots.OrderBy(item => item.Name, StringComparer.Ordinal).ToArray();

        text.AppendLine("public static class ConfigPath");
        text.AppendLine("{");
        foreach (var root in orderedRoots)
        {
            var name = Pascal(root.Name);
            text.AppendLine($"    public const string {name}Source = \"{EscapeCs(root.SourcePath)}\";");
            text.AppendLine($"    public const string {name}Pack = \"{EscapeCs(root.PackPath)}\";");
        }
        text.AppendLine();
        text.AppendLine("    public static IReadOnlyList<string> AllSourcePaths { get; } = new[]");
        text.AppendLine("    {");
        foreach (var root in orderedRoots)
        {
            text.AppendLine($"        {Pascal(root.Name)}Source,");
        }
        text.AppendLine("    };");
        text.AppendLine();
        text.AppendLine("    public static IReadOnlyList<string> AllPackPaths { get; } = new[]");
        text.AppendLine("    {");
        foreach (var root in orderedRoots)
        {
            text.AppendLine($"        {Pascal(root.Name)}Pack,");
        }
        text.AppendLine("    };");
        text.AppendLine("}");
    }

    private static void GenerateCSharpCodec(string output, ProtoSchema schema, string rootNamespace)
    {
        var rowMessages = schema.Messages.Values
            .Where(item => item.Name.EndsWith("Config", StringComparison.Ordinal))
            .Where(item => CanGenerateRowReader(item, schema))
            .OrderBy(item => item.Name, StringComparer.Ordinal)
            .ToArray();
        var packMessages = schema.Messages.Values
            .Where(item => item.Name != "Fixed32")
            .OrderBy(item => item.Name.EndsWith("Config", StringComparison.Ordinal) ? 1 : 0)
            .ThenBy(item => item.Name, StringComparer.Ordinal)
            .ToArray();

        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen config. Do not edit.");
        text.AppendLine("using System;");
        text.AppendLine("using System.Collections.Generic;");
        text.AppendLine("using System.Globalization;");
        text.AppendLine("using System.Text;");
        text.AppendLine("using System.Text.Json;");
        text.AppendLine("using Godot;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Core;");
        text.AppendLine();
        text.AppendLine("public static class ConfigCodec");
        text.AppendLine("{");
        RenderConfigRowReaders(text, rowMessages);
        RenderConfigPackReaders(text, schema, packMessages);
        RenderConfigCsvRuntime(text);
        text.AppendLine("}");
        TextUtil.WriteText(output, text.ToString());
        Console.WriteLine($"generated config csharp codec: {output}");
    }

    private static void RenderConfigFields(StringBuilder text, ProtoSchema schema)
    {
        var fields = schema.Messages.Values
            .SelectMany(message => message.Fields)
            .Select(field => field.Name)
            .Append("key")
            .Distinct(StringComparer.Ordinal)
            .OrderBy(item => item, StringComparer.Ordinal)
            .ToArray();

        text.AppendLine("public static class ConfigField");
        text.AppendLine("{");
        foreach (var field in fields)
        {
            text.AppendLine($"    public const string {Pascal(field)} = \"{field}\";");
        }
        text.AppendLine("}");
    }

    private static string CsConfigType(string type, bool repeated)
    {
        var itemType = type switch
        {
            "string" => "string",
            "bool" => "bool",
            "float" or "double" or "Fixed32" => "float",
            "uint32" => "int",
            "uint64" => "ulong",
            "int32" or "sint32" => "int",
            "int64" or "sint64" => "long",
            _ => type == "GameConfig" ? "CoreConfig" : type,
        };
        return repeated ? $"List<{itemType}>" : itemType;
    }

    private static string CsConfigInit(ProtoField field, ProtoSchema schema)
    {
        if (field.IsRepeated)
        {
            return " = new();";
        }
        if (field.Type == "string")
        {
            return " = \"\";";
        }
        if (schema.Messages.ContainsKey(field.Type) && field.Type != "Fixed32")
        {
            return " = new();";
        }
        return "";
    }

    private static bool CanGenerateRowReader(ProtoMessage message, ProtoSchema schema)
    {
        return message.Fields.All(field => !field.IsRepeated && IsConfigScalar(field.Type, schema));
    }

    private static bool IsConfigScalar(string type, ProtoSchema schema)
    {
        return type is "string" or "bool" or "float" or "double" or "Fixed32"
            or "uint32" or "uint64" or "int32" or "sint32" or "int64" or "sint64"
            || !schema.Messages.ContainsKey(type);
    }

    private static void RenderConfigRowReaders(StringBuilder text, IEnumerable<ProtoMessage> messages)
    {
        foreach (var message in messages)
        {
            var className = message.Name == "GameConfig" ? "CoreConfig" : message.Name;
            text.AppendLine($"    public static {className} Read{className}(Dictionary<string, string>? row)");
            text.AppendLine("    {");
            text.AppendLine($"        return new {className}");
            text.AppendLine("        {");
            foreach (var field in message.Fields)
            {
                text.AppendLine($"            {Pascal(field.Name)} = {ConfigReadExpr(field)},");
            }
            text.AppendLine("        };");
            text.AppendLine("    }");
            text.AppendLine();
        }
    }

    private static string ConfigReadExpr(ProtoField field)
    {
        var fieldName = $"ConfigField.{Pascal(field.Name)}";
        return field.Type switch
        {
            "string" => $"ReadString(row, {fieldName}, \"\")",
            "bool" => $"ReadBool(row, {fieldName}, false)",
            "float" or "double" or "Fixed32" => $"ReadFloat(row, {fieldName}, 0.0f)",
            "uint64" => $"ReadULong(row, {fieldName}, 0)",
            "int64" or "sint64" => $"ReadLong(row, {fieldName}, 0)",
            _ => $"ReadInt(row, {fieldName}, 0)",
        };
    }

    private static void RenderConfigPackReaders(
        StringBuilder text,
        ProtoSchema schema,
        IEnumerable<ProtoMessage> messages
    )
    {
        var items = messages.ToArray();
        foreach (var message in items.Where(item => item.Name.EndsWith("Config", StringComparison.Ordinal)))
        {
            var className = ConfigClassName(message.Name);
            var rootName = TextUtil.Snake(message.Name[..^"Config".Length]);
            text.AppendLine($"    public static {className} Read{className}Pack(string key)");
            text.AppendLine("    {");
            text.AppendLine($"        JsonElement? value = ReadPackValue(ConfigPath.{Pascal(rootName)}Pack, key);");
            text.AppendLine($"        return value.HasValue ? Parse{className}Pack(value.Value) : new {className}();");
            text.AppendLine("    }");
            text.AppendLine();
        }

        foreach (var message in items)
        {
            RenderConfigPackParser(text, schema, message);
        }

        RenderConfigPackRuntime(text);
    }

    private static void RenderConfigPackParser(
        StringBuilder text,
        ProtoSchema schema,
        ProtoMessage message
    )
    {
        var className = ConfigClassName(message.Name);
        text.AppendLine($"    private static {className} Parse{className}Pack(JsonElement obj)");
        text.AppendLine("    {");
        text.AppendLine("        if (obj.ValueKind != JsonValueKind.Object)");
        text.AppendLine("        {");
        text.AppendLine($"            return new {className}();");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine($"        return new {className}");
        text.AppendLine("        {");
        foreach (var field in message.Fields)
        {
            text.AppendLine($"            {Pascal(field.Name)} = {ConfigPackExpr(field, schema)},");
        }
        text.AppendLine("        };");
        text.AppendLine("    }");
        text.AppendLine();
    }

    private static string ConfigPackExpr(ProtoField field, ProtoSchema schema)
    {
        var fieldName = $"ConfigField.{Pascal(field.Name)}";
        if (field.IsRepeated)
        {
            return IsMessageType(field.Type, schema) && field.Type != "Fixed32"
                ? $"ReadPackArray(obj, {fieldName}, Parse{ConfigClassName(field.Type)}Pack)"
                : $"ReadPackScalarArray(obj, {fieldName}, {ConfigPackScalarParser(field.Type)})";
        }

        if (IsMessageType(field.Type, schema) && field.Type != "Fixed32")
        {
            if (IsConfigMessage(field.Type))
            {
                var rootName = ConfigRootName(field.Type);
                return $"ReadPackConfigRef(obj, {fieldName}, ConfigPath.{Pascal(rootName)}Pack, Parse{ConfigClassName(field.Type)}Pack)";
            }
            return $"ReadPackMessage(obj, {fieldName}, Parse{ConfigClassName(field.Type)}Pack)";
        }

        return field.Type switch
        {
            "string" => $"ReadPackString(obj, {fieldName}, \"\")",
            "bool" => $"ReadPackBool(obj, {fieldName}, false)",
            "float" or "double" => $"ReadPackFloat(obj, {fieldName}, 0.0f)",
            "Fixed32" => $"ReadPackFixed(obj, {fieldName}, 0.0f)",
            "uint64" => $"ReadPackULong(obj, {fieldName}, 0)",
            "int64" or "sint64" => $"ReadPackLong(obj, {fieldName}, 0)",
            _ => $"ReadPackInt(obj, {fieldName}, 0)",
        };
    }

    private static string ConfigPackScalarParser(string type)
    {
        return type switch
        {
            "string" => "ReadPackStringItem",
            "bool" => "ReadPackBoolItem",
            "float" or "double" => "ReadPackFloatItem",
            "Fixed32" => "ReadPackFixedItem",
            "uint64" => "ReadPackULongItem",
            "int64" or "sint64" => "ReadPackLongItem",
            _ => "ReadPackIntItem",
        };
    }

    private static void RenderConfigPackRuntime(StringBuilder text)
    {
        text.AppendLine("    public static JsonElement? ReadPackValue(string path, string key)");
        text.AppendLine("    {");
        text.AppendLine("        byte[] bytes = FileAccess.GetFileAsBytes(path);");
        text.AppendLine("        if (bytes.Length < 4 || bytes[0] != 87 || bytes[1] != 67 || bytes[2] != 70 || bytes[3] != 71)");
        text.AppendLine("        {");
        text.AppendLine("            return null;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        string text = Encoding.UTF8.GetString(bytes, 4, bytes.Length - 4);");
        text.AppendLine("        using JsonDocument document = JsonDocument.Parse(text);");
        text.AppendLine("        if (document.RootElement.ValueKind != JsonValueKind.Array)");
        text.AppendLine("        {");
        text.AppendLine("            return null;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        foreach (JsonElement entry in document.RootElement.EnumerateArray())");
        text.AppendLine("        {");
        text.AppendLine("            if (entry.ValueKind != JsonValueKind.Object)");
        text.AppendLine("            {");
        text.AppendLine("                continue;");
        text.AppendLine("            }");
        text.AppendLine("            if (!entry.TryGetProperty(ConfigField.Key, out JsonElement keyElement))");
        text.AppendLine("            {");
        text.AppendLine("                continue;");
        text.AppendLine("            }");
        text.AppendLine("            if (ReadPackStringItem(keyElement, \"\") != key)");
        text.AppendLine("            {");
        text.AppendLine("                continue;");
        text.AppendLine("            }");
        text.AppendLine("            return entry.TryGetProperty(\"value\", out JsonElement value) ? value.Clone() : null;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        return null;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static T ReadPackConfigRef<T>(JsonElement obj, string field, string path, Func<JsonElement, T> parser) where T : new()");
        text.AppendLine("    {");
        text.AppendLine("        if (!obj.TryGetProperty(field, out JsonElement value))");
        text.AppendLine("        {");
        text.AppendLine("            return new T();");
        text.AppendLine("        }");
        text.AppendLine("        if (value.ValueKind == JsonValueKind.String)");
        text.AppendLine("        {");
        text.AppendLine("            JsonElement? packed = ReadPackValue(path, value.GetString() ?? \"default\");");
        text.AppendLine("            return packed.HasValue ? parser(packed.Value) : new T();");
        text.AppendLine("        }");
        text.AppendLine("        return value.ValueKind == JsonValueKind.Object ? parser(value) : new T();");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static T ReadPackMessage<T>(JsonElement obj, string field, Func<JsonElement, T> parser) where T : new()");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) && value.ValueKind == JsonValueKind.Object");
        text.AppendLine("            ? parser(value)");
        text.AppendLine("            : new T();");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static List<T> ReadPackArray<T>(JsonElement obj, string field, Func<JsonElement, T> parser)");
        text.AppendLine("    {");
        text.AppendLine("        var output = new List<T>();");
        text.AppendLine("        if (!obj.TryGetProperty(field, out JsonElement value) || value.ValueKind != JsonValueKind.Array)");
        text.AppendLine("        {");
        text.AppendLine("            return output;");
        text.AppendLine("        }");
        text.AppendLine("        foreach (JsonElement item in value.EnumerateArray())");
        text.AppendLine("        {");
        text.AppendLine("            output.Add(parser(item));");
        text.AppendLine("        }");
        text.AppendLine("        return output;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static List<T> ReadPackScalarArray<T>(JsonElement obj, string field, Func<JsonElement, T> parser)");
        text.AppendLine("    {");
        text.AppendLine("        var output = new List<T>();");
        text.AppendLine("        if (!obj.TryGetProperty(field, out JsonElement value) || value.ValueKind != JsonValueKind.Array)");
        text.AppendLine("        {");
        text.AppendLine("            return output;");
        text.AppendLine("        }");
        text.AppendLine("        foreach (JsonElement item in value.EnumerateArray())");
        text.AppendLine("        {");
        text.AppendLine("            output.Add(parser(item));");
        text.AppendLine("        }");
        text.AppendLine("        return output;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static int ReadPackInt(JsonElement obj, string field, int fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackIntItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static long ReadPackLong(JsonElement obj, string field, long fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackLongItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static ulong ReadPackULong(JsonElement obj, string field, ulong fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackULongItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static float ReadPackFloat(JsonElement obj, string field, float fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackFloatItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static float ReadPackFixed(JsonElement obj, string field, float fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackFixedItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool ReadPackBool(JsonElement obj, string field, bool fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackBoolItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static string ReadPackString(JsonElement obj, string field, string fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackStringItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static int ReadPackIntItem(JsonElement value, int fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int number)");
        text.AppendLine("            ? number");
        text.AppendLine("            : value.ValueKind == JsonValueKind.String && int.TryParse(value.GetString(), out int parsed) ? parsed : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static long ReadPackLongItem(JsonElement value, long fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return value.ValueKind == JsonValueKind.Number && value.TryGetInt64(out long number)");
        text.AppendLine("            ? number");
        text.AppendLine("            : value.ValueKind == JsonValueKind.String && long.TryParse(value.GetString(), out long parsed) ? parsed : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static ulong ReadPackULongItem(JsonElement value, ulong fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return value.ValueKind == JsonValueKind.Number && value.TryGetUInt64(out ulong number)");
        text.AppendLine("            ? number");
        text.AppendLine("            : value.ValueKind == JsonValueKind.String && ulong.TryParse(value.GetString(), out ulong parsed) ? parsed : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static float ReadPackFloatItem(JsonElement value, float fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return value.ValueKind == JsonValueKind.Number && value.TryGetSingle(out float number)");
        text.AppendLine("            ? number");
        text.AppendLine("            : value.ValueKind == JsonValueKind.String && float.TryParse(value.GetString(), NumberStyles.Float, CultureInfo.InvariantCulture, out float parsed) ? parsed : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static float ReadPackFixedItem(JsonElement value, float fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return ReadPackFloatItem(value, fallback * 256.0f) / 256.0f;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool ReadPackBoolItem(JsonElement value, bool fallback)");
        text.AppendLine("    {");
        text.AppendLine("        if (value.ValueKind == JsonValueKind.True)");
        text.AppendLine("        {");
        text.AppendLine("            return true;");
        text.AppendLine("        }");
        text.AppendLine("        if (value.ValueKind == JsonValueKind.False)");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine("        return value.ValueKind == JsonValueKind.String ? ReadBool(new Dictionary<string, string> { [\"_\"] = value.GetString() ?? \"\" }, \"_\", fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static string ReadPackStringItem(JsonElement value, string fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return value.ValueKind == JsonValueKind.String ? value.GetString() ?? fallback : value.ToString();");
        text.AppendLine("    }");
        text.AppendLine();
    }

    private static void RenderConfigCsvRuntime(StringBuilder text)
    {
        text.AppendLine("    public static Dictionary<string, string>? ReadRow(string path, string key)");
        text.AppendLine("    {");
        text.AppendLine("        string text = FileAccess.GetFileAsString(path);");
        text.AppendLine("        if (string.IsNullOrEmpty(text))");
        text.AppendLine("        {");
        text.AppendLine("            return null;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        string[] lines = text.Replace(\"\\r\\n\", \"\\n\").Replace('\\r', '\\n').Split('\\n');");
        text.AppendLine("        if (lines.Length == 0)");
        text.AppendLine("        {");
        text.AppendLine("            return null;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        string[] headers = SplitCsvLine(lines[0]);");
        text.AppendLine("        for (int lineIndex = 1; lineIndex < lines.Length; lineIndex += 1)");
        text.AppendLine("        {");
        text.AppendLine("            string line = lines[lineIndex].Trim();");
        text.AppendLine("            if (string.IsNullOrEmpty(line))");
        text.AppendLine("            {");
        text.AppendLine("                continue;");
        text.AppendLine("            }");
        text.AppendLine();
        text.AppendLine("            string[] values = SplitCsvLine(line);");
        text.AppendLine("            var row = new Dictionary<string, string>();");
        text.AppendLine("            for (int index = 0; index < System.Math.Min(headers.Length, values.Length); index += 1)");
        text.AppendLine("            {");
        text.AppendLine("                row[NormalizeHeader(headers[index], index)] = values[index];");
        text.AppendLine("            }");
        text.AppendLine();
        text.AppendLine("            if (row.TryGetValue(ConfigField.Key, out string? rowKey) && rowKey == key)");
        text.AppendLine("            {");
        text.AppendLine("                return row;");
        text.AppendLine("            }");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        return null;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static int ReadInt(Dictionary<string, string>? row, string field, int fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return row != null && row.TryGetValue(field, out string? value) && int.TryParse(value, out int parsed)");
        text.AppendLine("            ? parsed");
        text.AppendLine("            : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static long ReadLong(Dictionary<string, string>? row, string field, long fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return row != null && row.TryGetValue(field, out string? value) && long.TryParse(value, out long parsed)");
        text.AppendLine("            ? parsed");
        text.AppendLine("            : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static ulong ReadULong(Dictionary<string, string>? row, string field, ulong fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return row != null && row.TryGetValue(field, out string? value) && ulong.TryParse(value, out ulong parsed)");
        text.AppendLine("            ? parsed");
        text.AppendLine("            : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static float ReadFloat(Dictionary<string, string>? row, string field, float fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return row != null");
        text.AppendLine("            && row.TryGetValue(field, out string? value)");
        text.AppendLine("            && float.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out float parsed)");
        text.AppendLine("            ? parsed");
        text.AppendLine("            : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static bool ReadBool(Dictionary<string, string>? row, string field, bool fallback)");
        text.AppendLine("    {");
        text.AppendLine("        if (row == null || !row.TryGetValue(field, out string? value))");
        text.AppendLine("        {");
        text.AppendLine("            return fallback;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        return value.ToLowerInvariant() switch");
        text.AppendLine("        {");
        text.AppendLine("            \"1\" or \"true\" or \"yes\" => true,");
        text.AppendLine("            \"0\" or \"false\" or \"no\" => false,");
        text.AppendLine("            _ => fallback,");
        text.AppendLine("        };");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static string ReadString(Dictionary<string, string>? row, string field, string fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return row != null && row.TryGetValue(field, out string? value) && !string.IsNullOrEmpty(value)");
        text.AppendLine("            ? value");
        text.AppendLine("            : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static string[] SplitCsvLine(string line)");
        text.AppendLine("    {");
        text.AppendLine("        var values = new List<string>();");
        text.AppendLine("        var current = new System.Text.StringBuilder();");
        text.AppendLine("        bool inQuote = false;");
        text.AppendLine("        for (int index = 0; index < line.Length; index += 1)");
        text.AppendLine("        {");
        text.AppendLine("            char ch = line[index];");
        text.AppendLine("            if (ch == '\"')");
        text.AppendLine("            {");
        text.AppendLine("                if (inQuote && index + 1 < line.Length && line[index + 1] == '\"')");
        text.AppendLine("                {");
        text.AppendLine("                    current.Append('\"');");
        text.AppendLine("                    index += 1;");
        text.AppendLine("                }");
        text.AppendLine("                else");
        text.AppendLine("                {");
        text.AppendLine("                    inQuote = !inQuote;");
        text.AppendLine("                }");
        text.AppendLine("                continue;");
        text.AppendLine("            }");
        text.AppendLine("            if (ch == ',' && !inQuote)");
        text.AppendLine("            {");
        text.AppendLine("                values.Add(current.ToString());");
        text.AppendLine("                current.Clear();");
        text.AppendLine("                continue;");
        text.AppendLine("            }");
        text.AppendLine("            current.Append(ch);");
        text.AppendLine("        }");
        text.AppendLine("        values.Add(current.ToString());");
        text.AppendLine("        return values.ToArray();");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static string NormalizeHeader(string header, int index)");
        text.AppendLine("    {");
        text.AppendLine("        return index == 0 && header.Length > 0 && header[0] == '\\ufeff'");
        text.AppendLine("            ? header[1..]");
        text.AppendLine("            : header;");
        text.AppendLine("    }");
    }

    private static string Pascal(string value)
    {
        var text = new StringBuilder();
        foreach (var part in value.Split('_', StringSplitOptions.RemoveEmptyEntries))
        {
            text.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
            {
                text.Append(part[1..].ToLowerInvariant());
            }
        }
        return text.Length == 0 ? "Value" : text.ToString();
    }

    private static string ResourcePath(string root, string fullPath)
    {
        var relative = Path.GetRelativePath(root, fullPath).Replace('\\', '/');
        return $"res://{relative}";
    }

    private static string EscapeCs(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private sealed record ConfigRoot(
        string Name,
        ProtoMessage Message,
        bool IsJson,
        string SourcePath,
        string PackPath
    );

    public static void Check(string root, FwConfig config)
    {
        var schemaDir = config.ConfigSchemaDir(root);
        var dataDir = config.ConfigDataDir(root);
        if (!Directory.Exists(schemaDir))
        {
            throw new DirectoryNotFoundException($"config schema dir not found: {schemaDir}");
        }
        if (!Directory.Exists(dataDir))
        {
            throw new DirectoryNotFoundException($"config data dir not found: {dataDir}");
        }

        var schema = ProtoSchema.ParseFiles(Directory.GetFiles(schemaDir, "*.proto").OrderBy(item => item, StringComparer.Ordinal));
        var roots = schema.Messages.Values
            .Where(item => item.Name.EndsWith("Config", StringComparison.Ordinal))
            .OrderBy(item => item.Name, StringComparer.Ordinal)
            .ToArray();
        if (roots.Length == 0)
        {
            throw new InvalidOperationException($"config schema has no *Config messages: {schemaDir}");
        }

        foreach (var message in roots)
        {
            CheckConfigData(dataDir, message);
        }

        Console.WriteLine($"config check ok: {schemaDir}, {dataDir}");
    }

    public static void Pack(string root, FwConfig config)
    {
        var schemaDir = config.ConfigSchemaDir(root);
        var dataDir = config.ConfigDataDir(root);
        var packDir = config.ConfigPackDir(root);
        if (!Directory.Exists(schemaDir))
        {
            throw new DirectoryNotFoundException($"config schema dir not found: {schemaDir}");
        }
        if (!Directory.Exists(dataDir))
        {
            throw new DirectoryNotFoundException($"config data dir not found: {dataDir}");
        }

        var schema = ProtoSchema.ParseFiles(Directory.GetFiles(schemaDir, "*.proto").OrderBy(item => item, StringComparer.Ordinal));
        var roots = schema.Messages.Values
            .Where(item => item.Name.EndsWith("Config", StringComparison.Ordinal))
            .Where(item => item.Name != "GameConfig" || HasConfigData(dataDir, "game"))
            .OrderBy(item => TextUtil.Snake(item.Name[..^"Config".Length]), StringComparer.Ordinal)
            .ToArray();
        if (roots.Length == 0)
        {
            throw new InvalidOperationException($"config schema has no packable *Config messages: {schemaDir}");
        }

        Directory.CreateDirectory(packDir);
        foreach (var message in roots)
        {
            var rootName = TextUtil.Snake(message.Name[..^"Config".Length]);
            var entries = PackConfigData(dataDir, schema, message, rootName);
            var output = Path.Combine(packDir, $"{rootName}.bin");
            WriteConfigPack(output, entries);
            Console.WriteLine($"packed config {rootName}: {output}");
        }
    }

    private static bool HasConfigData(string dataDir, string rootName)
    {
        return File.Exists(Path.Combine(dataDir, $"{rootName}.csv.txt"))
            || File.Exists(Path.Combine(dataDir, $"{rootName}.json"));
    }

    private static List<Dictionary<string, object?>> PackConfigData(
        string dataDir,
        ProtoSchema schema,
        ProtoMessage message,
        string rootName
    )
    {
        var csvPath = Path.Combine(dataDir, $"{rootName}.csv.txt");
        if (File.Exists(csvPath))
        {
            return PackCsvConfig(csvPath, schema, message, rootName);
        }

        var jsonPath = Path.Combine(dataDir, $"{rootName}.json");
        if (File.Exists(jsonPath))
        {
            return PackJsonConfig(jsonPath, schema, message, rootName);
        }

        throw new FileNotFoundException($"missing config data for {message.Name}: {csvPath} or {jsonPath}");
    }

    private static List<Dictionary<string, object?>> PackCsvConfig(
        string path,
        ProtoSchema schema,
        ProtoMessage message,
        string rootName
    )
    {
        var lines = File.ReadAllLines(path, Encoding.UTF8)
            .Select(item => item.Trim())
            .Where(item => item.Length > 0)
            .ToArray();
        if (lines.Length == 0)
        {
            throw new InvalidOperationException($"{rootName} config is empty: {path}");
        }

        var headers = SplitCsvLine(lines[0]);
        var entries = new List<Dictionary<string, object?>>();
        for (var lineIndex = 1; lineIndex < lines.Length; lineIndex++)
        {
            var values = SplitCsvLine(lines[lineIndex]);
            var row = new Dictionary<string, string>(StringComparer.Ordinal);
            for (var index = 0; index < Math.Min(headers.Length, values.Length); index++)
            {
                row[headers[index]] = values[index];
            }

            if (!row.TryGetValue("key", out var key) || string.IsNullOrEmpty(key))
            {
                throw new InvalidOperationException($"{rootName} config missing key at line {lineIndex + 1}: {path}");
            }

            entries.Add(new Dictionary<string, object?>
            {
                ["key"] = key,
                ["value"] = PackCsvMessage(row, schema, message, rootName),
            });
        }

        return entries;
    }

    private static Dictionary<string, object?> PackCsvMessage(
        IReadOnlyDictionary<string, string> row,
        ProtoSchema schema,
        ProtoMessage message,
        string ctx
    )
    {
        var value = new Dictionary<string, object?>(StringComparer.Ordinal);
        foreach (var field in message.Fields)
        {
            if (!row.TryGetValue(field.Name, out var raw) || string.IsNullOrWhiteSpace(raw))
            {
                continue;
            }
            if (field.IsRepeated)
            {
                throw new InvalidOperationException($"{ctx}.{field.Name} repeated field cannot be packed from csv text");
            }
            value[field.Name] = PackScalarOrReference(raw, schema, field);
        }
        return value;
    }

    private static List<Dictionary<string, object?>> PackJsonConfig(
        string path,
        ProtoSchema schema,
        ProtoMessage message,
        string rootName
    )
    {
        using var document = JsonDocument.Parse(File.ReadAllText(path, Encoding.UTF8));
        if (document.RootElement.ValueKind != JsonValueKind.Array)
        {
            throw new InvalidOperationException($"{rootName} config must be a json array: {path}");
        }

        var entries = new List<Dictionary<string, object?>>();
        var index = 0;
        foreach (var item in document.RootElement.EnumerateArray())
        {
            var ctx = $"{rootName}[{index}]";
            if (item.ValueKind != JsonValueKind.Object)
            {
                throw new InvalidOperationException($"{ctx} config item must be object: {path}");
            }
            if (!item.TryGetProperty("key", out var keyElement))
            {
                throw new InvalidOperationException($"{ctx} config item missing key: {path}");
            }

            entries.Add(new Dictionary<string, object?>
            {
                ["key"] = PackJsonScalar(keyElement, "string", $"{ctx}.key"),
                ["value"] = PackJsonMessage(item, schema, message, ctx),
            });
            index++;
        }

        return entries;
    }

    private static Dictionary<string, object?> PackJsonMessage(
        JsonElement source,
        ProtoSchema schema,
        ProtoMessage message,
        string ctx
    )
    {
        var value = new Dictionary<string, object?>(StringComparer.Ordinal);
        foreach (var field in message.Fields)
        {
            if (!source.TryGetProperty(field.Name, out var item))
            {
                continue;
            }
            value[field.Name] = PackJsonField(item, schema, field, $"{ctx}.{field.Name}");
        }
        return value;
    }

    private static object? PackJsonField(JsonElement item, ProtoSchema schema, ProtoField field, string ctx)
    {
        if (field.IsRepeated)
        {
            if (item.ValueKind != JsonValueKind.Array)
            {
                throw new InvalidOperationException($"{ctx} must be array");
            }
            var values = new List<object?>();
            foreach (var child in item.EnumerateArray())
            {
                values.Add(PackJsonItem(child, schema, field.Type, ctx));
            }
            return values;
        }

        return PackJsonItem(item, schema, field.Type, ctx);
    }

    private static object? PackJsonItem(JsonElement item, ProtoSchema schema, string type, string ctx)
    {
        if (schema.Messages.TryGetValue(type, out var message) && type != "Fixed32")
        {
            if (item.ValueKind == JsonValueKind.String)
            {
                return item.GetString() ?? "";
            }
            if (item.ValueKind != JsonValueKind.Object)
            {
                throw new InvalidOperationException($"{ctx} must be object or config key");
            }
            return PackJsonMessage(item, schema, message, ctx);
        }

        return PackJsonScalar(item, type, ctx);
    }

    private static object? PackScalarOrReference(string raw, ProtoSchema schema, ProtoField field)
    {
        if (schema.Messages.ContainsKey(field.Type) && field.Type != "Fixed32")
        {
            return raw;
        }
        return PackStringScalar(raw, field.Type);
    }

    private static object? PackJsonScalar(JsonElement item, string type, string ctx)
    {
        return type switch
        {
            "string" => item.ValueKind == JsonValueKind.String ? item.GetString() ?? "" : item.ToString(),
            "bool" => item.ValueKind switch
            {
                JsonValueKind.True => true,
                JsonValueKind.False => false,
                JsonValueKind.String => PackStringBool(item.GetString() ?? "", ctx),
                _ => throw new InvalidOperationException($"{ctx} must be bool"),
            },
            "float" or "double" => PackJsonDouble(item, ctx),
            "Fixed32" => PackFixed(PackJsonDouble(item, ctx)),
            "uint64" => item.ValueKind == JsonValueKind.String
                ? ulong.Parse(item.GetString() ?? "0", CultureInfo.InvariantCulture)
                : item.GetUInt64(),
            "uint32" => item.ValueKind == JsonValueKind.String
                ? int.Parse(item.GetString() ?? "0", CultureInfo.InvariantCulture)
                : item.GetInt32(),
            "int64" or "sint64" => item.ValueKind == JsonValueKind.String
                ? long.Parse(item.GetString() ?? "0", CultureInfo.InvariantCulture)
                : item.GetInt64(),
            "int32" or "sint32" => item.ValueKind == JsonValueKind.String
                ? int.Parse(item.GetString() ?? "0", CultureInfo.InvariantCulture)
                : item.GetInt32(),
            _ => item.ValueKind == JsonValueKind.String ? item.GetString() ?? "" : item.ToString(),
        };
    }

    private static object? PackStringScalar(string raw, string type)
    {
        return type switch
        {
            "string" => raw,
            "bool" => PackStringBool(raw, type),
            "float" or "double" => double.Parse(raw, CultureInfo.InvariantCulture),
            "Fixed32" => PackFixed(double.Parse(raw, CultureInfo.InvariantCulture)),
            "uint64" => ulong.Parse(raw, CultureInfo.InvariantCulture),
            "uint32" => int.Parse(raw, CultureInfo.InvariantCulture),
            "int64" or "sint64" => long.Parse(raw, CultureInfo.InvariantCulture),
            "int32" or "sint32" => int.Parse(raw, CultureInfo.InvariantCulture),
            _ => raw,
        };
    }

    private static bool PackStringBool(string raw, string ctx)
    {
        return raw.Trim().ToLowerInvariant() switch
        {
            "1" or "true" or "yes" => true,
            "0" or "false" or "no" => false,
            _ => throw new InvalidOperationException($"{ctx} must be bool-compatible text"),
        };
    }

    private static double PackJsonDouble(JsonElement item, string ctx)
    {
        return item.ValueKind == JsonValueKind.String
            ? double.Parse(item.GetString() ?? "0", CultureInfo.InvariantCulture)
            : item.ValueKind == JsonValueKind.Number
                ? item.GetDouble()
                : throw new InvalidOperationException($"{ctx} must be numeric");
    }

    private static int PackFixed(double value)
    {
        return (int)Math.Round(value * 256.0, MidpointRounding.AwayFromZero);
    }

    private static void WriteConfigPack(string output, object entries)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(output) ?? ".");
        var bytes = JsonSerializer.SerializeToUtf8Bytes(entries);
        using var stream = File.Create(output);
        stream.Write(new byte[] { 87, 67, 70, 71 });
        stream.Write(bytes);
    }

    private static void CheckConfigData(string dataDir, ProtoMessage message)
    {
        var rootName = TextUtil.Snake(message.Name[..^"Config".Length]);
        var csvPath = Path.Combine(dataDir, $"{rootName}.csv.txt");
        var jsonPath = Path.Combine(dataDir, $"{rootName}.json");
        if (File.Exists(csvPath))
        {
            CheckCsvConfig(csvPath, message, rootName);
            return;
        }
        if (File.Exists(jsonPath))
        {
            CheckJsonConfig(jsonPath, message, rootName);
            return;
        }

        throw new FileNotFoundException($"missing config data for {message.Name}: {csvPath} or {jsonPath}");
    }

    private static void CheckCsvConfig(string path, ProtoMessage message, string rootName)
    {
        var lines = File.ReadAllLines(path, Encoding.UTF8)
            .Select(item => item.Trim())
            .Where(item => item.Length > 0)
            .ToArray();
        if (lines.Length == 0)
        {
            throw new InvalidOperationException($"{rootName} config is empty: {path}");
        }

        var headers = SplitCsvLine(lines[0]);
        var headerSet = new HashSet<string>(headers, StringComparer.Ordinal);
        if (!headerSet.Contains("key"))
        {
            throw new InvalidOperationException($"{rootName} config missing key column: {path}");
        }

        var allowedFields = message.Fields.Select(item => item.Name)
            .Append("key")
            .ToHashSet(StringComparer.Ordinal);
        foreach (var header in headers)
        {
            if (!allowedFields.Contains(header))
            {
                throw new InvalidOperationException($"{rootName} config unknown column {header}: {path}");
            }
        }

        foreach (var field in message.Fields)
        {
            if (!headerSet.Contains(field.Name))
            {
                throw new InvalidOperationException($"{rootName} config missing column {field.Name}: {path}");
            }
        }

        var keyIndex = Array.IndexOf(headers, "key");
        var hasDefault = false;
        for (var lineIndex = 1; lineIndex < lines.Length; lineIndex++)
        {
            var values = SplitCsvLine(lines[lineIndex]);
            if (keyIndex < values.Length && values[keyIndex] == "default")
            {
                hasDefault = true;
                break;
            }
        }
        if (!hasDefault)
        {
            throw new InvalidOperationException($"{rootName} config missing default row: {path}");
        }
    }

    private static void CheckJsonConfig(string path, ProtoMessage message, string rootName)
    {
        using var document = JsonDocument.Parse(File.ReadAllText(path, Encoding.UTF8));
        if (document.RootElement.ValueKind != JsonValueKind.Array)
        {
            throw new InvalidOperationException($"{rootName} config must be a json array: {path}");
        }

        var allowedFields = message.Fields.Select(item => item.Name)
            .Append("key")
            .ToHashSet(StringComparer.Ordinal);
        var hasDefault = false;
        foreach (var item in document.RootElement.EnumerateArray())
        {
            if (item.ValueKind != JsonValueKind.Object)
            {
                throw new InvalidOperationException($"{rootName} config item must be object: {path}");
            }

            if (!item.TryGetProperty("key", out var key))
            {
                throw new InvalidOperationException($"{rootName} config item missing key: {path}");
            }
            if (key.ValueKind == JsonValueKind.String && key.GetString() == "default")
            {
                hasDefault = true;
            }

            foreach (var property in item.EnumerateObject())
            {
                if (!allowedFields.Contains(property.Name))
                {
                    throw new InvalidOperationException($"{rootName} config unknown field {property.Name}: {path}");
                }
            }
        }
        if (!hasDefault)
        {
            throw new InvalidOperationException($"{rootName} config missing default item: {path}");
        }
    }

    private static string[] SplitCsvLine(string line)
    {
        var values = new List<string>();
        var current = new StringBuilder();
        var inQuote = false;
        for (var index = 0; index < line.Length; index += 1)
        {
            var ch = line[index];
            if (ch == '"')
            {
                if (inQuote && index + 1 < line.Length && line[index + 1] == '"')
                {
                    current.Append('"');
                    index += 1;
                }
                else
                {
                    inQuote = !inQuote;
                }
                continue;
            }
            if (ch == ',' && !inQuote)
            {
                values.Add(NormalizeHeader(current.ToString(), values.Count));
                current.Clear();
                continue;
            }
            current.Append(ch);
        }
        values.Add(NormalizeHeader(current.ToString(), values.Count));
        return values.ToArray();
    }

    private static string NormalizeHeader(string value, int index)
    {
        return index == 0 && value.Length > 0 && value[0] == '\ufeff'
            ? value[1..]
            : value;
    }
}
