using System.Text;
using System.Text.Json;

static class ConfigGen
{
    public static void Generate(string root, FwConfig config)
    {
        GenerateCSharp(root, config);
        var output = config.ConfigGdPath(root);
        if (File.Exists(output))
        {
            Console.WriteLine($"kept existing config gd script: {output}");
            return;
        }

        var schemaDir = config.ConfigSchemaDir(root);
        var schema = ProtoSchema.ParseFiles(Directory.Exists(schemaDir)
            ? Directory.GetFiles(schemaDir, "*.proto").OrderBy(item => item, StringComparer.Ordinal)
            : []);
        var rootNamespace = TextUtil.PascalName(config.ProjectName());

        var roots = schema.Messages.Values
            .Where(item => item.Name.EndsWith("Config", StringComparison.Ordinal))
            .Select(item => TextUtil.Snake(item.Name[..^"Config".Length]))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(item => item, StringComparer.Ordinal)
            .ToArray();

        var text = new StringBuilder();
        text.AppendLine("# This file is generated by fwgen. Do not edit manually.");
        text.AppendLine("extends RefCounted");
        text.AppendLine("class_name _config");
        text.AppendLine();
        text.AppendLine("static func _fallback() -> Dictionary:");
        text.AppendLine("\treturn {}");
        text.AppendLine();
        foreach (var rootName in roots)
        {
            text.AppendLine($"static func {rootName}_default_config() -> Dictionary:");
            text.AppendLine("\treturn _fallback()");
            text.AppendLine();
        }

        TextUtil.WriteText(output, text.ToString());
        Console.WriteLine($"generated minimal config gd script: {output}");
    }

    private static void GenerateCSharp(string root, FwConfig config)
    {
        var schemaDir = config.ConfigSchemaDir(root);
        var output = config.ConfigContractCsPath(root);
        var schema = ProtoSchema.ParseFiles(Directory.Exists(schemaDir)
            ? Directory.GetFiles(schemaDir, "*.proto").OrderBy(item => item, StringComparer.Ordinal)
            : []);
        var rootNamespace = TextUtil.PascalName(config.ProjectName());

        var messages = schema.Messages.Values
            .Where(item => item.Name != "Fixed32")
            .OrderBy(item => item.Name == "GameConfig" ? "CoreConfig" : item.Name, StringComparer.Ordinal)
            .ToArray();

        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen config. Do not edit.");
        text.AppendLine("using System.Collections.Generic;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Core;");
        text.AppendLine();
        RenderConfigFields(text, schema);
        text.AppendLine();
        foreach (var message in messages)
        {
            var className = message.Name == "GameConfig" ? "CoreConfig" : message.Name;
            text.AppendLine($"public sealed class {className}");
            text.AppendLine("{");
            foreach (var field in message.Fields)
            {
                text.AppendLine($"    public {CsConfigType(field.Type, field.IsRepeated)} {Pascal(field.Name)} {{ get; init; }}{CsConfigInit(field, schema)}");
            }
            text.AppendLine("}");
            text.AppendLine();
        }

        TextUtil.WriteText(output, text.ToString());
        Console.WriteLine($"generated config csharp contract: {output}");
    }

    private static void RenderConfigFields(StringBuilder text, ProtoSchema schema)
    {
        var fields = schema.Messages.Values
            .SelectMany(message => message.Fields)
            .Select(field => field.Name)
            .Append("key")
            .Distinct(StringComparer.Ordinal)
            .OrderBy(item => item, StringComparer.Ordinal)
            .ToArray();

        text.AppendLine("public static class ConfigField");
        text.AppendLine("{");
        foreach (var field in fields)
        {
            text.AppendLine($"    public const string {Pascal(field)} = \"{field}\";");
        }
        text.AppendLine("}");
    }

    private static string CsConfigType(string type, bool repeated)
    {
        var itemType = type switch
        {
            "string" => "string",
            "bool" => "bool",
            "float" or "double" or "Fixed32" => "float",
            "uint32" => "int",
            "uint64" => "ulong",
            "int32" or "sint32" => "int",
            "int64" or "sint64" => "long",
            _ => type == "GameConfig" ? "CoreConfig" : type,
        };
        return repeated ? $"List<{itemType}>" : itemType;
    }

    private static string CsConfigInit(ProtoField field, ProtoSchema schema)
    {
        if (field.IsRepeated)
        {
            return " = new();";
        }
        if (field.Type == "string")
        {
            return " = \"\";";
        }
        if (schema.Messages.ContainsKey(field.Type) && field.Type != "Fixed32")
        {
            return " = new();";
        }
        return "";
    }

    private static string Pascal(string value)
    {
        var text = new StringBuilder();
        foreach (var part in value.Split('_', StringSplitOptions.RemoveEmptyEntries))
        {
            text.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
            {
                text.Append(part[1..].ToLowerInvariant());
            }
        }
        return text.Length == 0 ? "Value" : text.ToString();
    }

    public static void Check(string root, FwConfig config)
    {
        var schemaDir = config.ConfigSchemaDir(root);
        var dataDir = config.ConfigDataDir(root);
        if (!Directory.Exists(schemaDir))
        {
            throw new DirectoryNotFoundException($"config schema dir not found: {schemaDir}");
        }
        if (!Directory.Exists(dataDir))
        {
            throw new DirectoryNotFoundException($"config data dir not found: {dataDir}");
        }

        var schema = ProtoSchema.ParseFiles(Directory.GetFiles(schemaDir, "*.proto").OrderBy(item => item, StringComparer.Ordinal));
        var roots = schema.Messages.Values
            .Where(item => item.Name.EndsWith("Config", StringComparison.Ordinal))
            .OrderBy(item => item.Name, StringComparer.Ordinal)
            .ToArray();
        if (roots.Length == 0)
        {
            throw new InvalidOperationException($"config schema has no *Config messages: {schemaDir}");
        }

        foreach (var message in roots)
        {
            CheckConfigData(dataDir, message);
        }

        Console.WriteLine($"config check ok: {schemaDir}, {dataDir}");
    }

    public static void Pack(string root, FwConfig config)
    {
        var packDir = config.ConfigPackDir(root);
        Directory.CreateDirectory(packDir);
        Console.WriteLine($"prepared config pack dir: {packDir}");
    }

    private static void CheckConfigData(string dataDir, ProtoMessage message)
    {
        var rootName = TextUtil.Snake(message.Name[..^"Config".Length]);
        var csvPath = Path.Combine(dataDir, $"{rootName}.csv.txt");
        var jsonPath = Path.Combine(dataDir, $"{rootName}.json");
        if (File.Exists(csvPath))
        {
            CheckCsvConfig(csvPath, message, rootName);
            return;
        }
        if (File.Exists(jsonPath))
        {
            CheckJsonConfig(jsonPath, message, rootName);
            return;
        }

        throw new FileNotFoundException($"missing config data for {message.Name}: {csvPath} or {jsonPath}");
    }

    private static void CheckCsvConfig(string path, ProtoMessage message, string rootName)
    {
        var lines = File.ReadAllLines(path, Encoding.UTF8)
            .Select(item => item.Trim())
            .Where(item => item.Length > 0)
            .ToArray();
        if (lines.Length == 0)
        {
            throw new InvalidOperationException($"{rootName} config is empty: {path}");
        }

        var headers = SplitCsvLine(lines[0]);
        var headerSet = new HashSet<string>(headers, StringComparer.Ordinal);
        if (!headerSet.Contains("key"))
        {
            throw new InvalidOperationException($"{rootName} config missing key column: {path}");
        }

        var allowedFields = message.Fields.Select(item => item.Name)
            .Append("key")
            .ToHashSet(StringComparer.Ordinal);
        foreach (var header in headers)
        {
            if (!allowedFields.Contains(header))
            {
                throw new InvalidOperationException($"{rootName} config unknown column {header}: {path}");
            }
        }

        foreach (var field in message.Fields)
        {
            if (!headerSet.Contains(field.Name))
            {
                throw new InvalidOperationException($"{rootName} config missing column {field.Name}: {path}");
            }
        }

        var keyIndex = Array.IndexOf(headers, "key");
        var hasDefault = false;
        for (var lineIndex = 1; lineIndex < lines.Length; lineIndex++)
        {
            var values = SplitCsvLine(lines[lineIndex]);
            if (keyIndex < values.Length && values[keyIndex] == "default")
            {
                hasDefault = true;
                break;
            }
        }
        if (!hasDefault)
        {
            throw new InvalidOperationException($"{rootName} config missing default row: {path}");
        }
    }

    private static void CheckJsonConfig(string path, ProtoMessage message, string rootName)
    {
        using var document = JsonDocument.Parse(File.ReadAllText(path, Encoding.UTF8));
        if (document.RootElement.ValueKind != JsonValueKind.Array)
        {
            throw new InvalidOperationException($"{rootName} config must be a json array: {path}");
        }

        var allowedFields = message.Fields.Select(item => item.Name)
            .Append("key")
            .ToHashSet(StringComparer.Ordinal);
        var hasDefault = false;
        foreach (var item in document.RootElement.EnumerateArray())
        {
            if (item.ValueKind != JsonValueKind.Object)
            {
                throw new InvalidOperationException($"{rootName} config item must be object: {path}");
            }

            if (!item.TryGetProperty("key", out var key))
            {
                throw new InvalidOperationException($"{rootName} config item missing key: {path}");
            }
            if (key.ValueKind == JsonValueKind.String && key.GetString() == "default")
            {
                hasDefault = true;
            }

            foreach (var property in item.EnumerateObject())
            {
                if (!allowedFields.Contains(property.Name))
                {
                    throw new InvalidOperationException($"{rootName} config unknown field {property.Name}: {path}");
                }
            }
        }
        if (!hasDefault)
        {
            throw new InvalidOperationException($"{rootName} config missing default item: {path}");
        }
    }

    private static string[] SplitCsvLine(string line)
    {
        var values = new List<string>();
        var current = new StringBuilder();
        var inQuote = false;
        for (var index = 0; index < line.Length; index += 1)
        {
            var ch = line[index];
            if (ch == '"')
            {
                if (inQuote && index + 1 < line.Length && line[index + 1] == '"')
                {
                    current.Append('"');
                    index += 1;
                }
                else
                {
                    inQuote = !inQuote;
                }
                continue;
            }
            if (ch == ',' && !inQuote)
            {
                values.Add(NormalizeHeader(current.ToString(), values.Count));
                current.Clear();
                continue;
            }
            current.Append(ch);
        }
        values.Add(NormalizeHeader(current.ToString(), values.Count));
        return values.ToArray();
    }

    private static string NormalizeHeader(string value, int index)
    {
        return index == 0 && value.Length > 0 && value[0] == '\ufeff'
            ? value[1..]
            : value;
    }
}
