using System.Text;

static class ConfigGen
{
    public static void Generate(string root, FwConfig config)
    {
        GenerateCSharp(root, config);
        var output = config.PathValue(root, "gen", "config_gd", "scripts/gen/_config.gd");
        if (File.Exists(output))
        {
            Console.WriteLine($"kept existing config gd script: {output}");
            return;
        }

        var schemaDir = config.PathValue(root, "schema", "config", "schema/config");
        var schema = ProtoSchema.ParseFiles(Directory.Exists(schemaDir)
            ? Directory.GetFiles(schemaDir, "*.proto").OrderBy(item => item, StringComparer.Ordinal)
            : []);
        var rootNamespace = TextUtil.PascalName(config.Value("project", "name", "Game"));

        var roots = schema.Messages.Values
            .Where(item => item.Name.EndsWith("Config", StringComparison.Ordinal))
            .Select(item => TextUtil.Snake(item.Name[..^"Config".Length]))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(item => item, StringComparer.Ordinal)
            .ToArray();

        var text = new StringBuilder();
        text.AppendLine("# This file is generated by fw_gen. Do not edit manually.");
        text.AppendLine("extends RefCounted");
        text.AppendLine("class_name _config");
        text.AppendLine();
        text.AppendLine("static func _fallback() -> Dictionary:");
        text.AppendLine("\treturn {}");
        text.AppendLine();
        foreach (var rootName in roots)
        {
            text.AppendLine($"static func {rootName}_default_config() -> Dictionary:");
            text.AppendLine("\treturn _fallback()");
            text.AppendLine();
        }

        TextUtil.WriteText(output, text.ToString());
        Console.WriteLine($"generated minimal config gd script: {output}");
    }

    private static void GenerateCSharp(string root, FwConfig config)
    {
        var schemaDir = config.PathValue(root, "schema", "config", "schema/config");
        var output = config.PathValue(root, "gen", "config_contract_cs", "csharp/core/config/config_contract.cs");
        var schema = ProtoSchema.ParseFiles(Directory.Exists(schemaDir)
            ? Directory.GetFiles(schemaDir, "*.proto").OrderBy(item => item, StringComparer.Ordinal)
            : []);
        var rootNamespace = TextUtil.PascalName(config.Value("project", "name", "Game"));

        var messages = schema.Messages.Values
            .Where(item => item.Name != "Fixed32")
            .OrderBy(item => item.Name == "GameConfig" ? "CoreConfig" : item.Name, StringComparer.Ordinal)
            .ToArray();

        var text = new StringBuilder();
        text.AppendLine("// @generated by fw_gen config. Do not edit.");
        text.AppendLine("using System.Collections.Generic;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Core;");
        text.AppendLine();
        RenderConfigFields(text, schema);
        text.AppendLine();
        foreach (var message in messages)
        {
            var className = message.Name == "GameConfig" ? "CoreConfig" : message.Name;
            text.AppendLine($"public sealed class {className}");
            text.AppendLine("{");
            foreach (var field in message.Fields)
            {
                text.AppendLine($"    public {CsConfigType(field.Type, field.IsRepeated)} {Pascal(field.Name)} {{ get; init; }}{CsConfigInit(field, schema)}");
            }
            text.AppendLine("}");
            text.AppendLine();
        }

        TextUtil.WriteText(output, text.ToString());
        Console.WriteLine($"generated config csharp contract: {output}");
    }

    private static void RenderConfigFields(StringBuilder text, ProtoSchema schema)
    {
        var fields = schema.Messages.Values
            .SelectMany(message => message.Fields)
            .Select(field => field.Name)
            .Append("key")
            .Distinct(StringComparer.Ordinal)
            .OrderBy(item => item, StringComparer.Ordinal)
            .ToArray();

        text.AppendLine("public static class ConfigField");
        text.AppendLine("{");
        foreach (var field in fields)
        {
            text.AppendLine($"    public const string {Pascal(field)} = \"{field}\";");
        }
        text.AppendLine("}");
    }

    private static string CsConfigType(string type, bool repeated)
    {
        var itemType = type switch
        {
            "string" => "string",
            "bool" => "bool",
            "float" or "double" or "Fixed32" => "float",
            "uint32" => "int",
            "uint64" => "ulong",
            "int32" or "sint32" => "int",
            "int64" or "sint64" => "long",
            _ => type == "GameConfig" ? "CoreConfig" : type,
        };
        return repeated ? $"List<{itemType}>" : itemType;
    }

    private static string CsConfigInit(ProtoField field, ProtoSchema schema)
    {
        if (field.IsRepeated)
        {
            return " = new();";
        }
        if (field.Type == "string")
        {
            return " = \"\";";
        }
        if (schema.Messages.ContainsKey(field.Type) && field.Type != "Fixed32")
        {
            return " = new();";
        }
        return "";
    }

    private static string Pascal(string value)
    {
        var text = new StringBuilder();
        foreach (var part in value.Split('_', StringSplitOptions.RemoveEmptyEntries))
        {
            text.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
            {
                text.Append(part[1..].ToLowerInvariant());
            }
        }
        return text.Length == 0 ? "Value" : text.ToString();
    }

    public static void Check(string root, FwConfig config)
    {
        var schemaDir = config.PathValue(root, "schema", "config", "schema/config");
        var dataDir = config.PathValue(root, "schema", "data_config", "data/config");
        if (!Directory.Exists(schemaDir))
        {
            throw new DirectoryNotFoundException($"config schema dir not found: {schemaDir}");
        }
        if (!Directory.Exists(dataDir))
        {
            throw new DirectoryNotFoundException($"config data dir not found: {dataDir}");
        }
        Console.WriteLine($"config paths ok: {schemaDir}, {dataDir}");
    }

    public static void Pack(string root, FwConfig config)
    {
        var packDir = config.PathValue(root, "gen", "config_pack_dir", "data/gen/config");
        Directory.CreateDirectory(packDir);
        Console.WriteLine($"prepared config pack dir: {packDir}");
    }
}
