using System.Text;

static class CoreSystemGen
{
    public static void Generate(string root, FwConfig config, RuntimeSystemSchema schema)
    {
        var output = config.CoreSystemsCsPath(root);
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        TextUtil.WriteText(output, Render(schema, rootNamespace));
        Console.WriteLine($"generated core systems: {output}");
    }

    private static string Render(RuntimeSystemSchema schema, string rootNamespace)
    {
        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen system. Do not edit.");
        text.AppendLine("using Fw.Rt.Systems;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Core;");
        text.AppendLine();
        text.AppendLine("internal static class CoreSystems");
        text.AppendLine("{");
        foreach (var system in schema.Systems)
        {
            text.AppendLine($"    public const string Id{TextUtil.PascalName(system.Id)} = \"{system.Id}\";");
        }
        text.AppendLine();
        foreach (var phase in schema.PhaseOrder)
        {
            text.AppendLine($"    public const string Phase{TextUtil.PascalName(phase)} = \"{phase}\";");
        }
        text.AppendLine();
        text.AppendLine("    public static readonly string[] PhaseOrder =");
        text.AppendLine("    [");
        foreach (var phase in schema.PhaseOrder)
        {
            text.AppendLine($"        Phase{TextUtil.PascalName(phase)},");
        }
        text.AppendLine("    ];");
        text.AppendLine();
        text.AppendLine("    public static void Setup(SystemRuntime runtime, CoreContext context)");
        text.AppendLine("    {");
        text.AppendLine("        runtime.SetPhaseOrder(PhaseOrder);");
        foreach (var system in schema.Systems)
        {
            text.AppendLine($"        runtime.Add(Id{TextUtil.PascalName(system.Id)}, new {system.Type}(), context, Phase{TextUtil.PascalName(system.Phase)});");
        }
        text.AppendLine("    }");
        text.AppendLine("}");
        return text.ToString();
    }
}
