using System.Text;

static class CoreSystemGen
{
    private sealed record CoreSystemSchema(List<string> PhaseOrder, List<CoreSystemNode> Systems);
    private sealed record CoreSystemNode(string Id, string Phase, string Type);

    public static void Generate(string root, FwConfig config)
    {
        var schemaPath = config.PathValue(root, "schema", "core_system", "schema/core_system.toml");
        if (!File.Exists(schemaPath))
        {
            return;
        }

        var output = config.PathValue(root, "gen", "core_systems_cs", "csharp/core/core_systems.cs");
        var schema = Parse(schemaPath);
        var rootNamespace = TextUtil.PascalName(config.Value("project", "name", "Game"));
        TextUtil.WriteText(output, Render(schema, rootNamespace));
        Console.WriteLine($"generated core system registrations: {output}");
    }

    private static CoreSystemSchema Parse(string path)
    {
        var phaseOrder = new List<string>();
        var systems = new List<CoreSystemNode>();
        var values = new Dictionary<string, Dictionary<string, string>>(StringComparer.Ordinal);
        var section = "";

        var lines = File.ReadAllLines(path, Encoding.UTF8);
        for (var index = 0; index < lines.Length; index++)
        {
            var lineNo = index + 1;
            var line = StripComment(lines[index]).Trim();
            if (line.Length == 0)
            {
                continue;
            }

            if (line.StartsWith('[') && line.EndsWith(']'))
            {
                section = line.Trim('[', ']').Trim();
                if (section.Length == 0)
                {
                    throw new InvalidOperationException($"{path}:{lineNo} section cannot be empty");
                }
                values.TryAdd(section, new Dictionary<string, string>(StringComparer.Ordinal));
                continue;
            }

            var parts = line.Split('=', 2);
            if (parts.Length != 2 || section.Length == 0)
            {
                throw new InvalidOperationException($"{path}:{lineNo} expected `field = \"value\"` under a section");
            }

            var field = parts[0].Trim();
            var value = parts[1].Trim();
            if (section == "phases" && field == "order")
            {
                phaseOrder = ParseQuotedList(value, path, lineNo);
                continue;
            }

            values[section][field] = ParseQuotedRaw(value, path, lineNo);
        }

        foreach (var (id, fields) in values)
        {
            if (id == "phases")
            {
                continue;
            }
            if (!fields.TryGetValue("phase", out var phase) || phase.Length == 0)
            {
                throw new InvalidOperationException($"{path}: core system `{id}` needs phase");
            }
            if (!fields.TryGetValue("type", out var type) || type.Length == 0)
            {
                throw new InvalidOperationException($"{path}: core system `{id}` needs type");
            }
            systems.Add(new CoreSystemNode(id, phase, type));
        }

        if (systems.Count == 0)
        {
            throw new InvalidOperationException($"{path}: core system schema is empty");
        }
        return new CoreSystemSchema(phaseOrder, systems);
    }

    private static string Render(CoreSystemSchema schema, string rootNamespace)
    {
        var text = new StringBuilder();
        text.AppendLine("// @generated by fw_gen system. Do not edit.");
        text.AppendLine("using Fw.Rt.Systems;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Core;");
        text.AppendLine();
        text.AppendLine("internal static class CoreSystems");
        text.AppendLine("{");
        foreach (var system in schema.Systems)
        {
            text.AppendLine($"    public const string Id{TextUtil.PascalName(system.Id)} = \"{system.Id}\";");
        }
        if (schema.Systems.Count > 0)
        {
            text.AppendLine();
        }
        foreach (var phase in schema.PhaseOrder)
        {
            text.AppendLine($"    public const string Phase{TextUtil.PascalName(phase)} = \"{phase}\";");
        }
        if (schema.PhaseOrder.Count > 0)
        {
            text.AppendLine();
        }
        text.AppendLine("    public static readonly string[] PhaseOrder =");
        text.AppendLine("    [");
        foreach (var phase in schema.PhaseOrder)
        {
            text.AppendLine($"        Phase{TextUtil.PascalName(phase)},");
        }
        text.AppendLine("    ];");
        text.AppendLine();
        text.AppendLine("    public static void Register(SystemRuntime runtime, CoreContext context)");
        text.AppendLine("    {");
        text.AppendLine("        runtime.SetPhaseOrder(PhaseOrder);");
        foreach (var system in schema.Systems)
        {
            text.AppendLine($"        runtime.Add(Id{TextUtil.PascalName(system.Id)}, new {system.Type}(), context, Phase{TextUtil.PascalName(system.Phase)});");
        }
        text.AppendLine("    }");
        text.AppendLine("}");
        return text.ToString();
    }

    private static string StripComment(string line)
    {
        var inQuote = false;
        for (var i = 0; i < line.Length; i++)
        {
            if (line[i] == '"')
            {
                inQuote = !inQuote;
            }
            if (!inQuote && line[i] == '#')
            {
                return line[..i];
            }
        }
        return line;
    }

    private static string ParseQuotedRaw(string value, string path, int lineNo)
    {
        if (!value.StartsWith('"') || !value.EndsWith('"') || value.Length < 2)
        {
            throw new InvalidOperationException($"{path}:{lineNo} value must be quoted");
        }
        return value[1..^1];
    }

    private static List<string> ParseQuotedList(string value, string path, int lineNo)
    {
        if (!value.StartsWith('[') || !value.EndsWith(']'))
        {
            throw new InvalidOperationException($"{path}:{lineNo} expected quoted string array");
        }

        var inner = value[1..^1].Trim();
        if (inner.Length == 0)
        {
            return [];
        }

        var items = new List<string>();
        foreach (var rawPart in inner.Split(','))
        {
            items.Add(ParseQuotedRaw(rawPart.Trim(), path, lineNo));
        }
        return items;
    }
}
