using System.Text;

static class SystemGen
{
    public static void Generate(string root, FwConfig config, RuntimeSystemSchema schema)
    {
        var output = config.GodotSystemsGdPath(root);
        DeleteLegacyGraph(config.GodotGenDir(root));
        TextUtil.WriteText(output, RenderSystems(schema));
        Console.WriteLine($"generated godot systems: {output}");
    }

    private static void DeleteLegacyGraph(string godotGenDir)
    {
        DeleteIfExists(Path.Combine(godotGenDir, "_godot_system_graph.gd"));
        DeleteIfExists(Path.Combine(godotGenDir, "_godot_system_graph.gd.uid"));
    }

    private static void DeleteIfExists(string path)
    {
        if (File.Exists(path))
        {
            File.Delete(path);
        }
    }

    private static string RenderRefs(RuntimeSystemSchema model)
    {
        var entries = new List<string>();
        foreach (var system in model.Systems)
        {
            if (system.Refs.Count == 0)
            {
                entries.Add($"\t\t&\"{system.Id}\": {{}}");
                continue;
            }

            var refs = string.Join(",\n", system.Refs.Select(item => $"\t\t\t&\"{item.Field}\": &\"{item.Target}\""));
            entries.Add($"\t\t&\"{system.Id}\": {{\n{refs}\n\t\t}}");
        }

        return "static func refs() -> Dictionary:\n" +
               "\treturn {\n" +
               string.Join(",\n", entries) +
               "\n\t}\n";
    }

    private static string RenderPhaseOrder(RuntimeSystemSchema model)
    {
        return "static func phase_order() -> Array[StringName]:\n" +
               "\treturn [\n" +
               string.Join(",\n", model.PhaseOrder.Select(item => $"\t\t&\"{item}\"")) +
               "\n\t]";
    }

    private static string RenderSystems(RuntimeSystemSchema model)
    {
        var systems = model.Systems.Where(item => item.AutoGodot).ToArray();
        var text = new StringBuilder();
        text.AppendLine("# @generated by fwgen system. Do not edit.");
        text.AppendLine("class_name GodotSystems");
        text.AppendLine("extends RefCounted");
        text.AppendLine();
        text.AppendLine(RenderPhaseOrder(model));
        text.AppendLine();
        text.Append(RenderRefs(model));
        text.AppendLine();

        foreach (var system in systems)
        {
            var stem = TextUtil.PascalName(system.Id);
            text.AppendLine($"const {stem}SystemScript = preload(\"{EscapeGdString(system.Script)}\")");
            text.AppendLine($"const {stem}ContextScript = preload(\"{EscapeGdString(system.Context)}\")");
        }

        if (systems.Length > 0)
        {
            text.AppendLine();
        }
        text.AppendLine("static func create(mode: Variant) -> Dictionary:");
        text.AppendLine("\tvar entries: Dictionary = {}");
        foreach (var system in systems)
        {
            var stem = TextUtil.PascalName(system.Id);
            var local = TextUtil.Snake(system.Id);
            text.AppendLine($"\tvar {local}_system = {stem}SystemScript.new()");
            text.AppendLine($"\tvar {local}_context = {stem}ContextScript.new()");
            text.AppendLine($"\tif not mode.add_system(&\"{system.Id}\", {local}_system, {local}_context, &\"{system.Phase}\"):");
            text.AppendLine("\t\treturn {}");
            text.AppendLine($"\tentries[&\"{system.Id}\"] = {{");
            text.AppendLine($"\t\t\"system\": {local}_system,");
            text.AppendLine($"\t\t\"context\": {local}_context,");
            text.AppendLine("\t}");
        }
        text.AppendLine("\treturn entries");
        text.AppendLine();
        text.AppendLine();
        text.AppendLine("static func setup(mode: Variant) -> Dictionary:");
        text.AppendLine("\tvar entries: Dictionary = create(mode)");
        text.AppendLine("\tmode.set_system_phase_order(phase_order())");
        text.AppendLine("\tif not mode.bind_system_refs(refs()):");
        text.AppendLine("\t\treturn {}");
        text.AppendLine("\treturn entries");
        return text.ToString();
    }

    private static string EscapeGdString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
