; Minimal Godot project scaffold generated by fw.
config_version=5

[application]

config/name="__PROJECT_NAME_PASCAL__"
run/main_scene="res://scenes/app/main.tscn"
config/features=PackedStringArray("4.6", "C#")

[dotnet]

project/assembly_name="__PROJECT_NAME__"

[rendering]

renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
