(function () {
  'use strict';
  const mounted = new WeakMap();
  const labels = { running:'执行中', completed:'已完成', failed:'失败', building:'构建中', built:'已构建', passed:'通过', pass:'通过', fail:'受阻', warning:'待验收', blocked:'受阻', 'not-tested':'未验收', uploaded:'已上传', unknown:'需对账', uploading:'上传中', 'not-uploaded':'未上传' };
  const provider = { 'wechat-minigame':['wechat-ci','2.1.31'], 'douyin-minigame':['douyin-cli','2.1.1'], poki:['poki-cli','0.1.19'] };
  const label = value => labels[value] || value || '未记录';
  function el(tag, text, cls) { const n = document.createElement(tag); if (text !== undefined) n.textContent = text; if (cls) n.className = cls; return n; }
  function mount(host) {
    let session, snapshot, config, revision, environment, selected='web', profile='debug', page='build', refreshing=false, submitting=false, disposed=false, dirty=false, envDirty=false, seenJob='', selectedArtifact='', uploadPlan, configRoot, lastBuildSignature='';
    const root=el('div',undefined,'fwb-workbench fwe-surface'); root.dataset.testid='fwb-workbench';
    const style=el('style'); style.textContent='.fwb-workbench{display:flex;flex-direction:column;gap:16px;padding:8px 4px;min-width:0}.fwb-workbench h2,.fwb-workbench h3,.fwb-workbench p{margin:0}.fwb-workbench h2{font-size:24px}.fwb-workbench h3{font-size:16px}.fwb-muted{color:var(--muted,#69788b);font-size:12px;line-height:1.7}.fwb-toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.fwb-card{border:1px solid var(--line,#d5dce6);background:var(--panel);padding:16px;display:flex;flex-direction:column;gap:12px;min-width:0}.fwb-platforms{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.fwb-workbench button[aria-pressed=true]{border-color:var(--accent);background:var(--accent);color:white}.fwb-columns{display:grid;grid-template-columns:minmax(280px,1fr) minmax(280px,1fr);gap:16px}.fwb-workbench input:not([type=checkbox]),.fwb-workbench select,.fwb-workbench textarea{box-sizing:border-box;min-height:34px;padding:6px 8px;border:1px solid var(--line);color:var(--text);background:var(--panel);min-width:0;max-width:100%}.fwb-field{display:flex;flex-direction:column;gap:6px;font-size:13px}.fwb-field input{width:100%}.fwb-field .fwb-toolbar input{flex:1}.fwb-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.fwb-notice{padding:12px;background:var(--bg);border-left:3px solid var(--accent);white-space:pre-wrap;font-size:13px;line-height:1.6}.fwb-notice[data-error=true]{border-color:#c2483a;color:#a12b20}.fwb-row{padding:12px;border:1px solid var(--line);display:flex;flex-direction:column;gap:8px;overflow-wrap:anywhere}.fwb-check{padding:10px 0;border-bottom:1px solid var(--line);font-size:13px;line-height:1.6}.fwb-workbench pre{margin:0;max-height:440px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;line-height:1.6}.fwb-workbench [hidden]{display:none!important}.fwb-workbench a{color:var(--accent)}.fwb-workbench dialog{background:var(--panel);color:var(--text);border:1px solid var(--line);width:min(720px,85vw);max-height:80vh}.fwb-browser-list{display:flex;flex-direction:column;gap:5px;max-height:45vh;overflow:auto}.fwb-browser-list button{text-align:left}.fwb-workbench button{white-space:normal}.fwb-workbench button:disabled{opacity:.5}.fwb-nav button{padding:9px 14px}@media(max-width:1000px){.fwb-columns{grid-template-columns:1fr}}@media(max-width:640px){.fwb-platforms,.fwb-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}';
    const notify=(message,error=false)=>{ notice.textContent=message; notice.dataset.error=String(error); };
    function button(text, action, primary=false) { const n=el('button',text,'fwe-surface-button'); n.type='button'; if(primary)n.dataset.tone='primary'; n.addEventListener('click',()=>void Promise.resolve().then(action).catch(e=>notify(e.message,true))); return n; }
    const heading=el('h2','构建工作台'), projectText=el('p','正在读取工程…','fwb-muted');
    const nav=el('div',undefined,'fwb-toolbar fwb-nav'), notice=el('div','接入工程 → 配置环境 → 检查平台 → 构建与验收','fwb-notice'); notice.setAttribute('role','status');
    const panels={}, tabs={};
    for(const [id,name] of Object.entries({build:'构建',project:'工程接入',environment:'本机环境',platform:'平台设置',publish:'验收与上传'})) { panels[id]=el('section',undefined,'fwb-card'); tabs[id]=button(name,()=>showPage(id)); nav.append(tabs[id]); }
    const platformButtons=el('div',undefined,'fwb-platforms');
    const title=el('h3','Web 浏览器'), support=el('p',undefined,'fwb-muted');
    const picker=el('select'); picker.setAttribute('aria-label','构建配置'); picker.addEventListener('change',()=>{profile=picker.value; uploadPlan=undefined; renderBuild();});
    const check=button('检查环境',()=>command('doctor',{target:selected,profile})); check.dataset.testid='fwb-doctor';
    const build=button('构建',()=>command('build',{target:selected,profile}),true); build.dataset.testid='fwb-build';
    const batch=button('批量构建已启用平台',()=>command('build.batch',{targets:snapshot.platforms.filter(item=>item.enabled).map(item=>item.target),profile}));const cancel=button('取消构建',()=>command('build.cancel',{jobId:snapshot.activeJobId},true));
    const controls=el('div',undefined,'fwb-toolbar'); controls.append(picker,check,build,batch,cancel,button('平台设置',()=>showPage('platform')),button('刷新',()=>refresh()));
    const explanation=el('p','debug 用于调试；release 用于交付。两种配置分别检查，构建成功后仍需运行和平台验收。','fwb-muted');
    const checks=el('div'); checks.dataset.testid='fwb-diagnostics';
    const artifacts=el('div'); artifacts.dataset.testid='fwb-artifacts';
    const left=el('section',undefined,'fwb-card'),right=el('section',undefined,'fwb-card'),columns=el('div',undefined,'fwb-columns');
    left.append(title,support,controls,explanation,checks); right.append(el('h3','构建产物'),artifacts); columns.append(left,right);
    panels.build.append(platformButtons,columns);
    const detailsTitle=el('h3','任务与日志'),details=el('pre','构建阶段和日志会在这里实时更新。'); details.dataset.testid='fwb-details';
    const detailsCard=el('section',undefined,'fwb-card'); detailsCard.append(detailsTitle,details);
    root.append(style,heading,projectText,nav,notice,...Object.values(panels),detailsCard); host.replaceChildren(root);
    async function api(url,options={}) { const response=await fetch(url,{cache:'no-store',...options,headers:window.fwe.session.headers(options.headers||{})}); const body=await response.json(); if(!response.ok)throw new Error(body.error||'请求失败 '+response.status); return body; }
    const get=(obj,key)=>key.split('.').reduce((value,part)=>value?.[part],obj);
    function put(obj,key,value) { const parts=key.split('.'); let parent=obj; for(const part of parts.slice(0,-1))parent=parent[part] ||= {}; if(value==='')delete parent[parts.at(-1)]; else parent[parts.at(-1)]=value; }
    function field(host,text,obj,key,{type='text',hint='',browse=false,dirs=false,options}={}) {
      const wrap=el('label',undefined,'fwb-field'),caption=el('span',text),input=el(options?'select':'input'); input.setAttribute('aria-label',text);
      if(options) for(const [value,name] of options) {const option=el('option',name);option.value=value;input.append(option);}
      else input.type=type;
      if(type==='checkbox') input.checked=get(obj,key)===true; else input.value=get(obj,key)??'';
      const change=()=>{put(obj,key,type==='checkbox'?input.checked:type==='number'&&input.value!==''?Number(input.value):input.value);if(obj===environment?.config)envDirty=true;else dirty=true;uploadPlan=undefined;};
      input.addEventListener('input',change); input.addEventListener('change',change);
      wrap.append(caption);
      if(browse){const row=el('div',undefined,'fwb-toolbar');row.append(input,button('浏览…',()=>browsePath(input.value,dirs,value=>{input.value=value;change();})));wrap.append(row);}else wrap.append(input);
      if(hint)wrap.append(el('span',hint,'fwb-muted'));host.append(wrap);return input;
    }
    async function browsePath(current,dirs,choose) {
      const dialog=el('dialog'),bar=el('div',undefined,'fwb-toolbar'),address=el('input');address.setAttribute('aria-label','浏览目录');
      const entries=el('div',undefined,'fwb-browser-list'),error=el('p',undefined,'fwb-muted');let directory=snapshot.project.root;
      address.value=current&&/[/\\]/.test(current)?current:snapshot.project.root;
      const load=async value=>{try{const response=await api('/api/fwb/commands',{method:'POST',headers:{'Content-Type':'application/json','X-FWB-CSRF':session.csrfToken},body:JSON.stringify({type:'paths.browse',payload:{path:value,directoriesOnly:dirs}})});const result=response.job.result;directory=result.directory;address.value=directory;entries.replaceChildren();entries.append(button('↑ 上一级',()=>load(result.parent)));for(const entry of result.entries)entries.append(button((entry.directory?'文件夹 · ':'文件 · ')+entry.name,()=>entry.directory?load(entry.path):(choose(entry.path),dialog.close())));error.textContent='';}catch(e){error.textContent=e.message;}};
      bar.append(address,button('打开目录',()=>load(address.value)),button('关闭',()=>dialog.close()));if(dirs)bar.append(button('选择此目录',()=>{choose(directory);dialog.close();},true));
      dialog.append(bar,error,entries);root.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();
      await load(address.value);
    }
    function showPage(value) { page=value;for(const [id,panel]of Object.entries(panels)){panel.hidden=id!==page;tabs[id].setAttribute('aria-pressed',String(id===page));}if(value==='platform')renderPlatform();if(value==='publish')void renderPublish(); }
    async function loadConfiguration() { const value=await api('/api/fwb/config');config=value.config;revision=value.revision;configRoot=snapshot.project.root;dirty=false;renderProject();renderPlatform(); }
    async function loadEnvironment() {environment=await api('/api/fwb/environment');envDirty=false;renderEnvironment();}
    function saveSettings(){return command('settings.save',{config,revision});}
    function renderProject() {
      if(!config)return;const panel=panels.project;panel.replaceChildren(el('h3','接入自己的 Godot 工程'),el('p','选择包含 project.godot 的文件夹。首次接入只创建 FWB 配置；已有游戏和已有配置会保留。','fwb-muted'));
      const draft={path:snapshot.project.root,initialize:true},row=el('div',undefined,'fwb-grid');field(row,'游戏工程目录',draft,'path',{browse:true,dirs:true});field(row,'首次接入时创建 FWB 配置',draft,'initialize',{type:'checkbox'});panel.append(row,button('打开 / 接入工程',()=>command('project.open',draft),true));
      const recent=el('div',undefined,'fwb-toolbar');for(const item of snapshot.recentProjects||[])recent.append(button(item,()=>command('project.open',{path:item,initialize:false})));panel.append(recent,el('h3','工程参数'));
      const form=el('div',undefined,'fwb-grid');field(form,'游戏名称',config,'name');field(form,'版本号',config,'version');field(form,'构建序号',config,'buildNumber',{type:'number'});field(form,'启用 FWB 运行时桥接',config,'runtimeAddon',{type:'checkbox',hint:'当前内置 Poki 生命周期和广告桥接；其他渠道仍需对应适配。'});
      field(form,'工程 Godot 路径（可选）',config,'godot.executable',{browse:true,hint:'留空继承本机环境。'});field(form,'工程 Godot 版本（可选）',config,'godot.version');field(form,'工程导出模板（可选）',config,'godot.templatesPath',{browse:true,dirs:true});
      panel.append(form,button('保存工程参数',saveSettings,true),button('重新读取工程配置',loadConfiguration));
    }
    function renderEnvironment() {
      if(!environment)return;const panel=panels.environment;panel.replaceChildren(el('h3','本机共享环境'),el('p','这台电脑配置一次，多个游戏共享。优先级：平台覆盖 → 工程覆盖 → 本机环境 → 系统环境。保存后无需重启，重新检查即可。','fwb-muted'));
      const form=el('div',undefined,'fwb-grid');field(form,'Godot 可执行文件',environment.config,'godot.executable',{browse:true});field(form,'Godot 版本',environment.config,'godot.version',{hint:'例如 4.6.2；可留空，由检查读取实际版本。'});field(form,'Godot 导出模板目录',environment.config,'godot.templatesPath',{browse:true,dirs:true});field(form,'Android SDK 目录',environment.config,'android.androidSdkPath',{browse:true,dirs:true});field(form,'JDK 目录',environment.config,'android.javaHome',{browse:true,dirs:true});
      panel.append(button('识别当前工程 / 系统工具路径',()=>command('environment.detect',{target:selected})),form,button('保存本机环境',()=>command('environment.save',{config:environment.config,revision:environment.revision}),true),button('检查当前平台环境',()=>{showPage('build');return command('doctor',{target:selected,profile});}),button('重新读取本机环境',loadEnvironment),el('p','Android SDK/JDK 会写入本次构建的隔离编辑器设置。App Store 需要在 Mac 上运行；当前尚未接入远程 Mac。','fwb-muted'),el('p','保存位置：'+environment.file,'fwb-muted'));
    }
    function renderPlatform() {
      if(!config||!snapshot)return;const panel=panels.platform;panel.replaceChildren(el('h3','平台参数'));
      const select=el('select');select.setAttribute('aria-label','设置平台');for(const item of snapshot.platforms){const option=el('option',item.label);option.value=item.target;select.append(option);}select.value=selected;select.addEventListener('change',()=>{selected=select.value;uploadPlan=undefined;renderPlatform();renderBuild();});panel.append(select);
      const descriptor=snapshot.platforms.find(item=>item.target===selected);panel.append(el('p',descriptor.requirements.join('；'),'fwb-muted'));
      const base='targets.'+selected;config.targets[selected] ||= {enabled:false,preset:['web','poki','taptap-h5'].includes(selected)?'Web':selected==='google-play'?'Android':selected==='app-store'?'iOS':selected==='wechat-minigame'?'WeChat':'Douyin'};
      const form=el('div',undefined,'fwb-grid');field(form,'启用此平台',config,base+'.enabled',{type:'checkbox'});field(form,'导出预设名称',config,base+'.preset');field(form,'包体预算（字节，可选）',config,base+'.maxBytes',{type:'number'});
      if(!['web','poki','taptap-h5'].includes(selected))field(form,selected==='app-store'?'Bundle ID':'应用 ID / 包名',config,base+'.applicationId');
      if(selected==='app-store')field(form,'Apple Team ID',config,base+'.teamId');
      const extra=el('details'),summary=el('summary','覆盖此平台的工具链（可选）'),extraForm=el('div',undefined,'fwb-grid');extra.append(summary,extraForm);
      field(extraForm,'平台 Godot 路径',config,base+'.godot.executable',{browse:true,hint:'留空继承工程与本机环境。'});field(extraForm,'平台 Godot 版本',config,base+'.godot.version');field(extraForm,'平台导出模板目录',config,base+'.godot.templatesPath',{browse:true,dirs:true});
      if(descriptor.family==='minigame'){
        field(form,'平台适配 SDK 目录',config,base+'.sdkPath',{browse:true,dirs:true});field(form,'SDK 版本',config,base+'.sdkVersion');field(form,'适配器导出平台名称',config,base+'.exportPlatform');
        panel.append(el('p','微信 / 抖音需要实际引擎适配器。本页保存路径与验证声明，不会把普通 Web 包转换为小游戏。','fwb-notice'));
        field(form,'适配验证报告文件',config,base+'.validation.evidence',{browse:true});field(form,'报告中的 Godot 版本',config,base+'.validation.godotVersion');field(form,'报告中的 SDK 版本',config,base+'.validation.sdkVersion');field(form,'适配验证声明',config,base+'.validation.status',{options:[['','尚未验证'],['verified','已完成对应版本实测（需报告）']]});
      }
      if(selected==='google-play'){
        field(extraForm,'平台 Android SDK 目录',config,base+'.androidSdkPath',{browse:true,dirs:true});field(extraForm,'平台 JDK 目录',config,base+'.javaHome',{browse:true,dirs:true});field(form,'发布签名证书路径',config,base+'.signing.keystorePath',{browse:true});field(form,'签名别名所在环境变量',config,base+'.signing.userEnv',{hint:'例如 ANDROID_KEY_ALIAS，只保存变量名称。'});field(form,'签名密码所在环境变量',config,base+'.signing.passwordEnv',{hint:'例如 ANDROID_KEY_PASSWORD，密码不保存在工程配置。'});
      }
      const upload=el('details'),uploadForm=el('div',undefined,'fwb-grid');upload.append(el('summary','上传配置'),uploadForm);
      field(uploadForm,'上传方式',config,base+'.upload.provider',{options:[['handoff','人工交接到平台控制台'],...(provider[selected]?[[provider[selected][0],'官方工具上传开发版本']]:[])]});
      if(provider[selected]){
        field(uploadForm,'上传应用 ID',config,base+'.upload.applicationId');field(uploadForm,'上传工具包目录',config,base+'.upload.packagePath',{browse:true,dirs:true});field(uploadForm,'上传工具版本',config,base+'.upload.toolVersion',{hint:'当前接口支持 '+provider[selected][1]});field(uploadForm,'版本说明',config,base+'.upload.notes');
        if(selected==='wechat-minigame'){field(uploadForm,'上传私钥路径所在环境变量',config,base+'.upload.privateKeyPathEnv');field(uploadForm,'上传机器人编号',config,base+'.upload.robot',{type:'number'});}
      }
      panel.append(form,extra,upload,button('保存平台设置',saveSettings,true));
      if(descriptor.family!=='minigame')panel.append(button('补全缺失导出预设',()=>command('preset.create',{target:selected})));
      panel.append(button('检查此平台',()=>{showPage('build');return command('doctor',{target:selected,profile});}));
    }
    function diagnosis(target=selected) {const job=snapshot.jobs.find(job=>(job.type==='doctor'||job.type==='build'&&job.result?.diagnosis||job.type==='build.batch'&&job.diagnostics?.[target])&&(job.payload.target===target||job.payload.targets?.includes(target))&&job.payload.profile===profile&&job.generation===snapshot.generation&&job.environmentRevision===snapshot.environmentRevision&&job.status==='completed');return job?.type==='build'?{...job,result:job.result.diagnosis}:job?.type==='build.batch'?{...job,result:job.diagnostics[target]}:job;}
    function renderBuild() {
      if(!snapshot)return;const platform=snapshot.platforms.find(item=>item.target===selected),busy=submitting||Boolean(snapshot.activeJobId),report=diagnosis();
      title.textContent=platform.label;support.textContent=selected==='taptap-h5'?'目标是在手机 TapTap App 内点开游玩；本地预览通过后仍需 App 内验收。':platform.family==='minigame'?'适配尚需验证：须准备对应引擎、SDK 和真实导出预设。':selected==='app-store'?'Godot 导出 Xcode 工程；签名归档和 TestFlight 尚需在 Mac 完成。':platform.requirements.join('；');
      check.disabled=busy||!platform.configured;build.disabled=busy||!platform.enabled||report?.result?.ok===false;picker.disabled=busy;batch.disabled=busy||!snapshot.platforms.some(item=>item.enabled);
      cancel.hidden=!snapshot.jobs.some(job=>job.id===snapshot.activeJobId&&['build','build.batch'].includes(job.type));cancel.disabled=submitting;
      platformButtons.replaceChildren();for(const item of snapshot.platforms){const previous=diagnosis(item.target);const status=!item.configured?'未配置':!item.enabled?'已停用':previous?previous.result.ok?'环境通过 · 待验收':'缺少条件':item.family==='minigame'?'待适配验证':item.support!=='supported'?'待平台验收':'待检查';const b=button(item.label+' · '+status,()=>{selected=item.target;selectedArtifact='';uploadPlan=undefined;renderBuild();});b.setAttribute('aria-pressed',String(item.target===selected));platformButtons.append(b);}
      checks.replaceChildren();if(!report)checks.append(el('p',platform.enabled?'尚未检查 '+profile+' 配置，构建前会自动预检。':'此平台尚未启用，请进入平台设置。','fwb-muted'));
      else {checks.append(el('p','检查配置：'+profile,'fwb-muted'));for(const item of [...report.result.checks].sort((a,b)=>Number(a.status==='pass')-Number(b.status==='pass'))){const row=el('div',undefined,'fwb-check');row.append(el('strong',label(item.status)+' · '+item.message));if(item.action&&item.status!=='pass')row.append(el('p',item.action,'fwb-muted'));if(item.status==='fail')row.append(button(/godot|jdk|android-sdk|android-build-tools|android-platform|export-template|template-version/.test(item.id)?'配置环境':'配置平台',()=>showPage(/godot|jdk|android-sdk|android-build-tools|android-platform|export-template|template-version/.test(item.id)?'environment':'platform')));checks.append(row);}checks.append(el('p','实际 Godot：'+(report.result.engine?.executable||'未找到')+'；模板：'+(report.result.engine?.templatesPath||'未找到'),'fwb-muted'));}
      artifacts.replaceChildren();const relevant=snapshot.artifacts.filter(item=>item.target===selected);if(!relevant.length)artifacts.append(el('p','这个平台还没有构建产物。','fwb-muted'));
      for(const artifact of relevant.slice(0,20)){const row=el('div',undefined,'fwb-row');row.append(el('strong',artifact.profile+' · '+label(artifact.status)),el('p',artifact.id,'fwb-muted'),el('p','包体：'+label(artifact.validation?.package)+' · 运行：'+label(artifact.validation?.runtime)+' · 平台：'+label(artifact.validation?.platform),'fwb-muted'));const actions=el('div',undefined,'fwb-toolbar');actions.append(button('记录 / 日志',async()=>{selectedArtifact=artifact.id;const value=await api('/api/fwb/artifact?id='+encodeURIComponent(artifact.id));showDetails('产物 '+artifact.id,JSON.stringify({...value,logText:undefined},null,2)+'\n'+value.logText);}));
        if(artifact.status==='built'){const open=button('打开目录',()=>command('artifact.open',{artifactId:artifact.id}));open.disabled=busy;const download=el('a','下载交付 ZIP');download.href='/api/fwb/download?id='+encodeURIComponent(artifact.id);download.download=artifact.id+'.zip';const validate=button('校验包体',()=>command('validate',{artifactId:artifact.id}));validate.disabled=busy;actions.append(open,download,validate,button('验收 / 上传',()=>{selectedArtifact=artifact.id;showPage('publish');}));if(['web','taptap-h5','poki'].includes(selected)){const preview=button('启动预览',()=>command('preview',{artifactId:artifact.id}));preview.disabled=busy;actions.append(preview);}}
        row.append(actions);artifacts.append(row);}
    }
    async function renderPublish(){
      if(!snapshot)return;const panel=panels.publish;panel.replaceChildren(el('h3','验收与上传'),el('p','包体校验、运行验收、平台验收分别记录。上传仅进入开发版本；审核与正式上线在平台操作。','fwb-muted'));
      const choices=snapshot.artifacts.filter(a=>a.status==='built'),select=el('select');select.setAttribute('aria-label','验收产物');select.append(el('option','请选择构建产物'));select.firstChild.value='';for(const artifact of choices){const option=el('option',artifact.target+' / '+artifact.profile+' / '+artifact.id);option.value=artifact.id;select.append(option);}select.value=selectedArtifact;select.addEventListener('change',()=>{selectedArtifact=select.value;uploadPlan=undefined;void renderPublish();});panel.append(select);
      if(selectedArtifact&&choices.some(a=>a.id===selectedArtifact)){
        const currentArtifact=choices.find(a=>a.id===selectedArtifact);panel.append(el('p','包体：'+label(currentArtifact.validation?.package)+' · 运行：'+label(currentArtifact.validation?.runtime)+' · 平台：'+label(currentArtifact.validation?.platform),'fwb-notice'));const artifactId=selectedArtifact,draft={kind:'runtime',result:'passed',file:'',note:''},form=el('div',undefined,'fwb-grid');field(form,'验收类型',draft,'kind',{options:[['runtime','运行验收'],['platform','平台验收']]});field(form,'验收结果',draft,'result',{options:[['passed','通过'],['failed','失败']]});field(form,'验收报告文件',draft,'file',{browse:true});field(form,'验收备注',draft,'note');panel.append(form,button('登记已有验收报告',()=>command('evidence',{artifactId,...draft})),button('检查上传条件',()=>command('upload-plan',{artifactId}),true));
        if(uploadPlan?.artifactId===artifactId){const plan=uploadPlan;panel.append(el('p','目标：'+plan.target+' · 应用：'+(plan.applicationId||'未配置')+' · 版本：'+plan.version+'（'+plan.buildNumber+'）','fwb-muted'));panel.append(el('p',plan.canExecute?'上传条件通过，可以上传开发版本。':plan.status==='handoff'?'此平台使用人工交接。':'上传条件尚未满足。','fwb-notice'));for(const check of plan.checks||[])panel.append(el('p',label(check.status)+' · '+check.message+(check.action&&check.status!=='pass'?' '+check.action:''),'fwb-muted'));if(plan.handoff?.url){const link=el('a','打开 '+plan.handoff.destination);link.href=plan.handoff.url;link.target='_blank';link.rel='noopener noreferrer';panel.append(link);}for(const step of plan.handoff?.steps||[])panel.append(el('p',step,'fwb-muted'));if(plan.canExecute){const confirmation={confirmed:false};const checkbox=field(panel,'已核对应用、版本和产物，确认上传开发版本',confirmation,'confirmed',{type:'checkbox'});const execute=button('上传开发版本',()=>command('upload.execute',{artifactId,revision:plan.projectRevision,outputsSha256:plan.outputsSha256,confirmed:checkbox.checked}),true);execute.disabled=true;checkbox.addEventListener('change',()=>{execute.disabled=!checkbox.checked;});panel.append(execute);}}
      }
      const history=el('div');panel.append(el('h3','上传记录与异常对账'),history);try{const records=await api('/api/fwb/releases');if(page!=='publish'||disposed)return;if(!records.length)history.append(el('p','尚无上传记录。','fwb-muted'));for(const record of records){const row=el('div',undefined,'fwb-row');row.append(el('p',record.id+' · '+label(record.status)));const receipt={releaseId:record.id,status:'uploaded',remoteId:'',evidence:''};if(['unknown','uploading','uploaded'].includes(record.status)){field(row,'平台核对结果',receipt,'status',{options:[['uploaded','已在平台确认上传'],['not-uploaded','已在平台确认未上传']]});field(row,'远端版本 ID',receipt,'remoteId');field(row,'对账报告文件',receipt,'evidence',{browse:true});row.append(button('登记人工对账结果',()=>command('receipt.record',receipt)));}history.append(row);}}catch(e){history.textContent=e.message;}
    }
    function showDetails(title,value){detailsTitle.textContent=title;details.textContent=typeof value==='string'?value:JSON.stringify(value,null,2);}
    async function refresh(){
      if(refreshing||disposed)return;refreshing=true;try{session ||= await api('/api/fwb/session');snapshot=await api('/api/fwb/snapshot');projectText.textContent=snapshot.project.name+' · '+snapshot.project.root;
        if(!config||configRoot!==snapshot.project.root)await loadConfiguration();if(!environment)await loadEnvironment();
        if(!snapshot.profiles.includes(profile))profile=snapshot.profiles[0];if([...picker.options].map(o=>o.value).join('|')!==snapshot.profiles.join('|')){picker.replaceChildren();for(const name of snapshot.profiles){const option=el('option',name);option.value=name;picker.append(option);}}picker.value=profile;
        const nextBuildSignature=JSON.stringify({platforms:snapshot.platforms,artifacts:snapshot.artifacts,generation:snapshot.generation,environmentRevision:snapshot.environmentRevision,active:snapshot.activeJobId,jobs:snapshot.jobs.map(job=>[job.id,job.status])});if(nextBuildSignature!==lastBuildSignature){lastBuildSignature=nextBuildSignature;renderBuild();}const recent=snapshot.jobs[0];if(recent){const key=recent.id+':'+recent.status;if(recent.status==='running')showDetails('执行中 · '+(recent.phase||recent.type),recent.output||'正在执行，请稍候…');if(key!==seenJob){seenJob=key;if(recent.status==='failed'){notify(recent.error||'任务失败',true);showDetails('任务失败',recent);}else if(recent.status==='completed'){
          if(['settings.save','config.save','project.open'].includes(recent.type))await loadConfiguration();if(recent.type==='environment.save')await loadEnvironment();if(recent.type==='environment.detect'){Object.assign(environment.config.godot,recent.result.godot);Object.assign(environment.config.android,recent.result.android);envDirty=true;renderEnvironment();}
          if(recent.type==='upload-plan'){uploadPlan=recent.result;selectedArtifact=recent.payload.artifactId;showPage('publish');}else if(['evidence','receipt.record','upload.execute'].includes(recent.type))void renderPublish();
          notify(recent.result?.ok===false?'检查发现阻塞项，请按提示配置。':recent.type==='build'?'构建完成。请继续运行和平台验收。':recent.type.includes('save')?'已保存并生效，请重新检查环境。':'操作完成。',recent.result?.ok===false);
          showDetails('任务完成 · '+recent.type,recent.type==='build'?{artifactId:recent.result.id,target:recent.result.target,profile:recent.result.profile,status:recent.result.status,validation:recent.result.validation,completedAt:recent.result.completedAt}:recent.result);if(recent.type==='preview'&&recent.result?.url){const a=el('a','打开游戏预览');a.href=recent.result.url;a.target='_blank';a.rel='noopener noreferrer';notice.append(document.createTextNode(' '),a);}
        }}}for(const id of ['project','platform','environment','publish']){const busy=submitting||Boolean(snapshot.activeJobId);for(const input of panels[id].querySelectorAll('input,select,textarea'))input.disabled=busy;}
      }catch(e){notify(e.message,true);}finally{refreshing=false;}}
    async function command(type,payload,interrupt=false){if(!session||submitting||snapshot?.activeJobId&&!interrupt)throw new Error('请等待当前任务完成。');submitting=true;try{if(['build','build.batch','doctor'].includes(type))selectedArtifact='';const response=await api('/api/fwb/commands',{method:'POST',headers:{'Content-Type':'application/json','X-FWB-CSRF':session.csrfToken},body:JSON.stringify({type,payload})});notify(type==='build.cancel'?'正在取消构建…':'操作已开始。');return response;}finally{submitting=false;await refresh();}}
    showPage('build');void refresh();const timer=setInterval(()=>void refresh(),1000);
    return {root,dispose(){disposed=true;clearInterval(timer);root.remove();}};
  }
  window.fwe.registerWorkbenchLayout('fwb-workbench',{noInspector:()=>true,render(ctx){const host=ctx.hosts.documentTree;ctx.showView('document');if(!mounted.get(host)?.root.isConnected){mounted.get(host)?.dispose();mounted.set(host,mount(host));}}});
}());
